### ISSUE TITLE
Sigeldatenbank auf rism.info, Status eines Sigels berücksichtigen

### ISSUE THREAD

**Issue by Docudoctor** [rism-international/tasks#1000]
Bitte bei der Publikation in der Sigeldatenbank auf rism.info den Status (published/ unpublished) eines Sigel-Katalogisates berücksichtigen.
RISM-Sigel mit dem Status "In Arbeit/ Unpublished" bitte von der Publikation ausschließen. 
Schönen Dank, Guido.

**Comment by HirschSt** [comment]
Ich bin etwas irritiert, hatten wir nicht auf der Sitzung am 4. Mai 2023 beschlossen, dass der Status (published/unpublished) bei Normdaten keine Relevanz mehr besitzt?

**Comment by Docudoctor** [comment]
Ich habe fünf Sigel in der Diskussion. Sie sollten nicht jetzt schon veröffentlicht sein.
