### ISSUE TITLE
Sortierung von Einzeleinträgen nach ID bei PiKaDo-Titeln

### ISSUE THREAD

**Issue by HirschSt** [rism-international/tasks#1003]

**Comment by HirschSt** [comment]
done with https://github.com/rism-international/muscat-maintenance/commit/1b85910adc37cbd70ebadbabf273ef1d20c0b37d

@Docudoctor bitte anhand von https://github.com/rism-international/muscat-maintenance/blob/master/log/20230714_order_collections.log stichprobenartig auf beta testen

**Comment by Docudoctor** [comment]
Getestet. Sieht gut aus!!

**Comment by HirschSt** [comment]
Prima, dann kann das demnächst in Produktion laufen

**Comment by HirschSt** [comment]
Ist jetzt auch auf prod umgesetzt

**Comment by jenniferward** [comment]
Ich habe Titel aus Belgien gefunden, die auch eine falsche Sortierung haben, die aber nicht auf der log-Liste stehen. Weißt du, warum @HirschSt ?
https://muscat.rism.info/admin/sources/702012351 
702012363, 702012364... und am Ende 702012365.

https://muscat.rism.info/admin/sources/702011464: Alles durcheinander

**Comment by HirschSt** [comment]
Bei dem Ablauf wurden alle (PiKaDo-)Titel selektiert, die vor 2007 erstellt wurden, um Kallisto-Titel sicher auszuschließen. Daher gehe ich davon aus, dass es sich bei diesen Titeln um Kallisto-Titel handelt.

**Comment by jenniferward** [comment]
Ich habe beide Titel in der Liste hier gefunden: https://github.com/rism-international/tasks/issues/949 

Dieser Titel aus D steht auch auf der Pikado-Liste und nicht richtig sortiert: https://muscat.rism.info/admin/sources/469185300
