### ISSUE TITLE
Import Kirchenlied xml

### ISSUE THREAD

**Issue by HirschSt** [rism-international/tasks#1015]

**Comment by HirschSt** [comment]
@jenniferward Import kann vorübergehend unter beta geprüft werden, z.B. https://beta.rism.info/admin/sources/457001200

**Comment by jenniferward** [comment]
Die Einzeleinträgen sehen korrekt aus. 
Nur bei den Haupteinträgen fehlt die Verlinkung zu den Einzeleinträgen noch. https://beta.rism.info/admin/sources/990054385 hat z.B. 201 Einzeleinträgen, in z.B. https://beta.rism.info/admin/sources/457001664 korrekt verlinkt.
