### ISSUE TITLE
ICCU Komponisten in Einzeleinträge vererben

### ISSUE THREAD

**Issue by HirschSt** [rism-international/tasks#1017]
s. folder  https://muscat.rism.info/admin/folders/1102

**Comment by HirschSt** [comment]
dazu signatur und besetzung (?)

**Comment by Docudoctor** [comment]
Dazu später mehr. Ist noch nicht zu Ende gesichtet.

**Comment by Docudoctor** [comment]
Den Ablauf "ICCU Komponisten in Einzeleinträge vererben" bitte in Gang setzen.
Danke.

**Comment by HirschSt** [comment]
Ist umgesetzt.
