### ISSUE TITLE
Ergänze die Provenienz "Zakład Muzykologii Uniwersytetu Wrocławskiego" in Einträgen von PL-Wu

### ISSUE THREAD

**Issue by Docudoctor** [rism-international/tasks#1018]
Bitte diese Provenienz https://muscat.rism.info/admin/institutions/51007403 im MARC-Feld 710 zusammen mit der Funktionsbezeichnung "Vorbesitzer" in folgenden Einträgen von PL-Wu ergänzen: 
Alle Collection-Haupteinträge mit den Templates "Musikhandschrift, Haupteintrag Sammlung" und "Musikdruck, Haupteintrag Sammlung" sowie alle Individualeinträge mit den Templates "Musikhandschrift, Individualeintrag" und "Musikdruck, Individualeintrag". 

Besten Dank.

**Comment by HirschSt** [comment]
Bitte kurz prüfen, ob die Provinienz wirklich bei "Musikdruck, Haupteintrag Sammlung" ergänzt werden soll. Meiner Ansicht nach gehört das doch eher in die Holdingeinträge aus PL-Wu

**Comment by Docudoctor** [comment]
Ja natürlich. Bei Drucken geht es nur um die Holdings von PL-Wu!
Danke schön.

**Comment by HirschSt** [comment]
Alles klar, danke. Kann jetzt auf beta bzw. mit https://github.com/rism-international/muscat-maintenance/blob/master/log/20231030-add_provenance.log geprüft werden.

**Comment by Docudoctor** [comment]
Sieht gut aus! Kann in die Produktion gehen. 
Danke dir.
