### ISSUE TITLE
Besetzungshinweis

### ISSUE THREAD

**Issue by alexandermarxen** [rism-international/tasks#1019]
Vor allem durch A/I sind zahlreiche falsche Einträge im Feld Bestzungshinweis (240 $m) entstanden. Bitte die falschen Einträge aus dieser Tabelle per Script korrigieren:
https://docs.google.com/spreadsheets/d/1TR3_NMC-1WpNFqSQpWkhJXZ_fZewfGkN6DxnkfGJk1s/edit?pli=1#gid=0

**Comment by HirschSt** [comment]
Gleiche Tabelle in Markdown

falsch | richtig
-- | --
2 V | V (2)
2 V, pf | V (2), pf
2 fl | fl (2)
2 i | i (2)
2 vl | vl (2)
2 vl, 2 vla, vlc | vl (2), vla (2), vlc
2 vl, a-vla, b | vl (2), vla, b
2 vl, a-vla, vlc | vl (2), vla, vlc
2 vl, b | vl (2), b
2 vl, t-vla, vlc | vl (2), vla, vlc
2 vl, vla, b | vl (2), vla, b
2 vl, vla, vlc | vl (2), vla, vlc
2 vl, vlc | vl (2), vlc
3 V | V (3)
3 V, pf | V (3), pf
4 V | V (4)
coro | Coro
coro maschile | Coro maschile
Lute | lute
pf4hands | pf 4hands
pf 4 hands | pf 4hands
Singst., Klv. | V, pf
V(1) | V

**Comment by HirschSt** [comment]
Bitte anhand von beta bzw. https://github.com/rism-international/muscat-maintenance/blob/master/log/20231104-change-scoring.log stichprobenartig prüfen

**Comment by alexandermarxen** [comment]
Vielen Dank, sieht sehr gut aus!
