### ISSUE TITLE
856 $z ergänzen für A-Sm-Holdings

### ISSUE THREAD

**Issue by BaMikusi** [rism-international/tasks#1020]
Bei früher erfassten A-Sm-Holdings, wo auch 856 benutzt wurde, steht zwar ein Link ($u) und ein Linktyp ($x), allerdings ist $z nicht vorhanden, siehe:
https://docs.google.com/spreadsheets/d/1uowoA-z9YItNnv8NAYNWz3Ur617KH9PIFTV-6Nyot5w/edit#gid=0

In allen Fällen, wo im 856 $x "Other" steht, sollte für $z "bibliographic record" ergänzt werden (die entsprechenden Links fangen mit "http://permalink.obvsg.at/" an).

Dabei sollten die fehlenden $z bei Quellendigitalisaten ($x == "Digitized") einfach stehen bleiben; diese wollen die Kollegen in Salzburg händisch revidieren.

**Comment by HirschSt** [comment]
done with https://github.com/rism-international/muscat-maintenance/commit/caef6cd37eeca4c3f1f51e082e78f1226042c9bf @BaMikusi bitte auf beta strichprobenmäßig prüfen, z.B. https://beta.rism.info/admin/sources/00000990042651

**Comment by BaMikusi** [comment]
Da sieht alles gut aus, danke!

**Comment by HirschSt** [comment]
Ist umgesetzt.
