### ISSUE TITLE
List of 031q/031m if q=="t"

### ISSUE THREAD

**Issue by HirschSt** [rism-international/tasks#1022]

**Comment by HirschSt** [comment]
@alexandermarxen see https://github.com/rism-international/muscat-maintenance/blob/master/report/report_031q.csv

**Comment by alexandermarxen** [comment]
Vielen Dank! Ist wohl nicht so schlimm, wie ich befürchtet habe, es gibt aber einige Fälle, in denen das "t" wirklich für transponierte Incipits verwendet wurde.

**Comment by HirschSt** [comment]
Ok. Melde Dich, falls Du mehr Infos brauchst.
