### ISSUE TITLE
A-Whk Bestandsname ergänzen

### ISSUE THREAD

**Issue by Docudoctor** [rism-international/tasks#1023]
Bitte ergänze in den Katalogisaten des Ordners https://muscat.rism.info/admin/folders/1211
im Feld 852$z den Bestandsnamen "Hofmusikkapelle Wien - Archiv" 
Schönen Dank.

**Comment by BaMikusi** [comment]
Bitte berücksichtigen, dass wir aus dem A-Wn-Import auch weitere Datensätze haben, die ebenso aus A-Whk stammen, allerdings nicht als RISM-Altdaten vorhanden waren, und daher von mir nicht gelöscht wurden, wie z.B.:
https://muscat.rism.info/admin/sources/600102525
Hier wird die Zugehörigkeit als Bestandsname (Provenance) im Feld 852 $z angedeutet: "Hofmusikkapelle Wien - Archiv"
Ich fürchte, für die Nutzer wäre es hoffnungslos verwirrend, wenn diese Provenienzangaben für die verschiedenen Teile der Hofmusikkapelle-Sammlung nicht einheitlich dargestellt wären.

**Comment by jenniferward** [comment]
Ich habe euch ein Beispiel aus dem ÖNB-Import versprochen:
https://muscat.rism.info/admin/sources/600500372/edit 
Alttitel: Provenienzangaben fehlten
Import-Titel: 
Bestandsname (852$z) Leopoldina - Privatbibliothek Kaiser Leopolds I.
Provenienzvermerke (561$a) Aus der Schlafkammerbibliothek Kaiser Leopolds I.

**Comment by Docudoctor** [comment]
Ticket wurde umgeschrieben.

**Comment by Docudoctor** [comment]
Bitte ergänze in den Katalogisaten des Ordners https://muscat.rism.info/admin/folders/1211
im Feld 852$z den Bestandsnamen "Hofmusikkapelle Wien - Archiv"
Schönen Dank.

**Comment by HirschSt** [comment]
Biite kurz auf beta überprüfen, danke!

**Comment by Docudoctor** [comment]
Danke. Sieht gut aus!

**Comment by HirschSt** [comment]
Ist jetzt in Prod umgesetzt.
