### ISSUE TITLE
ICCU-2. Paket: Ergänze ET, SW, Besetz.hinweis und WV mit Nummer

### ISSUE THREAD

**Issue by Docudoctor** [rism-international/tasks#1024]
Ergänze bitte in allen RISM IDs (Spalte A) aus dem Sheet ICCU-2. Paket zeilenweise die Spalten F [STANDARD TITLE (240)], G [SCORING (240m)], H [WORK CATALOG (690)] und I [SUBJECT HEADING (650)]
https://docs.google.com/spreadsheets/d/1Icbe57AgMVlyxK9USCJbFmcHBIC72RLoFlGeWuwE-3o/edit#gid=691573135
Besten Dank.

**Comment by HirschSt** [comment]
Falls Werte bei scoring vorhanden sind: ergänzen oder immer komplett überschreiben?

**Comment by Docudoctor** [comment]
Nur wenn im Sheet Werte in scoring eingetragen sind, bitte in Muscat ergänzen oder überschreiben. :)

**Comment by HirschSt** [comment]
Ist jetzt auf beta umgesetzt, bitte stichprobenartig durchtesten

**Comment by Docudoctor** [comment]
Danke, sieht gut aus.

**Comment by jenniferward** [comment]
Etwas ist mir aufgefallen bei Feldern mit mehreren Angaben:

- 240$m: bei Titeln mit mehreren 240$m  
https://muscat.rism.info/admin/sources/850811852?view=MARC21 
`=240 ##$aTarantella$mcl, fag, pf$mob, fag, pf$03919116`
wurde nur die erste Angabe überschrieben:
https://beta.rism.info/admin/sources/850811852?view=MARC21
`=240 ##$aTarantellas$mcl, fag, pf$mob, fag, pf$03906199`

Ich glaube, Guido meinte, dass 240$m ganz (alle Angaben, auch wiederholten) gelöscht werden soll und dann mit der neuen Angabe aus der Tabelle ergänzt.


- 650: 
https://muscat.rism.info/admin/sources/850726028?view=MARC21
`=650 07$aSymphonies$025215`
`=650 07$aOvertures$025196`

Guido wollte nur `Symphonies` aber `Overtures` ist noch da:
https://beta.rism.info/admin/sources/850726028?view=MARC21
`=650 07$aSymphonies$025215`
`=650 07$aOvertures$025196`

**Comment by BaMikusi** [comment]
Wobei "ergänzen" eigentlich soviel zu sagen scheint, dass was schon dort war, bleiben soll, und wird mit weiteren Angaben nur vervollständigt -- also dann weiß ich ehrlich gesagt nicht mehr, was der ursprüngliche Wunsch war.

**Comment by Docudoctor** [comment]
Das Problem liegt bei den verdoppelbaren Feldern. Es tritt bei der Herstellung der Tabellen auf, sowie beim Einspielen einer Tabelle in Muscat. Beispiele: 
1) Besetzungshinweis: 850715331 (ältere Ergänzung von 2020)
In der Tabelle wird nur der Eintrag aus der ersten Zeile aufgeführt. Die zweite Zeile fehlt. Sie sollte in Zukunft mit Semikolon abgesetzt in Google Sheets-Tabellen mit aufgeführt werden. 
2) Schlagwörter: 850726028
In der Tabelle wurde das zweite Schlagwort gelöscht. Es soll nur das erste Schlagwort in Muscat verbleiben. 
Das zweite Schlagwort ist aber noch auf beta im Eintrag zu finden.

**Comment by HirschSt** [comment]
Die Werte in 240m und 650 werden jetzt komplett von den Werten in der Tabelle überschrieben, bitte erneut nochmal auf beta prüfen.

**Comment by Docudoctor** [comment]
Danke Stephan. 
Für das erste Bsp. Besetzungshinweis funktioniert das nicht, aber für das zweite Bsp. Schlagwörter. 

1)    Besetzungshinweis: 850715331 (ältere Ergänzung von 2020)
    In der Tabelle wird nur der Eintrag aus der ersten Zeile aufgeführt. Die zweite Zeile fehlt. Sie sollte in Zukunft mit Semikolon abgesetzt in Google Sheets-Tabellen mit aufgeführt werden.

2)    Schlagwörter: 850726028
    In der Tabelle wurde das zweite Schlagwort gelöscht. Es soll nur das erste Schlagwort in Muscat verbleiben.
    Das zweite Schlagwort ist aber noch auf beta im Eintrag zu finden.

Bitte die Änderungen einspielen. Die geringe Anzahl von Mehrfacheintragungen im Bestzungshinweis kann gegebenenfalls in Muscat nachgearbeitet werden.

**Comment by HirschSt** [comment]
Danke, wird so gemacht!

**Comment by HirschSt** [comment]
Ist jetzt auf production umgesetzt.
