### ISSUE TITLE
ÖNB: Datumsangabe ergänzen

### ISSUE THREAD

**Issue by jenniferward** [rism-international/tasks#1026]
In 18.382 Titeln aus dem ÖNB-Import steht `[s.d.]` in 260$c, jedoch gibt es eine Datumsangabe im originalen 300$a (später verschoben nach 500$a).
Beispiel:
https://muscat.rism.info/admin/sources/600114090
```
=260 ##$c[s.d.]
=500 ##$aPartitur, Handschrift (19. Jh.), 262 Bl.
```
Wir können 260$c mit `[1800-1899]` ergänzen.

Bitte in den angehängten Titeln die Datumsangabe auf dieser Weise ergänzen. Die neuen Angaben befinden sich in der Spalte mit der Überschrift 260$c-neu. Voraussetzung: 260$c=`[s.d.]`. Falls nicht (weil inzwischen überarbeitet), dann überspringen.

[Datumsangaben-import.xlsx](https://github.com/rism-international/tasks/files/15191534/Datumsangaben-import.xlsx)

**Comment by HirschSt** [comment]
Ist auf beta umgesetzt, bitte dort stichprobenartig prüfen.

**Comment by jenniferward** [comment]
Danke, sieht gut aus.

**Comment by HirschSt** [comment]
Ist jetzt in Produktion umgesetzt.
