### ISSUE TITLE
Falsche Templates: Materialangabe ändern

### ISSUE THREAD

**Issue by jenniferward** [rism-international/tasks#1027]
In dieser Liste https://docs.google.com/spreadsheets/d/10TYD3oLD94fASaaaguIxcEpDDb-lc9LT94LhgYTmHVk/edit#gid=0 handelt es sich um 749 Handschriften mit mehren Materialgruppen, wo die erste Gruppe eine Handschrift in 593 gekennzeichnet ist ist, und eine weitere Gruppe als `Print` gekennzeichnet ist (Nur `Print`). 

Bei diesen Titeln wo 593=`Print`, bitte in `Additional printed material` ändern.

Beispiel:
https://muscat.rism.info/admin/sources/605201751?view=MARC21
`=593 ##$aManuscript copy$bNotated music$801`
`=593 ##$aPrint$bNotated music$802`

Die zweite Gruppe wird geändert in: `$aAdditional printed material`

**Comment by HirschSt** [comment]
Bitte auf beta kurz prüfen, ob die Umsetzung ok ist.

**Comment by jenniferward** [comment]
Danke, das sieht gut aus, kann umgesetzt werden.

Könntest du bitte die "Aktion" ändern in `Batch change source type`, damit wir später die Änderung auf dem ersten Blick erkennen können?

![image](https://github.com/rism-international/tasks/assets/18663291/eeb38a62-635f-4281-85d6-855e94acccc4)


Notizen für mich:
Beispiele
Print in 3. Gruppe: https://beta.rism.info/admin/sources/600092505/edit
Keine Änderung (weil inzwischen überarbeitet): https://beta.rism.info/admin/sources/605201371/edit
COL mit Print in 2. Gruppe: https://beta.rism.info/admin/sources/1001165855
COL mit Print in 3. Gruppe: https://beta.rism.info/admin/sources/650013967
COL mit Print in 3. und 5. Gruppe https://beta.rism.info/admin/sources/250014947
MS in COL: https://beta.rism.info/admin/sources/280000203
MS in COL Gruppe 3-5: https://beta.rism.info/admin/sources/280000550/edit
Mehrmals Print: https://beta.rism.info/admin/sources/600090984/edit 
MS allein, 2 Gruppen: https://beta.rism.info/admin/sources/653003362/edit

**Comment by HirschSt** [comment]
Ist jetzt auf production umgesetzt.
