### ISSUE TITLE
300$a: "1 parts" in "1 part" ändern

### ISSUE THREAD

**Issue by jenniferward** [rism-international/tasks#1028]
Durch eine Pikado-Migration ist 150.000x "1 parts" im Feld 300$a entstanden, was niemals grammatisch korrekt ist:
https://rism.online/search?mode=sources&fq=format-extent%3A1%20parts&page=1&rows=20
![image](https://github.com/user-attachments/assets/6b093a5e-f3bc-4205-8cf9-5380e7109667)

Ich finde keine Beispiele, wo das korrekt sein kann, oder wo etwas anderes gemeint ist.

Bitte im Feld 300$a `1 parts` in `1 part` ändern.

Zufällige Beispiele:
https://muscat.rism.info/admin/sources/454002481 (HS COL, Gruppe 4)
https://muscat.rism.info/admin/sources/104490 (HS, 1 Gruppe)
https://muscat.rism.info/admin/sources/452515681 (Druck EE, 1 Gruppe) 
https://muscat.rism.info/admin/sources/452515678 (Druck COL, 1 Gruppe)

**Comment by HirschSt** [comment]
Ist auf beta umgesetzt, bitte stichprobenweise kurz prüfen, s. auch https://raw.githubusercontent.com/rism-international/muscat-maintenance/master/log/20240730_fix_parts.log

done with https://github.com/rism-international/muscat-maintenance/commit/c121a1f14cf62d7ce83f8fd659d6bfca2ebb5b28

**Comment by jenniferward** [comment]
Das Skript hat 151.594 Titel gefunden aber laut RISM Online sind es 150.808 Titel. Ich gehe davon aus, dass auch einige unveröffentlichte Titel auch geändert worden sind (was ok ist)? 

Stichprobenweise sieht es gut aus, auch meine Probetitel sind in Ordnung. Danke!

Ich habe mit einer höheren Anzahl an Drucken aus A/I oder B/I gerechnet aber ich finde keine konkreten Beispiele, die übersehen worden sind. Hier sehe ich nur 3 A- bzw. B-Nummern und auch in RISM Online finde ich nur die 3. 

Nun sehe ich Titel wie z.B. https://beta.rism.info/admin/sources/1001193499, wo eine Seitenangabe nach `1 parts` steht: 
`=300 ##$a1 parts: 4 p. $801`
Wir können aber später gucken, ob das ein systematisches Problem ist, oder vielleicht nur ein Flüchtigkeitsfehler.

**Comment by HirschSt** [comment]
Ist in production umgesetzt. Wenn noch Sachen zu erledigen sind, bitte ein neues Ticket schreiben
