### ISSUE TITLE
Signaturen für D-Rtt ergänzen (852 $c)

### ISSUE THREAD

**Issue by MFalletta** [rism-international/tasks#1032]
Ich habe eine Liste aus D-Rtt mit Signaturen für die Druckexemplare erhalten. 
Bitte 852 $c in den entsprechenden holdings ergänzen.
[D-Rtt Signaturnachträge.xlsx](https://github.com/user-attachments/files/17457429/D-Rtt.Signaturnachtrage.xlsx)

**Comment by HirschSt** [comment]
Vielen Dank. Dazu zwei kurze Fragen:

1. Was ist mit mehreren Holding in demselben Druck? In der Regel sind die Signaturen zwar gleich, aber es gibt auch Abweichungen (z.B. in 990000377, 990036195). Wie soll ich da vorgehen?

2. Bei Signatur Pleyel 21 fehlt (bei mir Jedenfalls) die ID.

**Comment by MFalletta** [comment]
Soweit ich sehen konnte, bleiben eine handvoll fragliche Datensätze übrig, zu denen evtl. Rückfragen in Regensburg notwendig sind (siehe 2.). 
Bitte berücksichtige daher nur die eindeutigen Fälle. Könntest du mir die Problemfälle auswerfen? Dann erledige ich diese händisch.
Danke!

**Comment by HirschSt** [comment]
Bitte kurz stichprobenartig auf beta prüfen. Die Problemfälle sind in https://github.com/rism-international/muscat-maintenance/blob/master/DRtt-exclude.csv

**Comment by MFalletta** [comment]
Das sieht gut aus!

Danke - auch für die kleine Liste.

**Comment by HirschSt** [comment]
Ist in production umgesetzt
