### ISSUE TITLE
Holdings bereinigen aus GB-Cfm

### ISSUE THREAD

**Issue by HirschSt** [rism-international/tasks#1036]
- [x] Dubletten löschen
- [x] 001, 005, 008, leader löschen
- [x] erstes 004 wird zu 001
- [x] restliche 004 bleiben stehen
- [x] 852$a ergänzen
- [x] 852$h wird zu 852$c
- [x] 852$2 löschen

**Comment by jenniferward** [comment]
Weitere Felder sind vorhanden. Ich habe noch nicht geguckt, wie wichtig sie sind:

| Field | In Records | Total |
|-------|------------|-------|
| 000   | 1463       | 1463  |
| 001   | 1463       | 1463  |
| 004   | 1463       | 7683  |
| 005   | 1355       | 1355  |
| 008   | 1463       | 1463  |
| 014   | 617        | 6652  |
| $a    | 6652       |       |
| 541   | 2          | 2     |
| $c    | 2          |       |
| $a    | 2          |       |
| 852   | 1463       | 1463  |
| $2    | 1355       |       |
| $b    | 1463       |       |
| $z    | 13         |       |
| $h    | 1463       |       |
| $k    | 2          |       |
| $x    | 5          |       |
| 916   | 3          | 3     |
| $a    | 3          |       |

**Comment by HirschSt** [comment]
done, see https://raw.githubusercontent.com/rism-international/import/refs/heads/master/data/Fitz/holdings.xml

**Comment by jenniferward** [comment]
Bei den Holdings muss auch 852$b berücksichtigt werden. 

FWM-MSSBB (1347x) muss umgesetzt werden in: `Dept. of Manuscripts & Printed Book`
FWM (109x) muss umgesetzt werden in: `Reference Collection`

852$z, k, x kann ich nach dem Import händisch ergänzen.

**Comment by HirschSt** [comment]
BITTE keine geschlossenen Issues neu aufmachen, sondern NEUE anlegen. DANKE!
