### ISSUE TITLE
Weitere Anpassungen Holdings aus GB-Cfm

### ISSUE THREAD

**Issue by jenniferward** [rism-international/tasks#1040]
- [x] 852$b berücksichtigen
- [x] 852$b FWM-MSSBB ändern zu: Dept. of Manuscripts & Printed Book
- [x] 852$b FWM ändern zu: Reference Collection

Wir kommen von hier: https://github.com/rism-international/tasks/issues/1036

Bei den Holdings muss auch 852$b berücksichtigt werden. 

FWM-MSSBB (1347x) muss umgesetzt werden in: `Dept. of Manuscripts & Printed Book`
FWM (109x) muss umgesetzt werden in: `Reference Collection`

852$z, k, x kann ich nach dem Import händisch ergänzen.

**Comment by HirschSt** [comment]
> FWM-MSSBB` (1347x) muss umgesetzt werden in: Dept. of Manuscripts & Printed Book

In welchem Feld?

> FWM (109x) muss umgesetzt werden in: Reference Collection

In welchem Feld?

**Comment by jenniferward** [comment]
852$b

 852$b
