### ISSUE TITLE
Check if Github API is available for Rails (ActiveAdmin) as show page

### ISSUE THREAD

**Issue by HirschSt** [rism-international/tasks#111]
see https://github.com/piotrmurach/github

**Comment by bjoernkessler** [comment]
The repository is cloned to zeus:$HOME/projects/github-api. In the same directory there is a Dockerfile specifying a ruby-container. This container builds nicely e.g. like this:
 
´´´bash
docker build -t github .
´´´
Unfortunately I could not figure out how to install the dependencies. I tried both gem and apt but they all failed at a certain point.

**Comment by bjoernkessler** [comment]
concerned with #199
