### ISSUE TITLE
Disable postfix/dovecot from restart with mailserver host machine

### ISSUE THREAD

**Issue by HirschSt** [rism-international/tasks#176]

**Comment by bjoernkessler** [comment]
## Commands:
### Postfix:

> sudo update-rc.d postfix disable

### Dovecot

Commenting out the following line in /etc/init/dovecot.conf
#start on runlevel [2345] 

### Reference:
https://askubuntu.com/questions/19320/how-to-enable-or-disable-services
-> Disable services (jobs) in upstart
