### ISSUE TITLE
Add backup strategy

### ISSUE THREAD

**Issue by HirschSt** [rism-international/tasks#196]

**Comment by bjoernkessler** [comment]
First of all the git repository for the docker architecture has to be seperated from the productive website. This is done using gits submodule feature.

**Comment by bjoernkessler** [comment]
git submodule could not be proven to be appropriate here. As we want the ide user dev to be able to control the websites git repository, it has to be completely independent from the docker git repository, which is controlled by the admin.

**Comment by bjoernkessler** [comment]
So from here we need 2 cron jobs: 
- [ ] daily dump of the database
- [ ] weekly commit to the website git

The docker git is only committed on change.

**Comment by bjoernkessler** [comment]
We still need a cronjob for the database and a cleanup script for both, similar to what is done with MAILDIR
