### ISSUE TITLE
Investigating on server shutdown on mail.rism.info ⑭

### ISSUE THREAD

**Issue by bjoernkessler** [rism-international/tasks#219]
- [ ] Find the reason for sudden server shutdowns
- [x] Make mailserver start automatically at boottime
- [x] Make sure that ssh connection is possible after reboot

**Comment by HirschSt** [comment]
#252

**Comment by HirschSt** [comment]
Broadcast message from root@rism-secure
	(unknown) at 6:34 ...

The system is going down for reboot NOW!
Control-Alt-Delete pressed

**Comment by HirschSt** [comment]
ssh-keygen -f "/home/xxx/.ssh/known_hosts" -R xxx.rism.info

**Comment by bjoernkessler** [comment]
Server-shutdown has not been happening since the move to the new server.
