### ISSUE TITLE
Whiteboard auswählen

### ISSUE THREAD

**Issue by bjoernkessler** [rism-international/tasks#22]
https://www.whiteboards-outlet.de/whiteboard/mobiles-whiteboard/mobilboard-revolve.html

**Comment by HirschSt** [comment]
wo ist der unterschied zu https://www.amazon.de/VIZ-PRO-Whiteboard-Doppelseitige-Whiteboard-magnetisch/dp/B01KYY7HN4/ref=sr_1_33?ie=UTF8&qid=1500371321&sr=8-33&keywords=whiteboard
