### ISSUE TITLE
Calling "contact" raises error

### ISSUE THREAD

**Issue by HirschSt** [rism-international/tasks#231]
at http://apollo.rism.info/service/contact-us.html

Warning: Uncaught exception 'TYPO3\CMS\Core\Error\Exception' with message 'PHP Warning: require_once(/var/www/html/typo3/sysext/cms/tslib/class.tslib_pibase.php): failed to open stream: No such file or directory in /var/www/html/typo3conf/ext/powermail/pi1/class.tx_powermail_pi1.php line 25' in /var/www/html/typo3_src-6.2.31/typo3/sysext/core/Classes/Error/ErrorHandler.php:101 Stack trace: #0 /var/www/html/typo3conf/ext/powermail/pi1/class.tx_powermail_pi1.php(25): TYPO3\CMS\Core\Error\ErrorHandler->handleError(2, 'require_once(/v...', '/var/www/html/t...', 25, Array) #1 /var/www/html/typo3conf/ext/powermail/pi1/class.tx_powermail_pi1.php(25): require_once() #2 /var/www/html/typo3_src-6.2.31/typo3/sysext/frontend/Classes/Controller/TypoScriptFrontendController.php(4477): include_once('/var/www/html/t...') #3 /var/www/html/typo3_src-6.2.31/typo3/sysext/frontend/Classes/Controller/TypoScriptFrontendController.php(3697): TYPO3\CMS\Frontend\Controller\TypoScriptFrontendController->includeLibraries(Array) #4 /var/www/html/ in /var/www/html/typo3_src-6.2.31/typo3/sysext/core/Classes/Error/ErrorHandler.php on line 101

**Comment by bjoernkessler** [comment]
By removing the deprecated require_once commands we could change the error to this:

Fatal error: Call to undefined function mysql_query() in /var/www/html/typo3conf/ext/powermail/pi1/class.tx_powermail_html.php on line 850

**Comment by bjoernkessler** [comment]
might be concerned with #41

**Comment by bjoernkessler** [comment]
solved without touching #41
