### ISSUE TITLE
Siglum search: make the contents of the country dropdown menu suitable for the results (KW45)

### ISSUE THREAD

**Issue by bjoernkessler** [rism-international/tasks#232]
At the moment a search for "Belgium" in "Country" doesn't bring any results even though Belgium is part of the dropdown menu that occures when you choose "Country" and type "B". For all libraries in Belgium you have to enter the country-code. So either the dropdown shows the country-code and the country names or the search parses country names to country-code.

**Comment by HirschSt** [comment]
contry codes at https://github.com/rism-ch/muscat/blob/6483f82755f52fe3639bb3a00ee2cd575694d895/config/editor_profiles/default/configurations/InstitutionLabels.yml#L733
