### ISSUE TITLE
Search for mixed material in muscat ⑮

### ISSUE THREAD

**Issue by HirschSt** [rism-international/tasks#246]
Drucke und Handschriften zuammengebunden
593 Materialtyp verdoppelt
sru-Schnittstelle
hs + print !!!

**Comment by bjoernkessler** [comment]
Script finding mixed material and the result of the test run of the script on muscat-gamma@zeus can be found here:

https://github.com/rism-international/muscat-maintenance/commit/95122f835084fd925f69abc9286bef58a9a5b591
