### ISSUE TITLE
Test mensural notation for BSB ⑬

### ISSUE THREAD

**Issue by HirschSt** [rism-international/tasks#248]
Bögen werden nicht angezeigt (Noten im PAE-Code mit "+" verbunden): Haltebögen (gleiche Notenhöhe) sind zwar von RISM nicht vorgesehen, Bindebögen schon, beides wird aber verwendet und wäre durchaus sinnvoll;
und
- [x] Metren werden nicht angezeigt: z.B. "o", "c", "c/"
RISM ID: 456051799 (oder 456050576)
PAE Code:  Schlüssel: C+3, Akzidentien: bB, Metrum: o, Musikincipit: 1C+1.F2E1C+,A2-'C1,G2AFAB'C+2.,B2A0'C
https://opac.rism.info/search?id=456051799
https://opac.rism.info/search?id=456050576

- [ ] Fermaten "(...)" werden nicht angezeigt:
RISM ID: 456051455
Incipit 1.1.1
PAE Code:  Schlüssel: C+1, , , Musikincipit: 0A2''C'G2.A4B2''CD1(C)
https://opac.rism.info/search?id=456051455

- [ ] Taktwechsel ("@ ")werden nicht angezeigt:
RISM ID: 456052623
Incipit 1.1.3
PAE Code  Schlüssel: C+3, , Metrum: c/, Musikincipit: 1-9C,1A+BB2-2B@3 '2.C4D2E
https://opac.rism.info/search?id=456052623
Vielleicht betrifft dies auch Schlüssel- und Vorzeichenwechsel, ich konnten leider ad hoc keine passende Beispiele finden:
Die PAE-Kodierung wäre hierbei folgende:
Schlüsselwechsel: %+Schlüssel+Spatium (z.B. "%C+1 ")
Vorzeichenwechsel: $+Schlüssel+Spatium (z.B. "$xF_")

**Comment by HirschSt** [comment]
see also https://github.com/rism-ch/verovio/issues/805

**Comment by rettinghaus** [comment]
Im Gegenteil:
Bindebögen sind in *Plaine & Easie* nicht vorgesehen, nur Haltebögen (auch wenn die Bezeichnung missverständlich bzw. falsch ist) 
>slur (follows immediately the note: only for same-pitch notes)

www.iaml.info/plaine-easie-code
