### ISSUE TITLE
Check if Finanzmanager Deluxe 2018 (Lexware) is available for Linux

### ISSUE THREAD

**Issue by HirschSt** [rism-international/tasks#26]

**Comment by bjoernkessler** [comment]
There are some Lexware products that have been tested on wine:

https://appdb.winehq.org/objectManager.php?sClass=category&iId=63

We'll need the software to try it out.

**Comment by bjoernkessler** [comment]
Unfortunately wine exits both, the installer as the exe files of finanzmanager with an error
