### ISSUE TITLE
Move 597 at end of 245 and move editor field

### ISSUE THREAD

**Issue by HirschSt** [rism-international/tasks#271]

**Comment by HirschSt** [comment]
same as #223

**Comment by KlausKeil** [comment]
Das hat geklappt, wenn das Feld 597 bereits Daten enthielt. Wenn es leer war wurde der Inhalt in 597 belassen. 
Beispiel: 00000991018752 oder 00000990019524

**Comment by HirschSt** [comment]
Wenn 245 nicht existiert, kann ich leider auch nichts anfügen. 
Ich werde nachrecherchieren, wie oft 245 insgesamt nicht belegt ist. In der Regel müsste dann zunächst "[without title]" ergänz werden, dann erst der Feldinhalt von 597.

**Comment by HirschSt** [comment]
Die noch nicht umgestellten Titel müssen mit einem weiteren Skript verschoben werden, s. #419
