### ISSUE TITLE
Installation of PDF-export for users

### ISSUE THREAD

**Issue by HirschSt** [rism-international/tasks#286]
fix issues

**Comment by bjoernkessler** [comment]
Concerned with #313

**Comment by bjoernkessler** [comment]
There is an issue with the 'contains' function in lualatex.xsl (line 137- 146) and/or the entry-link in preprocessing.xsl (line 435). The 'contains'-item in the catalogue-pdf only shows commas, not the reference number of the corresponding entries.

**Comment by BaMikusi** [comment]
I think this functionality was cleaned up in the spring of 2021
https://rism.info/new_publications/2021/05/17/creating-your-own-catalog-printout-rism-database.html
and the issue can now be closed?

**Comment by rism-international** [comment]
Yes, this can be closed now, thanks
