### ISSUE TITLE
test muscat docker api

### ISSUE THREAD

**Issue by bjoernkessler** [rism-international/tasks#315]
- [x] remove instance on zeus 
- [x] create instance with tag 4
- [ ] update to 5

https://github.com/rism-international/muscat_docker

**Comment by bjoernkessler** [comment]
https://github.com/rism-international/muscat_docker

**Comment by bjoernkessler** [comment]
rismit/muscat_app

**Comment by bjoernkessler** [comment]
Where does the Dockerfile of rismit/muscat_app live? It would be interesting to see it. Especially for updates it would be inevitable.

**Comment by HirschSt** [comment]
- [ ] install mysql-server without interactive questions
- [ ] execute init.sql from dockerfile as root
- [ ] push image to dockerhub

**Comment by bjoernkessler** [comment]
- [ ] try ubuntu 18.04
