### ISSUE TITLE
Write Rspec to check map in institution

### ISSUE THREAD

**Issue by HirschSt** [rism-international/tasks#319]
eg D-Mbs
especially if openstreetmap is reachable

**Comment by bjoernkessler** [comment]
This issue has been closed with the following muscat commit:

https://github.com/rism-ch/muscat/commit/1b900a9c2ac9e66433163928d7efac281f92410e

Please provide more information, if there is still development needed.

**Comment by bjoernkessler** [comment]
- [ ] Write spec for testing for statuscode 200 from openstreetmap.org
