### ISSUE TITLE
Make muscat sql-dump available for download

### ISSUE THREAD

**Issue by bjoernkessler** [rism-international/tasks#322]
Sql-dump of the muscat database should be available somewhere for development installations for muscat.

**Comment by HirschSt** [comment]
@bjoernkessler  the daily dump is available at http://lab.rism.info/muscat.gz

**Comment by HirschSt** [comment]
@bjoernkessler password encrypted due to security, link: http://lab.rism.info/muscat.gz.gpg

decryption see https://www.if-not-true-then-false.com/2010/linux-encrypt-files-decrypt-files-gpg-interactive-non-interactive/
