### ISSUE TITLE
Lokale Nummer in holding record

### ISSUE THREAD

**Issue by KlausKeil** [rism-international/tasks#327]
Lokale Nummer in holding record gebraucht:
Wenn man feststellt, dass ein Exemplar eines Druckes als Hs Titel aufgenommen wurde, kann man, wenn der Druck mit einem anderen Fundort eingegeben ist, im Prinzip den Fundort und die dazugehörigen Angaben an den neuen Titel anhängen und den alten löschen. Im Holding rec. gibt es aber keine Lokale Nummer, in die man die bisherige RISM-ID eingeben könnte. Muss eingerichtet werden, damit der Eintrag unter der alten Nr. zu finden ist. 
Beispiel: 654000172 wird zu Exemplareintrag in 1001042570

**Comment by KlausKeil** [comment]
Kann scheinbar kein Label setzen?

**Comment by HirschSt** [comment]
Don with https://github.com/rism-ch/muscat/commit/428d1f20c239dd9aee033c6d16c7c17a43a44396
