### ISSUE TITLE
Teileinträge bei unterschiedlichen Auflagen mehrfach verlinken?

### ISSUE THREAD

**Issue by KlausKeil** [rism-international/tasks#328]
Bei unterschiedlichen Ausgaben eines Sammeldruckes sind die Werke oft dieselben. Sollte man dann nicht besser immer auf den gleichen Teileintrag verlinken statt für die andere Ausgabe alle Teileinträge zu kopieren? 
Beispiel: Sammeldrucke 1001046709 und 990071923

**Comment by HirschSt** [comment]
Wäre lösbar bei klarer Verteilung der Objektprädikate, z.B.: 
- Komponist gehört zur Werkebene (W)
- Verlag zur Expression (E)
- Plattennummer zur Manifestationsebene (M)

Ein Teileintrag (E) könnte also problemlos alle Angaben von W übernehmen, und nur diejenigen Angaben enthalten, die für diese Ebene wichtig ist

Ebenso könnten unterschiedliche Ausgaben (M) auf einen "urspünglichen" Teileintrag des Erstdrucks verlinken, hätten also z.B. nur eine unterschiedliche Plattennummer.

Bisher fehlt aber die klare Zuordnung der Marcfelder auf die RDA Entitäten, deswegen gibt es aktuell zahlreiche Verdoppelungen. Das wird sich mit der Werkebene leider wiederholen.

**Comment by HirschSt** [comment]
Sind die Teileinträge denn immer völlig identisch?

**Comment by KlausKeil** [comment]
Nur in Fällen wie diesen, wo der neue Verleger sogar die Platten des vorigen verwenden durfte. (Pl.Nrn sind identisch)

**Comment by jenniferward** [comment]
>  Ich müsste jetzt also die drei Teileinträge kopieren und im Feld 773 die Verknüpfung ändern. 

Das ist und bleibt die Praxis. Ich ergänze diese Praxis in die Richtlinien und schließe das Ticket.
