### ISSUE TITLE
Frage zu Teileintrag

### ISSUE THREAD

**Issue by KlausKeil** [rism-international/tasks#329]
Kann der Teileintrag nicht nur aus einem Link zum betreffenden Werk in der WE bestehen?

**Comment by HirschSt** [comment]
Ich hoffe ich habe die Frage richtig verstanden: Der Teileintrag betrifft ja nur die Exemplarebene und enthält z.b. Beschreibungen zum Material, Abweichungen im Incipit etc.; andere Elemente könnten in die Werkebene transferiert werden, wobei ich diese aber nicht zu sehr überladen würde (viele Informationen sind ja über den Viaf-Eintrag auch schon vorhanden).

**Comment by HirschSt** [comment]
Danke, ich denke, die Problemstellung ist klar geworden und deckt sich in etwa mit #328

**Comment by HirschSt** [comment]
Ja, im großen und ganzen könnte die gesamte Beschreibung, die sich auf das Werk bezieht, durch den Link auf das Werk ersetzt werden. Man müsste nur bei dem Felderschema klar definieren, welche Felder sich wirklich auf die Manifestation beziehen (z.B. Seitenangaben) und welche auf das Exemplar (z.b. Handschriftliche Zusätze). Alles andere könnte man durch Verlinkungen referenzieren.
