### ISSUE TITLE
Werkebene / Anzeige 

### ISSUE THREAD

**Issue by KlausKeil** [rism-international/tasks#336]
Bei der Anzeige und beim Auswahlfeld  sollte auch das Werkverzeichnis angezeigt werden. 
Manche Werke lassen sich nur durch das Werkverzeichnis von anderen mit gleichem Titel unterscheiden (z.B. Rondo brillante hat Hummel viele geschrieben. Die Karten und das WV geben oft keine Tonart an).

**Comment by KlausKeil** [comment]
Opus sollte auch dabei sein: 
Reihenfolge: Komponist, Titel, Tonart, Opus, Werkverzeichnis

**Comment by HirschSt** [comment]
done with https://github.com/rism-ch/muscat/commit/367f8c7c26c3a7b3e391a391f1e0e3679d0cf628
