### ISSUE TITLE
Auswahlliste Tonart in WE

### ISSUE THREAD

**Issue by KlausKeil** [rism-international/tasks#337]
Im Feld Tonart gibt keine Auswahlliste vor

**Comment by HirschSt** [comment]
Das ist insofern heikel, da alle importierten Werktitel (z.B. Library of Congress, BNF etc) anderen Konventionen bei der Tonart (z.B. 'C major') folgen. Man müßte also nach jedem Import die Tonart nochmal nachjustieren, deswegen ist ein Freitextfeld zunächst sinnvoller.
