### ISSUE TITLE
Check current state of canto project

### ISSUE THREAD

**Issue by HirschSt** [rism-international/tasks#348]

**Comment by HirschSt** [comment]
mail v. 12.2.2019:
Der Text ist kurz und klar, einschl. der Einladung an die Benutzer, weitere Einträge zu lancieren. Ich würde vorschlagen, dass die an dieser Stelle einzutragende Adresse als eine Art Sammelbecken für die entsprechenden Anregungen von Benutzerseite dient, die dann an mich oder an die für die Aktualisierung verantwortliche Person regelmässig zur Umsetzung weitergeleitet werden. 

Die beiden Vorschläge für Bildmaterialien halte ich aus folgenden Gründen für passend: Bei Option 1 handelt es sich um eine Komposition von G. J. Vogler, die in seinem eigenen Lehrwerk erscheint und dabei mit den beim Vortrag vorzunehmenden Veränderungen wiedergegeben wird. Für Option 2 gilt ähnliches, allerdings ist die Komposition nun ein Werk von Rossini, das vom Autor des Lehrbuches mit einer möglichen vorzutragenden Melodiegestalt versehen wird. In beiden Fällen handelt es sich um Repertoire der Zeit um 1800, das nach heutigem Gusto keinen derart weit reichenden aufführungspraktischen Veränderungen unterworfen wird. Damit ist quasi unterschwellig auf die besondere Sinnhaftigkeit einer konkreten Auseinandersetzung mit den in RISM canto gesammelten Materialien hingewiesen. 
Vielleicht lassen sich ja sogar Bildelelemente aus beiden Exempeln anbringen?

**Comment by bjoernkessler** [comment]
- [ ] mehrsprachiger Einführungstext auf der Eingangseite
- [ ] Bild einbinden
- [ ] Footer um Hinweis auf Projekt erweitern
- [ ] Einstiegsseite soll Leitseite sein

**Comment by HirschSt** [comment]
closed with followop
