### ISSUE TITLE
falscher Komponist bei Übernahme aus Viaf 

### ISSUE THREAD

**Issue by KlausKeil** [rism-international/tasks#357]
Bei der Übernahme eines Werktitels aus VIAF wird für den Komponist anscheinend nur das Lebensdatum übergeben. So setzt Muscat beim Abspeichern anstelle von Hummel Johann Nepomuk den Namen Gustaf IV. Adolf, konung av Sverige ein, weil dieser Gustav die gleichen Lebensdaten wie Hummel hat.

**Comment by HirschSt** [comment]
Bitte Beispieltitel oder Suchbegriff nennen, damit ich das überprüfen kann.

**Comment by KlausKeil** [comment]
Beipieltitel geht nicht. 
Einen neuen Eintrag öffnen
Komponist: Hummel, Johann Nepomuk
Werktitel = Oberons Zauberhorn
(soweit vorbereitet) 
ViafSuche ergibt ein Ergebnis. - Übernehmen. 
In der Ansetzungsform wird nur das Lebensdatum des Komponisten übernommen. 
Beim Abspeichern wird als Komponist dieser Gustav eingesetzt.

**Comment by HirschSt** [comment]
Danke, jetzt ist der Groschen gefallen ... ich habe diesen Fehler behoben, bitte nochmal auf beta.rism.info testen

done with https://github.com/rism-ch/muscat/commit/aada4f05f2e0a0a00f9bf9614e64302e6489867e

**Comment by KlausKeil** [comment]
Beim ersten Komponist in 400 klappt es aber dei den Wiederholungen von 400 wir wieder Gustav eingesetzt. 
Beipiel auf Beta: Work 55 (Hummel Dances op. 44)

**Comment by HirschSt** [comment]
Danke nochmals! Jetzt sollte auch das richtig sein, siehe auf beta

done with https://github.com/rism-ch/muscat/commit/c8446d9b009ed1bdf97ae72e773f6835c1d702e3
