### ISSUE TITLE
Test muscat 5

### ISSUE THREAD

**Issue by KlausKeil** [rism-international/tasks#363]
Köperschaft SK-BRšk
In der Liste steht Quellen = 0
In der Titelanzeige ist eine Quelle genannt. Es ist ein Druck mit einem Holding record in SK-BRšk. 
Hier müsste Quellen auf 1 (oder mehr) stehen.

**Comment by HirschSt** [comment]
Tut es auf muscat-test:
![image](https://user-images.githubusercontent.com/6461776/47794365-9c8d5480-dd20-11e8-97a4-4af1ce5eb064.png)
