### ISSUE TITLE
Werkebene: Titel nicht zu finden obwohl in VIAF

### ISSUE THREAD

**Issue by KlausKeil** [rism-international/tasks#365]
Bestimmte Werktitel, die in VIAF vorhanden sind, lassen sich über die VIAF Suche in Muscat nicht finden. (Es scheint sich um solche zu handeln, die nur einen Eintrag aus der Bibliotheque de France haben.)
Beispiel: 
VIAF Suche "Hummel, Johann Nepomuk 43" Es kommt keine no result-Anzeige. Bei allen anderen Varianten z.B.  "Hummel, Johann Nepomuk Op. 43",  "Hummel, Johann Nepomuk Johann von Finnland" Meldung no result.  
Der Titel ist aber in VIAF: 4709148122900795200000 

VIAF Suche "Hummel, Johann Nepomuk"
bringt in Muscat nur 9 Einträge. 
VIAF hat aber 471 Einträge

**Comment by HirschSt** [comment]
Danke. Die Suche bei der viaf geht über 
`http://viaf.org/viaf/search?query=local.uniformTitleWorks=Hummel,%20Johann%20Nepomuk%2043&sortKeys=holdingscount&httpAccept=application/json`

Warum hier in der Ergebnisliste bei Muscat der Titel nicht auftaucht, muss ich noch recherchieren.

**Comment by HirschSt** [comment]
Für die BNF Einträge gibt es noch keinen Konverter, deswegen erscheinen nur Einträge aus DNB und LC; werde in Kürze einen Konverter schreiben.

**Comment by HirschSt** [comment]
Ich habe den BNF converter ergänzt, so dass jetzt auch Ergebnisse von "Hummel, Johann Nepomuk 43" von der BNF übernommen werden können. 

Die Suche bei Muscat ist auf die ersten 10 Treffer beschränkt, sonst würde die Übernahme in Muscat zu lange dauern. Insofern sollte "Hummel, Johann Nepomuk" immer mit einem entsprechenden Werkidentifikator ergänzt werden.

ich könnte die Gesamtanzahl der Treffer mit der Trefferlist zeigen ("10 von 451 Einträgen in VIAF"), aber das wäre was für Muscat > 5.2
