### ISSUE TITLE
Dropdownmenu in 856 $x

### ISSUE THREAD

**Issue by KlausKeil** [rism-international/tasks#372]
Sollte im holding record das gleiche sein wie im bibliographic record. 
Im holding record ist nur die Angabe IIIF möglich, nicht Notendigitalisat und Sonstige.

**Comment by HirschSt** [comment]
Ist in muscat-test korrekt. Bitte prüfen und schliessen.

**Comment by KlausKeil** [comment]
getestet. ok.
