### ISSUE TITLE
Musikincipit Darstellung falsch 

### ISSUE THREAD

**Issue by KlausKeil** [rism-international/tasks#374]
Diese Incipit führt zur falschen Darstellung der Triole, obwohl prinzipiell richtig codiert (wenn auch umständlich).: G-2 - 2/4 - 8,B/4(8{GB'E};3)({FD,B})/8'G-8.-6,B/4({8'EGB};3)({BBB})/8B-8.-6B/4({8CAC};3)({bCAC})/8,B-8.-6'A/
Die jeweils 2ten Triolen müssen 8tel sein, nicht 32tel. ... …};3) bedeutet nur, dass auf den Viertelwert (4 vor runder Klammer) 3 Noten kommen. 
Titel: 455002955. Incipit 1.3.1

**Comment by HirschSt** [comment]
this is verovio related, see https://github.com/rism-ch/verovio/issues/966#issue-383426975

**Comment by HirschSt** [comment]
@KlausKeil bitte nach dem nächsten Release erneut testen
