### ISSUE TITLE
Install oracle 10g with Kallisto db on linux

### ISSUE THREAD

**Issue by HirschSt** [rism-international/tasks#384]
Kallisto lief unter oracle (bei bsb). Datendump läuft auf repro. Version 10g! (Useredition)
Docker? zeus

**Comment by bjoernkessler** [comment]
Oracle Database 10.2 and 11.1 are no longer available for download. The software is available as a media or FTP request for those customers who own a valid Oracle Database product license for any edition. (https://www.oracle.com/technetwork/database/enterprise-edition/downloads/index.html)
