### ISSUE TITLE
Research incipits with collection template

### ISSUE THREAD

**Issue by HirschSt** [rism-international/tasks#385]
- [x] how many?
- [x] is it possible to change the template?

**Comment by HirschSt** [comment]
maybe adding to sru

**Comment by HirschSt** [comment]
list at https://github.com/rism-international/muscat-maintenance/blob/master/20181115-incipits_in_collections.yml

**Comment by lpugin** [comment]
Do any of these have children records? If not then changing the template would probably be all we need.

**Comment by HirschSt** [comment]
without child_sources: 367
with child_sources: 703

**Comment by HirschSt** [comment]
Probably the cleanest way:
I. if there **are** children
1. make a basic colletion entry
2. transfer the bad record to an individual entry
3. connect all children to the basic collection

II. if **not**:
1. change the template to individual source

**Comment by HirschSt** [comment]
probably it's cleaner to solve this issue with the template change mechanism in https://github.com/rism-ch/muscat/issues/237

**Comment by HirschSt** [comment]
see also https://github.com/rism-international/tasks/issues/349
