### ISSUE TITLE
Move 597 to new created 245

### ISSUE THREAD

**Issue by HirschSt** [rism-international/tasks#419]
new maintenance, see also #271 
- add [without title] if 245 is empty and there is no previous print
- add title of previous print, remove existing [impressum] and then add new text from 597 [...]

**Comment by KlausKeil** [comment]
[without title] wäre nicht richtig, da es sich meist um Folgedrucke handeln wird und eigentlich müsste der Titel aus dem Erstdruck genommen werden. Daran dann [597]

**Comment by HirschSt** [comment]
Danke, das ist natürlich auch wieder richtig...

**Comment by HirschSt** [comment]
Titel aus dem Erstdruck so wie er ist oder in eckigen Klammern?

**Comment by KlausKeil** [comment]
ja, so wie er ist. Die Titel in A/1 sind alle nicht original.

**Comment by HirschSt** [comment]
Ok, zusammengefasst also:

I. Drucke
1a. Wenn kein 245 (dipl. Titel) vorhanden ist, aber ein Erstdruck mit Titel -> in 245 dieser Erstdrucktitel, aber ohne dessen Impressum (also ohne die dortige Ergänzung in eckige Klammern)
1b. Wenn kein 245 vorhanden ist, und kein Erstdruck -> in 245 "[without title]"
 2. Anschließend wird der Titel um die Angabe in 597 in eckigen Klammern ergänzt, falls 597 vorhanden
 3. 597 wird dann gelöscht

II. Andere Quellen
1 Ergänze 245 als Pflichtfeld mit dem Inhalt "[without title]", wenn 245 nicht vorhanden

Beispiel https://beta.rism.info/admin/sources/990000030

vorher (kein 245 vorhanden):
```xml
<marc:datafield tag="597" ind1="1" ind2="0">
  <marc:subfield code="a">
     Paris, aux adresses ordinaires; Strasbourg, Henry; Lyon, Castaud
  </marc:subfield>
  <marc:subfield code="8">01</marc:subfield>
</marc:datafield>
```
nachher (597 gelöscht):
```xml
<marc:datafield tag="245" ind1="1" ind2="0">
  <marc:subfield code="a">
    Six quatuors concertans pour deux violons, alto et basse ... œuvre 
    1|e|r [Paris, aux adresses ordinaires; Strasbourg, Henry; Lyon, Castaud]
   </marc:subfield>
</marc:datafield>
```
Wäre das so korrekt?

Bitte zusätzlich https://raw.githubusercontent.com/rism-international/muscat-maintenance/master/log/20190626-missing_245.log konsultieren und stichprobenartig durchsehen - hier sind die Änderungen nach diesem Verfahren protokolliert. Aufgrund der Größe des Logfiles werden urls leider nicht aufgelöst.

**Comment by HirschSt** [comment]
Ist das so i.O.?

**Comment by MFalletta** [comment]
Nein, das geht so leider nicht!
siehe https://muscat.rism.info/admin/sources/990037074 
Hier war der dipl. Titel incl. anderem Verleger und Jahr aus dem Ersteintrag übernommen worden und hat zu Verwirrung bei der Bearbeitung geführt (siehe Kommentar von Alexander Staub).

Auch der obengenannte Beispieltitel 
https://muscat.rism.info/admin/sources/990000030
enthält seit dem 10.Okt. den dipl. Titel des Ersteintrags, aber andere Verlagsangaben 

![#419 move 597 vom 2019-10-18 14-37-05](https://user-images.githubusercontent.com/18736235/67095071-593c2800-f1b5-11e9-8801-9e4600183a0c.png)

Wie viele Titel sind davon betroffen? Kann dieser Schritt rückgängig gemacht werden?

**Comment by HirschSt** [comment]
Ok, dann werdet Euch bitte zunächst einig, was gewünscht ist. Vorgabe war, den Titel des Erstdruckes zu übernehmen, wenn kein Titel vorliegt, etc. siehe oben. Wenn hier die neuen Anforderungen vorliegen, neues Ticket schreiben und dann auch testen, bevor das in Produktion geht.

**Comment by HirschSt** [comment]
Vormaliges Logfile unter https://raw.githubusercontent.com/rism-international/muscat-maintenance/991b9eaeadf139da934d10b48367b87f6d1948a2/log/20190626-missing_245.log

**Comment by jenniferward** [comment]
Ich zähle 28.000 Zeilen - also fast alle Ersteinträge, wenn ich mich nicht irre? (29.445 Titel verlinken auf einen "Ersteintrag". 12.000 Titel sind die eigentlichen Ersteinträge. Summe 42.000)
