### ISSUE TITLE
Disable Translation Tool on zeus

### ISSUE THREAD

**Issue by bjoernkessler** [rism-international/tasks#422]

**Comment by bjoernkessler** [comment]
A final state has been pushed to https://github.com/rism-international/opac-translations.
The projects directory has been tarred an compressed and is backed up in /media/x/backup.
Can we remove the directory ~/projects/opac-translations from zeus?

**Comment by HirschSt** [comment]
Would it be possible to make some db dump of the mongodb before?

**Comment by bjoernkessler** [comment]
yes. There are actually two dumps. One is the automatic backup that has been done twice a day. It can be found in opac-translations/output/properties2019011611.tar.gz. And then I made another one by calling the backup-tool by hand. This one lives under opac-translations/db/b2dump.tar.bz2.

**Comment by bjoernkessler** [comment]
The raw data can also be found in the output folder. E.g.:
opac-translations/output/application_es.properties

**Comment by HirschSt** [comment]
opac-translations/db/b2dump.tar.bz2 would be fine, unfortunately now it's empty

**Comment by bjoernkessler** [comment]
The file is now populated with the database dump of its last state.

**Comment by HirschSt** [comment]
Perfect, the folder can be dropped now.
