### ISSUE TITLE
Check OAI-PMH of UdK Berlin

### ISSUE THREAD

**Issue by HirschSt** [rism-international/tasks#423]
hier ein Beispiel einer OAI-Abfrage aus unserem Opus:
https://opus4.kobv.de/opus4-udk/oai?verb=GetRecord&metadataPrefix=oai_dc&identifier=oai:kobv.de-opus4-udk:78

Folgende Optionen stehen zur Verfügung:

* OAI Anfrage mit dem Verb GetRecord (oai_dc)<https://opus4.kobv.de/opus4-udk/oai?verb=GetRecord&metadataPrefix=oai_dc&identifier=oai:kobv.de-opus4-udk:78>
* OAI Anfrage mit dem Verb GetRecord (oai_pp)<https://opus4.kobv.de/opus4-udk/oai?verb=GetRecord&metadataPrefix=oai_pp&identifier=oai:kobv.de-opus4-udk:78>
* OAI Anfrage mit dem Verb GetRecord (EPICUR)<https://opus4.kobv.de/opus4-udk/oai?verb=GetRecord&metadataPrefix=epicur&identifier=oai:kobv.de-opus4-udk:78>
* OAI Anfrage mit dem Verb GetRecord (XMetaDissPlus)<https://opus4.kobv.de/opus4-udk/oai?verb=GetRecord&metadataPrefix=XMetaDissPlus&identifier=oai:kobv.de-opus4-udk:41>
* OAI Anfrage mit dem Verb Identify<https://opus4.kobv.de/opus4-udk/oai?verb=Identify>
* OAI Anfrage mit dem Verb ListIdentifiers<https://opus4.kobv.de/opus4-udk/oai?verb=ListIdentifiers&metadataPrefix=oai_dc>
* OAI Anfrage mit dem Verb ListMetaDataFormats<https://opus4.kobv.de/opus4-udk/oai?verb=ListMetadataFormats>
* OAI Anfrage mit dem Verb ListRecords (mit Anfangsdatum)<https://opus4.kobv.de/opus4-udk/oai?verb=ListRecords&metadataPrefix=oai_dc&from=2006-01-01>
* OAI Anfrage mit dem Verb ListRecords (mit OAI-Set)<https://opus4.kobv.de/opus4-udk/oai?verb=ListRecords&metadataPrefix=oai_dc&set=ddc:62>
* OAI Anfrage mit dem Verb ListSets<https://opus4.kobv.de/opus4-udk/oai?verb=ListSets>
* OAI Anfrage mit dem Verb ListRecords (mit Open-Aire-Set)<https://opus4.kobv.de/opus4-udk/oai?verb=ListRecords&metadataPrefix=oai_dc&set=openaire>
Eine ausführliche Dokumentation findet sich hier:
https://www.kobv.de/wp-content/uploads/2015/03/kobv_opus_dokumentation_version-4.4.4_de.pdf

**Comment by HirschSt** [comment]
url: https://www.kobv.de/?ref=logo

**Comment by HirschSt** [comment]
related to #347

**Comment by HirschSt** [comment]
https://github.com/code4lib/ruby-oai

**Comment by bjoernkessler** [comment]
A ruby class <tt>Udk<\tt> has been created. The 804 Records with the document type "Noten" have been pulled into a xml-file.
