### ISSUE TITLE
Check differences between all *lables.yml in config/editor_profiles

### ISSUE THREAD

**Issue by HirschSt** [rism-international/tasks#486]
now we have 6 files with lables. It would be a great improvement if we can merge them to only one (or two: bibliographic and authority) files. 
Before this we have to check the differences between these files.

**Comment by bjoernkessler** [comment]
In the following file all the Labels have been gathered. Conflicting translations have been marked with the name of the model plus the concerning translation:
[allInOneLabels.txt](https://github.com/rism-international/tasks/files/2991849/allInOneLabels.txt)

The idea behind this file is to get an idea about how many conflicts are in the file and maybe even to serve as a blueprint for a new file or filestructure.

Comments and ideas are wellcome.
