### ISSUE TITLE
Adjust footer for canto project

### ISSUE THREAD

**Issue by rism-international** [rism-international/tasks#487]
follow up for #348

**Comment by bjoernkessler** [comment]
- In Sachen Grafik war ich ganz vage davon ausgegangen, dass die Abbildungen eher als Hintergrunddekor o. dgl. Verwendung finden würden. Wenn sie dagegen textbegleitend platziert werden, wie das aktuell der Fall ist, könnte es sinnvoll sein, wenn sich das oder die Bilder (es könnte evtl. auch eines alleine schon genügen) durch Anklicken vergrössern liessen und dabei dann auch per Bildunterschrift die bibliographischen Angaben zum einzelnen Bild sichtbar würden.

Sollten beide Abbildungen wie gehabt den Text begleiten, schiene mir eine grafische Angleichung wünschenswert, etwa was Bildrand, Helligkeit und Kontrast angeht, aber solche Dinge werden Sie sicher ohnehin noch vornehmen.


- Der Verweis auf den Nationalfonds könnte wie folgt lauten:


RISM canto entstand im Rahmen des vom Schweizerischen Nationalfonds geförderten Forschungsprojekts Kontinuität oder Koinzidenz? Gesangspraxis und Gesangsästhetik 'italienischer' Prägung im Spiegel schriftlicher und akustischer Quellen (1600-1950).
http://p3.snf.ch/project-133692

Es würde sicher genügen, diese Notiz diskret am unteren Seitenende zu platzieren, nicht notwendigerweise schon im  Einleitungstext.

Sobald RISM canto aufgeschaltet ist, würde ich in der SNF-Projektdatenbank die entsprechende Aktualisierung vornehmen.

Diesen Satz werde ich Ihnen in Kürze auch in den verbleibenden drei Sprachen zuschicken.


- Ich würde Sie auch noch bitten, den ersten Satz des deutschen Einleitungstextes / Projektbeschreibung wie folgt zu ändern:

RISM canto ist eine bibliographische Datenbank, die Textquellen zum Thema Gesang aus über vier Jahrhunderten abendländischer Musikgeschichte sammelt.

**Comment by bjoernkessler** [comment]
- [ ] Übersetzungen des Footers einfügen
- [ ] "Author" statt "Composer"?
- [ ] "Erscheinungsjahr" statt "Datum"?
- [ ] "Canto" im Seitentitel
- [ ] zu klären: Wie und von wem werden neue Einträge vorgenommen?
