### ISSUE TITLE
856 $x (Source) mit Linktyp=Quellendigitalisat auszeichnen

### ISSUE THREAD

**Issue by jenniferward** [rism-international/tasks#497]
!! Wichtig: Voraussetzung: Link type 856 $x muss leer sein; vorhandenen Linktyp bitte nicht überschreiben!!

856 $x mit Linktyp=**Quellendigitalisat** auszeichnen, wenn:
**(1)**
Alle Titel, wo 856 $z enthält **nur**:
- Digital copy
- Digital version 
- Digitalizovaný  dokument (klikněte pro zobrazení)

**(2)**
Alle Titel, wo 856 $z enthält **irgendwo**:
- Digitized        
_(Beispiele: Digitized copy | Digitized music | [digitized version] )_
- Digitalisat*     
_(Beispiele:  Digitalisat der Partitur | Digitalisate | Digitalisat. | Link zum Digitalisat)_

**Comment by HirschSt** [comment]
Bitte stichprobenartig https://raw.githubusercontent.com/rism-international/muscat-maintenance/master/log/20191021_digit.log durchsehen. Wenn alles ok ist, kann das Wartungsskript im Produktionssystem durchlaufen.

**Comment by jenniferward** [comment]
Auch grünes Licht von mir, vorausgesetzt, dass die Exemplare in einem gesonderten Wartungsskript behandelt werden.

**Comment by HirschSt** [comment]
Wartungsskript lief Ende Mai 2020, s. https://github.com/rism-international/muscat-maintenance/blob/master/log/20200502_digit.log

**Comment by jenniferward** [comment]
Wurde [digitized version] aus Versehen mit "Other" ausgezeichnet?

I, [2020-05-04T11:16:04.188593 #14586]  INFO -- : lab.rism: Holding #1295 '$z[digitized version]' added '$xOther'
I, [2020-05-04T11:16:06.707456 #14586]  INFO -- : lab.rism: Holding #2883 '$z[digitized version]' added '$xOther'
I, [2020-05-04T11:17:05.401464 #14586]  INFO -- : lab.rism: Holding #254947 '$z[digitized version] [Altus]' added '$xOther'

Und hier "Stemel" mit "Digitalization"?
I, [2020-05-04T11:16:08.165330 #14586]  INFO -- : lab.rism: Holding #4954 '$zStempel' added '$xDigitalization'

**Comment by jenniferward** [comment]
Hallo @HirschSt , nur sicherheitshalber, siehe bitte meinen Kommentar vom 9. Juli oben. Einige Digitalisate wurden mit "Other" ausgezeichnet:

https://muscat.rism.info/admin/holdings/1295/edit

Von den Holdings 2883, 254947 und 4954 im o.g. Kommentar sehe ich das Problem nicht mehr, vielleicht wurde die Änderung rückgängig gemacht?

"[digitized version]" gehörte zur Regel: 
> Alle Titel, wo 856 $z enthält **irgendwo**:
> 
> * Digitized
>   _(Beispiele: Digitized copy | Digitized music | [digitized version] )_

**Comment by HirschSt** [comment]
see #951

**Comment by BaMikusi** [comment]
#951 is now done, can this issue and #819 be closed together with it?

**Comment by jenniferward** [comment]
My two previous comments haven't been addressed yet.
I was going to wait until #951  is in the OPAC before I close this. #951 contains 4,000 items - my list has over 16,000 that are missing $x. Some are surely "other," but "Digitalisat" and "Digitalisate" are not included in #951.

**Comment by jenniferward** [comment]
Inzwischen erledigt
