### ISSUE TITLE
856 $x mit Linktyp=Sonstiges auszeichnen

### ISSUE THREAD

**Issue by jenniferward** [rism-international/tasks#498]
!! Wichtig: Voraussetzung: Link type 856 $x muss leer sein; vorhandenen Linktyp bitte nicht überschreiben!!

856 $x mit Linktyp=**Sonstiges** auszeichnen, wenn:
**(1)**
Alle Titel, wo 856 $z enthält **nur**:
- Parallelquelle
- Parallelüberlieferung
- Referenzquelle
- Libretto
- Original catalog entry
- [bibliographic record]
- Original catalogue entry
- Quellenbeschreibung
 - Projektwebseite
- Hofmeister
- Edition
- Zobrazení hudebního incipitu
- Textbuch
- Textdruck

**(2)**
Alle Titel, wo 856 $z enthält **irgendwo**:
- Schriftprobe
- Wasserzeichen*
_(Beispiele: Wasserzeichen | Wasserzeichens | Wasserzeichen(WZIS) )_
- Watermark
- Homepage
- Bach*
_(Beispiele:  Bach-Digital | Bach Digital)_

**Comment by HirschSt** [comment]
Bitte stichprobenartig https://raw.githubusercontent.com/rism-international/muscat-maintenance/master/log/20191021_digit.log durchsehen. Wenn alles ok ist, kann das Wartungsskript im Produktionssystem durchlaufen.

**Comment by jenniferward** [comment]
Im Titel 1001004071 kommt das Feld 856 4x vor:
Wasserzeichen 1
Wasserzeichen 2
Wasserzeichen 5
Schriftprobe Copyist Anon. D-B 287 (ca. 1800) [vol. 1, p. 99-100, f. 129r-v; vol. 2, f. 75r-v]
jedoch sehe ich im o.g. Link nur 1x:
I, [2019-10-22T09:23:53.715570 #25673]  INFO -- : lab.rism: Source #1001004071 '$zSchriftprobe Copyist Anon. D-B 287 (ca. 1800) [vol. 1, p. 99-100, f. 129r-v; vol. 2, f. 75r-v]' added '$xOther'

Auch im Titel 1001031090 gibt es 5x 856, alles Wasserzeichen 1 bis 5.
In der Liste sehe ich nur:
I, [2019-10-22T09:24:31.463722 #25673]  INFO -- : lab.rism: Source #1001031090 '$zWasserzeichen 5' added '$xOther'

Im Titel 600077051 kommt 856 2x vor: 
Referenzquelle
Parallelquelle
Im Link nur:
I, [2019-10-22T09:06:27.811861 #25673]  INFO -- : lab.rism: Source #600077051 '$zParallelquelle' added '$xOther'

Unsere Angabe "[bibliographic record]" steht nicht im Link. 
Wurden Exemplareinträge auch berücksight?
Beispiel: 993121615

Fortsetzung folgt...

**Comment by HirschSt** [comment]
@jenniferward danke, durch ein Versehen wurde in die Protokoll-Datei nur die letzte URL berücksichtigt, das ist jetzt behoben.
Holding records werden in einem gesonderten Wartungsskript behandelt. Die Titel können bis zum Ende von KW 47 auch auf beta.rism.info geprüft werden.

**Comment by jenniferward** [comment]
OK, die Exemplareinträge sind auch davon betroffen, und haben dieselben Bedingungen wie im diesem Ticket und #497

**Comment by jenniferward** [comment]
Ansonsten grünes Licht von mir

**Comment by jenniferward** [comment]
Wie ist der Stand der Dinge, auch wg. Exemplare?

**Comment by HirschSt** [comment]
Bei den Quellen ist das durchgelaufen, bei den Holdings wird das demnächst gemacht

**Comment by HirschSt** [comment]
done with https://github.com/rism-international/muscat-maintenance/commit/38531984e2ed12f3d3ab113ff1738f0fb08e9c39
