### ISSUE TITLE
Change templates for prints

### ISSUE THREAD

**Issue by bjoernkessler** [rism-international/tasks#505]
- [x] The template for prints should be changed.
- [x] For Collection entries the holdings information should be seperate.

See e.g.
https://sistina.rism.info/admin/sources/85702071

**Comment by HirschSt** [comment]
how many prints are in sistina? Maybe we can discuss this in the next days...

**Comment by bjoernkessler** [comment]
There are about 1390 printed pieces and a little bit more than 100 codes.

**Comment by bjoernkessler** [comment]
Check ./makeHoldings.rb in b07e660
