### ISSUE TITLE
Write some basic rspec regarding template change

### ISSUE THREAD

**Issue by HirschSt** [rism-international/tasks#527]
eg "Make manuscript to print"

**Comment by bjoernkessler** [comment]
Quelltemplate -> Zieltemplate
Belegte Felder ohne Zielfelder kommen in 599 (interne Bemerkungen)

**Comment by HirschSt** [comment]
initial done with https://github.com/rism-ch/muscat/blob/5.3-devel-assoc/spec/lib/check_dependencies_spec.rb
