### ISSUE TITLE
Vorschlag Statistik Muscat

### ISSUE THREAD

**Issue by jenniferward** [rism-international/tasks#531]
Nur ein Vorschlag: kann auf dieser Seite
https://muscat.rism.info/admin/statistics
die Kopfzeile in der Tabelle (wo die Monatsnamen gekennzeichnet sind)  fixiert werden? Man verliert den Überblick, vor allem wenn man weiter nach unten scrollt und man nur 0 0 0 0 1 sieht.

**Comment by HirschSt** [comment]
mal sehen was ich machen kann, danke für den Vorschlag. Als Zwischenlösung (wenn man die statistik nicht allzuoft auswertet) kannst Du aber auch die Tabelle als CSV exportieren und dann in Libreoffice die erste Zeile fixieren

**Comment by HirschSt** [comment]
done with https://github.com/rism-ch/muscat/commit/7e8c36bc4367e58cbb518862d15b32d6a282c2eb
