### ISSUE TITLE
Check the index trigger with holdings

### ISSUE THREAD

**Issue by HirschSt** [rism-international/tasks#533]
same as https://github.com/rism-ch/muscat/issues/770

**Comment by bjoernkessler** [comment]
This is the call that returns the wrong value: 
```Source.ransack(lib_siglum_cont: 'SK-BRnm').result.count```
That means runsack needs an update a some point.
For reference, the correct values are returned by:
```(Source.search do with(:filter_lib_siglum, 'SK-BRnm') end).result.count```

**Comment by HirschSt** [comment]
- [ ] seek all frontend references to holdings
