### ISSUE TITLE
Richtlinien: "Table of content" in "Table of contents" bitte  ändern

### ISSUE THREAD

**Issue by jenniferward** [rism-international/tasks#534]
Richtlinien: "Table of content" in "Table of contents" bitte ändern

Hier:
https://muscat.rism.info/admin/guidelines

auf der rechten Seite:
![image](https://user-images.githubusercontent.com/18663291/55809275-e9eaca80-5ae5-11e9-9223-83475567977e.png)

**Comment by HirschSt** [comment]
done with https://github.com/rism-ch/muscat/commit/8111371448ff93b3237998c3512ebfba616d8226
