### ISSUE TITLE
Richtlinien: [unspecified] bitte löschen

### ISSUE THREAD

**Issue by jenniferward** [rism-international/tasks#538]
Könntest du bitte die [unspecified]-Teile hier
https://muscat.rism.info/admin/guidelines (English)
bitte entfernen? 

[unspecified] taucht 2x auf:

4.6.8 – [unspecified] Note on performance (511 $a) : Das Dokument wurde schon vor einer Weile aus guidelines.rism.info gelöscht.

11.1.3 – [unspecified] HELP WILL FOLLOW  : Hierfür müssen die Dokumente catalogue_240 und catalogue_730 als 11.1.3 bzw. 11.1.4 eingebaut werden. (Sie fehlen komplett auf der Gesamtseite, sind aber in der Literatur-Template sichtbar.)

**Comment by HirschSt** [comment]
done with https://github.com/rism-ch/muscat-guidelines/commit/b098354c9d615e666bac493a0c62f9c39cfb8d34
