### ISSUE TITLE
Richtlinien: best_practices bitte einbauen

### ISSUE THREAD

**Issue by jenniferward** [rism-international/tasks#539]
Hier https://muscat.rism.info/admin/guidelines#aid_best steht "HELP WILL FOLLOW" aber die Help gibt es schon, die heißt: best_practices

Könntest du den Text bitte einbauen?

**Comment by HirschSt** [comment]
done with https://github.com/rism-ch/muscat-guidelines/commit/d5ba925146e7e22ad4ee94f89ca50c537ee77db2
