### ISSUE TITLE
Personen - Authentication Code sollte nicht verdoppelbar sein

### ISSUE THREAD

**Issue by alexandermarxen** [rism-international/tasks#570]
Feld 042 (Authentication Code) ist derzeit verdoppelbar. Das ist unnötig.
Da es auch immer ausgefüllt wird, sollte es standardmäßig geöffnet sein

**Comment by HirschSt** [comment]
done with https://github.com/rism-ch/muscat/commit/270969f33bfd562d886ece52e5c3420e90e33340
