### ISSUE TITLE
Personen - Länder-Code: Zwei Verdopplungsmöglichkeiten

### ISSUE THREAD

**Issue by alexandermarxen** [rism-international/tasks#572]
Für das Feld 043 (Länder-Code) gibt es zur Zeit zwei Verdopplungsmöglichkeiten, eine davon (am besten die vor dem Auswahlfeld) kann entfallen. Ggf. müsste geprüft werden, ob die Inhalte bei unterschiedlichen Verdopplungen an verschiedenen Stellen gespeichert werden.
![Person erstellen   Muscat](https://user-images.githubusercontent.com/42838336/59758263-cf736100-928d-11e9-8067-e900a008d3e6.png)

**Comment by HirschSt** [comment]
done with https://github.com/rism-ch/muscat/commit/a8aea496c6582e36b5d24b8d69af412d56657269
