### ISSUE TITLE
Personen - Import von Datensätzen aus der DNB (Probleme mit Umlauten)

### ISSUE THREAD

**Issue by alexandermarxen** [rism-international/tasks#575]
Beim Import von Datensätzen werden Umlaute nicht korrekt importiert. Sichtbar wird dies, wenn man den Umlaut per Backspace-Taste löscht. Dann wird beispielsweise aus einem "ä" ein "a". Die Datensätze sind in Muscat ohne manuelle Korrektur (Ersetzen des falschen Umlauts in einen richtigen) nicht suchbar.
Dies betrifft grundsätzlich alle importierten Felder.
Beispiel:
https://muscat.rism.info/admin/people/37261

**Comment by HirschSt** [comment]
Das betrifft nur die Suchbarkeit bzw. Indexierung?

**Comment by alexandermarxen** [comment]
Ich denke, es betrifft nur Suchbarkeit und Indexierung. In der XML-Ansicht sehen die Umlaute unverdächtig aus, so dass es vermutlich beim Export keine Rolle spielt.
Mitunter werden Personen mehrfach angelegt, weil sie in der Auswahlliste nicht gefunden werden.

**Comment by HirschSt** [comment]
kommt direkt von Viaf json: 
```json
{"type":"subfield","code":"a","content":"Hässler, Johann Wilhelm"}
```
```ruby
irb> "Hässler".bytes
[72, 97, 204, 136, 115, 115, 108, 101, 114]
```

**Comment by HirschSt** [comment]
Direkt von Viaf.org Website http://viaf.org/processed/DNB%7C11636906X, byes identisch wie oben.

Bei http://d-nb.info/gnd/11636906X ist die Ansetzung von Hässler auf der Website korrekt:
""Hässler".bytes -> [72, 195, 164, 115, 115, 108, 101, 114]

Im exportierten Marc-Datensatz dann aber anders (falsch) wie oben
```xml
<datafield tag="100" ind1="1" ind2=" ">
  <subfield code="a">Hässler, Johann Wilhelm</subfield>
  <subfield code="d">1747-1822</subfield>
</datafield>
```
```ruby
"Hässler".bytes -> [72, 97, 204, 136, 115, 115, 108, 101, 114]
```
möglicherweise also ein Verarbeitungsproblem bei der DNB

**Comment by HirschSt** [comment]
Possible fix
```ruby
irb> "Hässler".unicode_normalize.bytes
irb> [72, 195, 164, 115, 115, 108, 101, 114]
```

siehe https://www.honeybadger.io/blog/ruby-unicode-normalization/

**Comment by HirschSt** [comment]
done with https://github.com/rism-ch/muscat/commit/f6145df863416c9013474bfa4749d2c303c588e8
