### ISSUE TITLE
Personen - Verknüpfung mit Körperschaften

### ISSUE THREAD

**Issue by alexandermarxen** [rism-international/tasks#577]
Das Feld 510 (Zugehörige Sigel) erlaubt derzeit nur eine Verknüpfung über das Bibliotheks-Sigel. Damit entfällt die Möglichkeit, Personen beispielsweise mit Verlagen, Orchestern etc. zu verknüpfen.

**Comment by HirschSt** [comment]
Bei mir klappt die Suche über das Lupensymbol, aber nicht über das Autocomplete, wo nur Sigel angezeigt werden. Das Feld müsste dann auch umbenannt werden.

**Comment by HirschSt** [comment]
Das Autocomplete habe ich jetzt umgestellt, s. https://github.com/rism-ch/muscat/commit/8b554afb058d757181c87b4496bbf1c81ab8b19e

**Comment by alexandermarxen** [comment]
Herzlichen Dank! Muss bei den bereits bestehenden Verknüpfungen, die ja über das Bibliotheks-Sigel liefen, noch etwas korrigiert werden?
Für die Umbenennung schreibe ich noch ein Ticket.

**Comment by HirschSt** [comment]
Nein, da hat sich nichts geändert.

Am Mo., 27. Jan. 2020 um 10:09 Uhr schrieb alexandermarxen <
notifications@github.com>:

**Comment by alexandermarxen** [comment]
Ich habe es gerade nochmal auf beta getestet: Bei der Auswahl einer Körperschaft ohne Bibliothekssigel verschwindet die Verknüpfung zur Körperschaft beim Abspeichern.

**Comment by HirschSt** [comment]
Bitte nochmal testen, auch mit Altdaten: in 510$a kommt jetzt die Ansetzungsform der Institution, nicht mehr das Sigel; die Verknüfung mit der ID in $0 bleibt unangetastet.

**Comment by alexandermarxen** [comment]
Jetzt geht es! Vielen Dank!
Bei den Altdaten ist es jetzt natürlich etwas merkwürdig, siehe z.B. https://beta.rism.info/admin/people/30019235
In Kallisto war das Feld in Kombination mit 678 ja für Angaben zu Personen auf der Quelle vorgesehen und die Verknüpfung zum Sigel quasi eine Aufschlüsselung des Sigels.
Ließe sich vielleicht noch ein Link zum Körperschaftsdatensatz basteln?

**Comment by HirschSt** [comment]
> Ließe sich vielleicht noch ein Link zum Körperschaftsdatensatz basteln?

Ist erledigt.

**Comment by alexandermarxen** [comment]
Super! Gefällt mir sehr gut so!

**Comment by HirschSt** [comment]
done with https://github.com/rism-ch/muscat/commit/140034f769e2b23c8d125ef038f251cd2c6e4454
