### ISSUE TITLE
Personen - Das Feld "Beruf oder Funktion" sollte standardmäßig geöffnet sein.

### ISSUE THREAD

**Issue by alexandermarxen** [rism-international/tasks#578]
Das Feld 550 (Beruf oder Funktion) wird fast immer ausgefüllt und sollte daher standardmäßig geöffnet sein.

**Comment by HirschSt** [comment]
done with https://github.com/rism-ch/muscat/commit/597191633e02fa64bab139c4874f99dabd835449
