### ISSUE TITLE
Personen - Verknüpfung zum Normdatenbestand Orte

### ISSUE THREAD

**Issue by alexandermarxen** [rism-international/tasks#579]
Das Feld 551 (Orte) ist derzeit ein reines Textfeld. Eine Verknüpfung zum Normdatenbestand (später Thesaurus?) „places“ wäre sehr sinnvoll und hilfreich.

**Comment by HirschSt** [comment]
Eine direkte Verknüpfung, etwa wie bei den Körperschaften, ist aufwendig zu realisieren. Ich würde das gerne mit der Einführung des Thesaurus kombinieren, dieses Teilprojekt wäre für die Umstellung sehr gut geeignet. 

Für den Übergang könnte auch ein Autocomplete eingerichtet werden. Wenn das ein provisorischer Ersatz wäre und hohe Priorität hat, würde ich das für die Übergangszeit (ca.6-12 Monate) implementieren. Hierfür dann ein neues Ticket schreiben und dieses schließen.

**Comment by alexandermarxen** [comment]
Thesaurus ist auf jeden Fall die beste Lösung!
