### ISSUE TITLE
Personen - Mehrere Zeilen im Feld "Weitere biographische Angaben"

### ISSUE THREAD

**Issue by alexandermarxen** [rism-international/tasks#580]
Zur Zeit gibt im Feld 678 (Weitere biographische Angaben) drei Zeilen zur Eingabe, von der nur die erste publiziert wird. Bitte die zwei überflüssigen Zeilen löschen.
![Person erstellen   Muscat](https://user-images.githubusercontent.com/42838336/59759879-4fe79100-9291-11e9-86b9-2a8c7326af7f.png)

- [x] remove from editor (done with https://github.com/rism-ch/muscat/commit/a58f9434c40c20ad45ad7b491ad4d1acd2d7c268)
- [x] check for existing data
- [ ] remove from configuration

**Comment by HirschSt** [comment]
http://www.loc.gov/marc/authority/ad678.html
Es handelt sich bei den Zeilen um die Subfields $b und $u. Ich kann diese aus dem Editor entfernen. In einem nächsten Schritt muss ich prüfen, ob diese subfields belegt sind. Wenn nicht, werden sie auch aus der Konfiguration entfernt.

**Comment by HirschSt** [comment]
@alexandermarxen in den Subfeldern $b und $u stehen bisher noch keine Daten. Jetzt ist noch die Frage, ob wir die Felder in der Konfiguration trotzdem für eventuell späteren Gebrauch stehen lassen, denn ein späteres Neuhinzufügen ist wesentlich umständlicher. Siehe dazu https://www.loc.gov/marc/authority/ad678.html

**Comment by alexandermarxen** [comment]
Ja, das wäre für mich kein Problem. Auch wenn mir momentan noch kein konkreter Nutzen für die Felder einfällt, musst Du sie nicht löschen.
Mir war wichtig, dass sie nicht als Textfelder stehen bleiben und dann als verdoppeltes Subfeld $a verstanden und verwendet werden.

**Comment by HirschSt** [comment]
Prima, danke. Im Editor sind sie ja weg, daher sollte das kein Problem mehr sein. Wenn wir sie aber später benötigen sollten, zaubern wir sie wieder herbei...
