### ISSUE TITLE
Personen - Mehrere Zeilen im Feld "Allgemeine Bemerkungen"

### ISSUE THREAD

**Issue by alexandermarxen** [rism-international/tasks#581]
Zur Zeit gibt im Feld 680 (Allgemeine Bemerkungen) drei Zeilen zur Eingabe, von der nur die erste publiziert wird. Bitte die zwei überflüssigen Zeilen löschen.

**Comment by HirschSt** [comment]
Wie sonst wurden zunächst die nicht genutzten Felder aus dem Editor entfernt https://github.com/rism-ch/muscat/commit/b696a375434329a7fe9aacf08a1e69fbae7eef66, die Bereinigung ggf. vorhandener Daten erfolgt später
