### ISSUE TITLE
Personen - Bei Normdatenverweisen: Verlinkung zu ICCU

### ISSUE THREAD

**Issue by alexandermarxen** [rism-international/tasks#591]
Im Feld 024 (Normdatenverweise) wäre eine Verlinkung zu ICCU analog zur Verlinkung zur VIAF oder DNB sinnvoll.
Beispiel:
https://muscat.rism.info/admin/people/30000064
https://opac.sbn.it/opacsbn/opac/iccu/scheda_authority.jsp?bid=IT%5cICCU%5cCFIV078349
Der String müsste wohl: https://opac.sbn.it/opacsbn/opac/iccu/scheda_authority.jsp?bid=IT%5cICCU% sein.

**Comment by HirschSt** [comment]
done with https://github.com/rism-ch/muscat/commit/83cd05cbbb7630b2621016e2f3cdcf07c6b0cd92
