### ISSUE TITLE
Check status of canto.rism.info

### ISSUE THREAD

**Issue by HirschSt** [rism-international/tasks#593]
no news on rism.info?

**Comment by MFalletta** [comment]
Der News-Text liegt vor. Wann erfolgt die Freischaltung der Daten?

**Comment by BaMikusi** [comment]
Freischaltung vorab geweigert vom Vorstand, weitere Diskussionen sind im Gange über die angemessene Veröffentlichungsform.

**Comment by rism-international** [comment]
Sehr ärgerlich...dann schließen wir das hier und machen falls notwendig ein neues Ticket auf.
