### ISSUE TITLE
Incipits mit 0 in 031 $o (Metrum)

### ISSUE THREAD

**Issue by jenniferward** [rism-international/tasks#607]
Es gibt ca. 5000 Incipits wo 031 $o = 0 

Bei ziellos ausgewählten Titeln steht immer die Bemerkung (031 $q) "Taktart ermittelt", d.h. eine Taktart ist irgendwie gemeint (und nicht keine Taktart).

Beispiele: 
(GB) https://muscat.rism.info/admin/sources/800265428
(D) https://muscat.rism.info/admin/sources/455014432
(SI) https://muscat.rism.info/admin/sources/540000215

Ca. 10 Titel wurden in Muscat erstellt und sollen hier nicht berücksichtigt werden.

**Comment by HirschSt** [comment]
Ich habe das geprüft, die Angaben stammen bereits aus Kallisto, z.B.:

```
SQL> select h0001 from hspr01 where rismnr = '540000215';

     H0001
----------
  31136753

SQL> select h0001 from hspr01 where colkey = '31136753';

     H0001
----------
  31136754

SQL> select takta from hspr01 where h0001 = 31136754;

TAKTA
--------------------------------------------------------------------------------
0

SQL> select incbm from hspr01 where h0001 = 31136754;

INCBM
--------------------------------------------------------------------------------
Taktart ermittelt

SQL> 


```

**Comment by MFalletta** [comment]
Die Null bitte aus den Daten löschen, ebenso den Vermerk "Taktart ermittelt"

Sofern möglich Vermerk in 599 "Taktart überprüfen (IncipitNr.)" ergänzen

**Comment by HirschSt** [comment]
wird über ein Wartungsskript umgesetzt

**Comment by HirschSt** [comment]
done with https://github.com/rism-international/muscat-maintenance/commit/1442fe758a37d06bc2f09be77e9f741ff211348d

**Comment by HirschSt** [comment]
kann anhand von https://raw.githubusercontent.com/rism-international/muscat-maintenance/master/log/20200907-clearing_031.log auf beta noch kurzzeitig geprüft werden

**Comment by jenniferward** [comment]
Ich habe ca. 10 Titel geprüft.
Der Vermerk "Taktart ermittelt" ist in 031 manchmal noch vorhanden: 136482, 452520045
Beides: Taktart ermittelt; ? 


@MFalletta : An wen wäre der 599 Vermerk "Taktart überprüfen (IncipitNr.)" im Titel gerichtet?

**Comment by HirschSt** [comment]
Der vermerk "Taktart ermittelt" wird jetzt auch gelöscht, wenn weitere Angaben in dem Feld vorhanden sind, s. https://github.com/rism-international/muscat-maintenance/commit/432057e1d6036ae498325567dca9d1ab30e5a0a4
