### ISSUE TITLE
ICCU: Problem Sammelhandschriften

### ISSUE THREAD

**Issue by KlausKeil** [rism-international/tasks#609]
Habe eine Sammelhandschrift gefunden, bei der der Haupteintrag auch als erster Einzeleintrag benutzt wurde. Drangehängt sind zwei weitere Einzeleinträge, die aber keinen Fundort haben (weder Bibliothekssigel, noch Signatur) 
Siehe: 850600294; 850600311

**Comment by KlausKeil** [comment]
Anderer Fall: Sammelhss. im Haupteintrag steht I-Fn, die Einzeleinträge haben I-Rrostirolla. Die Liste in Muscat zeigt I-Rrostirolla an. 
Ist da eine Sigelkorr. gemacht worden und die Einzeleinträge vergessen?
850668714
--

**Comment by HirschSt** [comment]
Frage 1 ist erledigt, Frage 2 bezieht sich auf eine Kontrolle der Sigel von Collection und Einzeleinträge. @MFalletta Wie soll verfahren werden, wenn beide voneinander abweichen?

**Comment by HirschSt** [comment]
see list at https://github.com/rism-international/muscat-maintenance/blob/master/log/20200903-check_siglum.log

**Comment by MFalletta** [comment]
Danke für die Aufstellung!
Ich habe daraus eine Tabelle gemacht:  
https://docs.google.com/spreadsheets/d/1DEN7VaHNsB4fSjZRin75roqZi_kuI5fWh4X7QHEYqxY/edit#gid=0
@docudoctor Bitte auch einen Blick reinwerfen!

**Comment by jenniferward** [comment]
Wir nehmen das Thema im Herbst wieder auf.

**Comment by jenniferward** [comment]
Wir brauchen dieses Ticket nicht mehr; @docudoctor und @MFalletta haben die Tabelle.
