### ISSUE TITLE
ICCU: falscher tag

### ISSUE THREAD

**Issue by KlausKeil** [rism-international/tasks#627]
850817474 hat in 852 einen falschen tag. Kann nicht gespeichert werden.

**Comment by HirschSt** [comment]
Bitte erneut prüfen, speichern ging bei mir ohne Probleme.

**Comment by MFalletta** [comment]
Das betrifft nicht nur die ICCU-Daten. Habe die Fehlermeldung auch gerade bekommen.
RISM ID no. 600500090
![Tag 852a vom 2019-08-26 10-27-43](https://user-images.githubusercontent.com/18736235/63677025-71627d00-c7ec-11e9-825d-933d03336481.png)

**Comment by HirschSt** [comment]
Auch diesen Fehler kann ich nicht reproduzieren, speichern ging ohne Probleme. Bitte erneut prüfen.

**Comment by jenniferward** [comment]
Diesen Fehler habe ich auch mal gehabt - A/I glaube ich - ich melde mich, falls er wieder auftaucht.

**Comment by MFalletta** [comment]
Heute konnte ich meine Korrekturen abspeichern!

**Comment by jenniferward** [comment]
Ich hatte es gerade eben - 1001008027 (auch aus A) - habe nichts geändert, nur den Titel eine zeitlang im Bearbeitungsmodus gelassen und überall geklickt. Als ich wieder auf "Library information and relations" klickte, kam die Fehlermeldung.

**Comment by MFalletta** [comment]
Ich hatte die Meldung auch gerade wieder bei
https://muscat.rism.info/admin/sources/703001970

Ich war in den Feldern 240, 650, 594, 500 und 518

**Comment by HirschSt** [comment]
Könnt Ihr bei den einzelnen Titeln die Fehlermeldung reproduzieren?

**Comment by MFalletta** [comment]
Leider nein! Diesmal sind alle Korrekturen angenommen worden.

**Comment by jenniferward** [comment]
Ich kann sie auch niemals reproduzieren. Führt etwas dazu, dass die Meldung
![image](https://user-images.githubusercontent.com/18663291/63841668-81f92b80-c983-11e9-8479-89eab9d3ba4d.png)

nicht ausgelöst wird?

**Comment by HirschSt** [comment]
Vor dem Speichern wird stets validiert. Möglicherweise handelt es sich um ein Browserproblem mit Javascript, aber das kann ich eben nicht reproduzieren.

Wenn die Meldung seit mehr als 20 tagen nicht mehr aufgetreten ist, würde ich das Ticket demnächst schließen.

**Comment by HirschSt** [comment]
closed due to inactivity
