### ISSUE TITLE
Personen - Auswahlliste "Art der Namensvariante"

### ISSUE THREAD

**Issue by alexandermarxen** [rism-international/tasks#633]
Bitte folgende Begriffe aus der Auswahlliste "Art der Namensvariante" löschen:
Familienname
Monogramm
andere Suchform
Personenname
Unbekannt
Falls diese Begriffe verwendet wurden, können die Werte in den Titeln gelöscht werden.

**Comment by HirschSt** [comment]
done with https://github.com/rism-ch/muscat/commit/072aa59a8355f2daaa3336f717780fef6a4dce4a
---------------
ef Familienname
mo Monogramm
dv andere Suchform
ff Personenname
xx Unbekannt
