### ISSUE TITLE
Personen - Begriffe im Menü "Relationship (500)"

### ISSUE THREAD

**Issue by alexandermarxen** [rism-international/tasks#637]
Englische Oberfläche:
Bitte den Begriff "married with" in "married to" ändern

**Comment by HirschSt** [comment]
done with https://github.com/rism-ch/muscat/commit/e96df8f75db4265961e83b4af02543ab65d66f21

**Comment by jenniferward** [comment]
Ich sehe hier "unspecified" in der EN- Oberfläche
![image](https://user-images.githubusercontent.com/18663291/74925203-1349d780-53d4-11ea-97bf-3eba0eb3ae66.png)
