### ISSUE TITLE
Personen - Auswahlliste für das Feld "Beruf oder Funktion (550)"

### ISSUE THREAD

**Issue by alexandermarxen** [rism-international/tasks#639]
Langfristig soll das Feld zu einem Thesaurus werden (auch wg. Mehrsprachigkeit). Könnte man als Übergangslösung eine Auswahlliste der bislang verwendeten Begriffe anbieten?

**Comment by HirschSt** [comment]
Auf beta ist eine Version mit autocomplete zu diesem Feld. Bitte kurz testen, ob das als eine Übergangslösung geeignet ist.

**Comment by alexandermarxen** [comment]
Danke! Sieht sehr gut aus!
