### ISSUE TITLE
Sekundärliteratur - englische Oberfläche - fehlende Feldbezeichnungen

### ISSUE THREAD

**Issue by MFalletta** [rism-international/tasks#640]
Bei einigen Feldern fehlen noch die Feldbezeichnugnen.
Bitte folgende Begriffe für die genannten Felder ergänzen:

Function - bei 700 $4 
Related place - 651
Preceding entry - 780
Succeeding entry - 785
Internal note - 599
Contents note - 520

![Literatur eng 2019-08-27 13-12-11](https://user-images.githubusercontent.com/18736235/63768337-3df91e80-c8d0-11e9-9ae0-9b8ecf9dd0a8.png)

**Comment by HirschSt** [comment]
done with https://github.com/rism-ch/muscat/commit/8f4bed36a9729685b6e19041d22d4bd0dc0aa05c
