### ISSUE TITLE
BNF: Fehlende Materialangaben

### ISSUE THREAD

**Issue by MFalletta** [rism-international/tasks#663]
in 840011066 wurde nur die Partitur in 300 übernommen

Es gibt aber auch 18 Stimmen (= 2. Materialgruppe)
 215 .. $a 1 partition ([39] p.) $d 30 x 22,5 cm $e 18 parties ; 30 x 22,5 cm 
Angaben zu den einzelnen Stimmen stehen bereits in 500 aus
300 .. $a Parties instrumentales : violino primo (3 p. ), violino secondo 3 ex. (4 p. chacun), alto 2 ex. (4 p.), basse 4 ex. (4 p. chacun), flute (3 p.), clarinettes (4 p.), bassons (4 p.), cors 2 ex. (3, 4 p.), harpe (3 p.)

**Comment by HirschSt** [comment]
done with https://github.com/rism-international/import/commit/19347a086740b20389f95b1deb53952608031438
