### ISSUE TITLE
BNF: Dubletten F-Pn

### ISSUE THREAD

**Issue by MFalletta** [rism-international/tasks#664]
Wir haben in Muscat ca. 800 Handschriftentitel aus F-Pn. Wie vermeiden wir Dubletten?
Die Signaturen sind leider abweichend, lassen sie sich trotzdem vergleichen?

Einige Beispiele:
Mus. Vm/7. 6764 siehe  https://muscat.rism.info/admin/sources/840000701
VM7-6764 siehe https://bnf.rism.info/admin/sources/840012816

Mus.ms. 8508 siehe https://muscat.rism.info/admin/sources/840000106
MS-8508 siehe https://bnf.rism.info/admin/sources/840021843

Mus. L 2620 siehe https://muscat.rism.info/admin/sources/840000805
L-2620 siehe https://bnf.rism.info/admin/sources/840021809

**Comment by MFalletta** [comment]
Die Muscattitel dürfen nicht überschrieben werden. Hier steht viel mehr drin!
Beispiel:
Mus. D. 41 siehe https://muscat.rism.info/admin/sources/840000043  
D-41 siehe https://bnf.rism.info/admin/sources/840012307

Aber bitte den Link zum Original Catalogue entry in 856 ($u, $z, $x) ergänzen

**Comment by HirschSt** [comment]
Die Titel werden eingespielt, aber sind zunächst auf unpublished gesetzt. Wie Dubletten später zusammengeführt werden, wird manuell gesteuert.
