### ISSUE TITLE
BNF: Druck mit Verknüpfung zu Handschrift

### ISSUE THREAD

**Issue by MFalletta** [rism-international/tasks#667]
840016116 ist ein Musikdruck-Teileintrag mit übergeordneter Verknüpfung zu 840026018 im Template Handschrift, Autograph!

https://bnf.rism.info/admin/sources/840016116 siehe dazu auch original catalogue entry, https://catalogue.bnf.fr/ark:/12148/cb39780493d - dort sieht es so aus, als ob die Handschrift, dem Druck beiliegen würde

Der Druck entspricht https://muscat.rism.info/admin/sources/990003445

Verknüpfung herausnehmen?

**Comment by HirschSt** [comment]
wird manuell nach dem Import geprüft und falls nötig umgewandelt
