### ISSUE TITLE
BNF: Besitzer der Importdaten 

### ISSUE THREAD

**Issue by MFalletta** [rism-international/tasks#671]
Bitte alle Titel auf François-Pierre Goy stellen.

Account ist noch nicht angelegt!
francois-pierre.goy@bnf.fr
Berechtigung für F-Pn, F-Pa, F-Po

**Comment by HirschSt** [comment]
done with importscript https://github.com/rism-international/import/commit/f645a2000eeb9fc7dce8e8396350037e65ea2f7e

user should be created on production first
