### ISSUE TITLE
BNF: 100 zweimal vorhanden

### ISSUE THREAD

**Issue by MFalletta** [rism-international/tasks#695]
Durch 
#685 
oder 
#676 
ist nun 100 doppelt vorhanden 
siehe: https://bnf.rism.info/admin/sources/840029664

Vererben oder ergänzen sollte nur erfolgen, wenn 100 nicht schon vorhanden war.

**Comment by HirschSt** [comment]
done with https://github.com/rism-international/import/commit/36417c28ee45ef6f7de1e07ab3214a2e89bc8b03
