### ISSUE TITLE
BNF: Sekundärliteratur

### ISSUE THREAD

**Issue by MFalletta** [rism-international/tasks#702]
Von der "neuen" Sekundärliteratur lassen sich einige Kurztitel bereits vorhandenen IDs zuordnen. Damit wäre dann in immerhin 740 Quellen der richtige Datensatz verknüpft.
[BNF Literatur.xlsx](https://github.com/rism-international/tasks/files/3767203/BNF.Literatur.xlsx)

**Comment by HirschSt** [comment]
Leider kann ich im Vorlauf die Einträge nicht mit den Kurztiteln verbinden, weil ich hier keinen direkten Zugriff auf die Muscat-Datenbank habe. Die Titel können im Nachgang umgehängt werden.
