### ISSUE TITLE
Editors should see the data quality column

### ISSUE THREAD

**Issue by HirschSt** [rism-international/tasks#710]

**Comment by jenniferward** [comment]
Kann man schon jetzt auf EN einfach "Level" als Spaltenüberschrift nehmen? "Quality" könnte heikel sein, "level" ist neutraler und entspricht der Feldbezeichnung im 980.

**Comment by HirschSt** [comment]
Ja, ist umsetzt (https://github.com/rism-ch/muscat/commit/4528ef537a525735b9facb5952f85422a13de377)
