### ISSUE TITLE
Add new functions for (700 $4) in template holdings

### ISSUE THREAD

**Issue by Docudoctor** [rism-international/tasks#733]
1) Please add new function "Depositor [dpt]" for (700 $4) in template holdings.

2) Please add new function "Printer [prt]" for (700 $4) in template holdings.

3) Please add new function "Other [oth]" for (700 $4) in template holdings.

**Comment by jenniferward** [comment]
Printer has been added already: 
https://github.com/rism-ch/muscat/issues/819

**Comment by jenniferward** [comment]
oth has already been added.

**Comment by HirschSt** [comment]
done with https://github.com/rism-ch/muscat/commit/29f2c5be2c10defa9f68b1ffba159dd9928e6253

**Comment by jenniferward** [comment]
Hier liegt ein Missverständnis vor - dpt ist in 700 **nicht** gewollt.
Siehe Protokoll, ZR-Sitzung, 12.12-2019

**Comment by HirschSt** [comment]
@Docudoctor bitte bestätigen

**Comment by MFalletta** [comment]
Die Entscheidung während der Sitzung wurde von allen getragen und ist damit bestätigt.
