### ISSUE TITLE
Add new functions for (710 $4) in template holdings

### ISSUE THREAD

**Issue by Docudoctor** [rism-international/tasks#734]
1) Please add new function "Printer [prt]" for (710 $4) in template holdings.

2) Please add new function "Other [oth]" for (710 $4) in template holdings.

**Comment by jenniferward** [comment]
oth has already been added.

**Comment by HirschSt** [comment]
done with https://github.com/rism-ch/muscat/commit/80fff50cd73db464375aa7e6ffb292530e05706b
