### ISSUE TITLE
Werkebene Titel nicht zugänglich

### ISSUE THREAD

**Issue by KlausKeil** [rism-international/tasks#735]
Beim Aufrufen folgenden Titels in der Werkebene:

279 | Hummel, Johann Nepomuk: Trios op. 35; ZimH 35 G; pf, vl, vlc; | 6 | AnzeigenBearbeitenLöschen
-- | -- | -- | --

bekommt man die Meldung: The page you were looking for doesn't exist.

**Comment by HirschSt** [comment]
erneut geprüft, beim Aufruf des Titels gibt es keine Probleme
