### ISSUE TITLE
Check for sources without owner

### ISSUE THREAD

**Issue by HirschSt** [rism-international/tasks#738]

**Comment by HirschSt** [comment]
Currently we have ~ 55.000 records (sources) without owner (wf_owner: nil), mostly older ones, all are from CH. Needs to be clearified. This only touches sources, no holdings

**Comment by MFalletta** [comment]
263 records affect the unpubl. ICCU-Data

https://muscat.rism.info/admin/sources?order=lib_siglum_asc&page=1&per_page=100&q%5Bwf_owner_with_integer%5D=wf_owner%3A268&q%5Bwf_stage_with_integer%5D=wf_stage%3Ainprogress

**Comment by HirschSt** [comment]
Aber in diesen Titeln ist doch Massimo Gentili-Tedeschi als Besitzer eingetragen, oder verstehe ich etwas falsch?

**Comment by MFalletta** [comment]
Sorry, mein Versehen. Ich war auf 852 fixiert.

**Comment by HirschSt** [comment]
Waiting for user account of CH, who should be the owner then

**Comment by HirschSt** [comment]
creating maintenance for adding wf_owner

**Comment by HirschSt** [comment]
Done with archive/20220901_wf_owner.rb
