### ISSUE TITLE
Editor can't open without correct record_type

### ISSUE THREAD

**Issue by HirschSt** [rism-international/tasks#740]
https://github.com/rism-ch/muscat/blob/87b9deb245627489a3d889112668afda24ff1d3e/app/admin/source.rb#L93

see 840017127

Backtrace:

A NoMethodError occurred in sources#edit:

  undefined method `+' for nil:NilClass
  app/admin/source.rb:93:in `edit'

-------------------------------
Request:
-------------------------------

  * URL        : https://muscat.rism.info/admin/sources/840017127/edit
  * HTTP Method: GET
  * IP address : 141.2.23.18
  * Parameters : {"controller"=>"admin/sources", "action"=>"edit", "id"=>"840017127"}
  * Timestamp  : 2020-01-07 07:17:40 UTC
  * Server : b-web64
  * Rails root : /usr/local/SBB/var/rails/muscat-3.6
  * Process: 32164

**Comment by xhero** [comment]
This is a good catch, but… how was the record created? It is impossible in the muscat interface (unless you do it from the backend) to create records without record_id

**Comment by HirschSt** [comment]
It's an imported record from France BNF (from Unimarc)

**Comment by HirschSt** [comment]
since we don't have any nil record_types anymore, probably this can be closed. How about rescueing?
