### ISSUE TITLE
Personen - Neuer Feldname 510

### ISSUE THREAD

**Issue by alexandermarxen** [rism-international/tasks#744]
Bitte Feld 510 (im Normdatenbestand Personen) umbenennen in:

Deutsch: BEZIEHUNG KÖRPERSCHAFT
Französisch: INSTITUTIONS LIÉES
Italienisch: ISTITUZIONI CORRELATE

Englisch, portugiesisch und spanisch können so bleiben.

**Comment by HirschSt** [comment]
done with https://github.com/rism-ch/muscat/commit/0bf175bd535888c17adf46e6f96c60c75a7cd433
