### ISSUE TITLE
Pflichtfeld 852 bei Template Theoretica gedruckt

### ISSUE THREAD

**Issue by KlausKeil** [rism-international/tasks#748]
In dem Template Theoretica gedruckt gibt die Validierung beim Abspeichern den Fehler aus, dass 852 fehlt. Das Feld ist aber im Template nicht vorhanden, weil der Fundort im Exemplareintrag angegeben werden muss. Somit können solche Aufnahmen gar nicht abgespeichert werden. 
Beim "Bearbeiten" ist der Menupunkt "Neuer Exemplareintrag" nicht vorhanden. 

Es muss aber schon mal gegangen sein, denn ich konnte es bei diesem Titel: https://muscat.rism.info/admin/sources/1001031851
machen.

**Comment by jenniferward** [comment]
Ist vermutlich schon behoben, siehe
https://github.com/rism-ch/muscat/issues/886

**Comment by HirschSt** [comment]
Ja, ist mit 6.1 erledigt (s. https://github.com/rism-ch/muscat/commit/a28bd7c88e786926b67e538d97d288baf7efa8f5)

**Comment by HirschSt** [comment]
Stop, das kein Exemplar angelegt werden kann, muss ich noch prüfen...

**Comment by HirschSt** [comment]
Nein, beim Template "Theor. gedruckt" kann auch ein Exemplar angehängt werden. Könnte es sich vielleicht im "Theor. gedruckt, Teileintrag" handeln?

**Comment by KlausKeil** [comment]
Das Problem ist wohl, dass bis zum ersten Speichern des Titels das Anklickfeld Neuer Exemplareintrag nicht erscheint. Das Abspeichern geht aber nicht, weil 852 als Pflichtfeld gefordert wird.

**Comment by KlausKeil** [comment]
Ist das Problem, das die Validierung meldet, 852 sei Pflichtfeld und deshalb das Speichern verhindert, auch gelöst?
