### ISSUE TITLE
Literatur: "Früherer Eintrag (780)" anzeigen

### ISSUE THREAD

**Issue by jenniferward** [rism-international/tasks#749]
Bitte  "Früherer Eintrag (780)" anzeigen.
Siehe https://github.com/rism-ch/muscat/issues/630 für die Erlärung. 
http://muscat.rism.info/admin/catalogues/30023740 

#148

**Comment by HirschSt** [comment]
done with https://github.com/rism-ch/muscat/commits/catalogue_partial
