### ISSUE TITLE
Leere 852$c mit [no indication] ergänzen

### ISSUE THREAD

**Issue by jenniferward** [rism-international/tasks#751]
Wie in der Sitzung besprochen:
In Muscat kommt es ca. 42.000 Mal vor, dass 852$c leer ist. Durch ein Skript bitte ergänzen mit:

[no indication]

**Comment by HirschSt** [comment]
Wird zunächst für die Sources umgesetzt; soll das auch bei Holdings laufen?

**Comment by jenniferward** [comment]
Ja, bitte.

**Comment by HirschSt** [comment]
Ist auf beta umgesetzt

**Comment by HirschSt** [comment]
done with https://github.com/rism-international/muscat-maintenance/commit/ddfbc0111184470ab9aa8d315cb9e8b7fd087d85
