### ISSUE TITLE
Giacomo Puccini umhängen

### ISSUE THREAD

**Issue by MFalletta** [rism-international/tasks#752]
Bitte alle 212 Titel aus dem Ordner "Giacomo Puccini" mit dem Personendatensatz 30007675 Giacomo Puccini (1712-1781) verknüpfen
https://muscat.rism.info/admin/people/30007675

**Comment by HirschSt** [comment]
done with https://github.com/rism-international/muscat-maintenance/commit/5a3a9a96874377d76e9fbbf0317985a442778a40
