### ISSUE TITLE
Externer Link in Guidelines funktioniert nicht

### ISSUE THREAD

**Issue by jenniferward** [rism-international/tasks#753]
Hallo Stephan, könntest du bitte gucken:
https://muscat.rism.info/admin/guidelines#doc_when_new_record und die dort verlinkte URL zu 
http://rbms.info/dcrm/

![image](https://user-images.githubusercontent.com/18663291/75861414-a71c9a00-5dfd-11ea-8c90-9937ea430e07.png)

In den Richtlinien habe ich http://rbms.info/dcrm/ eingetragen:
![image](https://user-images.githubusercontent.com/18663291/75861516-cf0bfd80-5dfd-11ea-81b5-381d79fa9629.png)
![image](https://user-images.githubusercontent.com/18663291/75861635-f793f780-5dfd-11ea-8273-321a9303849b.png)

In Muscat verschwindet der : und der Link führt ins Leere: http //rbms.info/dcrm/

**Comment by HirschSt** [comment]
Auf beta.rism.info funktioniert der Link bei en; bei de (und wahrscheinlich auch bei den anderen Sprachen) ist der Link falsch gesetzt. Bitte mal auf beta nachprüfen.

**Comment by jenniferward** [comment]
PT und ES in Ordnung (weil dort der EN-Text [noch] steht)
