### ISSUE TITLE
Interne Felder von der Datenlieferung ausschließen 

### ISSUE THREAD

**Issue by jenniferward** [rism-international/tasks#754]
Momentan wird das interne Feld für die Personen (667) geliefert. Es wird zwar nicht im OPAC publiziert, aber sie sind in MARCXML und Open-Data-Angebot zu finden. Diese Felder sollen nicht geliefert werden.

Beispiele: 
Person
https://opac.rism.info/search?id=pe209&View=rism
![image](https://user-images.githubusercontent.com/18663291/75880440-911ed180-5e1d-11ea-8b58-1b012489c1ad.png)

(Bei den Quellen hatte ich ein Beispiel, aber es scheint nicht mehr der Fall zu sein. Vielleicht hat sich etwas wider geändert.)
(Literatur und Institutionen sind schon ausgeschlossen, siehe #312 )

**Comment by HirschSt** [comment]
done with https://github.com/rism-ch/muscat/commit/aa06cd81526be1ef48a28c4924adccdd34ebfade
