### ISSUE TITLE
Frankreich-Import: 031 Musikincipit

### ISSUE THREAD

**Issue by jenniferward** [rism-international/tasks#758]
Das ganze Feld 031 im Frankreich-Import weist mehrere Probleme auf. Einzelne Fälle kann ich evtl. händisch korrigieren, aber ich weiß nicht, ob man vielleicht global etwas anders machen kann?

**$d - Satztitel, Tempo**
Erwartung: bsp. Lento, allegro
Auswertung: Außer Satztitel und Tempo kommen auch Instrumente (ca. 100x) vor.
Beispiel: 
840018675 - Violino primo

**$n - Vorzeichen**
Erwartung: Form entsprechend Muscat (Bsp.: xF, xFC, bB, bBE)
Auswertung: Leider ca. 300x Schlüssel und Taktart drin, auch Vorzeichen, die nicht Muscat entsprechen. 
Beispiele:  840018720, 840012909, 840026505
räpresentative Werte:
2/2
b
xFmajeur
bF
xBE

**$o - Taktart**
Erwartung: Form entsprechend Muscat (Bsp.: 2/4)
Auswertung: Ca. 88x Noten reingerutscht. 
Beispiele:  840026040
2/4'''2.C/''8BAB'''C/''4BA/8GFGA/qG4FF;4/4;2/4

**$p - Musikincipit** 
Erwartung: Plaine & Easie-Code
Auswertung: Schwierig bei der Menge. Ich kann nur die Ausreißer erkennen:

1. 59x kommt # vor (statt x?) Beispiele: 840026040, 840016647
2. “ statt ‘’ [Anführungszeichen statt 2x Apostroph ] Häufig. Bsp: 84001002
3. X statt(?) x  Bsp.: 840010434  (kommt 1.000x vor)
4. N statt(?) n Bsp.: 840020569
5. Incipits, wo etwas fehlt, zB. “29” oder “24” am Anfang [29-Takt Pause??] : 840024623, 840014878;  “-13” am Anfang: 840028961
6. Falsch belegte Felder - vermutlich sind hier mehrere Sachen falsch: 
840014544 Requiem aeternam; Feld Textincipit: (bBEmineur2/4) "8D/C'B-G/FE-E/E'C-6C'A/4XF
ähnlich: 840029635, 840028364, 840024748, 840022439, 840030717
7. Vorzeichen sind reingerutscht: 840012875
8. Rolle ist reingerutscht: 840020330

**$r - Tonart**
Erwartung: Form entspricht Muscat (A, c, E|b, f|x)
Auswertung: Wir erstellen eine Übersetzungstabelle für  “G major”oder  “Mode de sol”. Aber außerdem: Bei einigen Datensätzen ist das Musikincipt reingerutscht. In der Importdatei sieht es auch nicht ganz sauber aus. Beispiel: 
840010618
KEY OR MODE | (4/4)2-,4G8-G/4G8EE4XC8-6EE/4A8GAFF-F/AA6-AAG4G4G4-/
Unimarc-Datei: 036 .. $a 01 $b 01 $c 03 **$g** (4/4)2-,4G8-G/4G8EE4XC8-6EE/4A8GAFF-F/AA6-AAG4G4G4-/ **$g** Fa majeur 
Das taucht 10x auf. Ich kann das nicht händisch korrigieren. Ich weiß nicht, wo ich die Noten einordnen soll. 

**$t - Textincipit**
Erwartung: Text
Auswertung: Überwiegend Text.
Lieder sind auch hier einige Incipits reingerutscht (7x): 
840031022:     ,2.D4D/2D4DD/BBBB/4.G8G2G

**Comment by jenniferward** [comment]
Auch scheinen manche Incipits falsch zu sein. Heute schon mehrmals vorgekommen.
 Beispiele:
https://muscat.rism.info/admin/sources/840024821
![image](https://user-images.githubusercontent.com/18663291/79569196-7c3d8b00-80b7-11ea-828f-36b05fb72ab0.png)

Der Schlüssel kommt nicht in der Originaldatei vor:
https://catalogue.bnf.fr/ark:/12148/cb39632674z.intermarc
![image](https://user-images.githubusercontent.com/18663291/79569282-a3945800-80b7-11ea-90ad-2e634ec765ab.png)

Digitalisat: 
https://gallica.bnf.fr/ark:/12148/btv1b55008433j/f22.item
![image](https://user-images.githubusercontent.com/18663291/79569324-b018b080-80b7-11ea-9808-8af7782bb35a.png)

Wenn ich den Schlüssel in F-4 ändere, sieht es schon mal besser aus:
![image](https://user-images.githubusercontent.com/18663291/79569483-f1a95b80-80b7-11ea-9ccf-f84b7f4744c3.png)

**Comment by KlausKeil** [comment]
Liebe Frau Ward, 
wie Sie bemerkt haben fehlen die Schlüssel in den Originaldaten. Deshalb haben wir G-2 ergänzt immer wenn kein Schlüssel da war. Es war klar, dass das auch schief gehen kann. 
Man könnte die Incipits danach kontrollieren, ob die Mehrzahl der Oktavzeichen unten stehen und dann den Schlüssel entsprechend ersetzen. Die Frage ist, ob der Aufwand sich lohnt. Sicherlich, die Grafik sieht nicht gut aus im OPAC. Aber wenn die Noten weitgehend stimmen - wie in Ihrem Beispiel, kann die Suche erfolgreich sein. 
Da wir die Daten bald im OPAC haben müssen, sollten wir Prioritäten setzen.

**Comment by jenniferward** [comment]
Alles klar, ich habe nicht gewusst, dass G-2 grundsätzlich ergänzt wurde.

Ich möchte wissen, wie wir mit den anderen Problemen (oben beschrieben) umgehen sollen.

**Comment by jenniferward** [comment]
Ich habe nach **G-2** mit **,,**   [2x Komma]  gesucht, einem Hinweis auf einen möglichen Bassschlüssel, und 209 Incipits gefunden. Die könnte man nach der Veröffentlichung in F-4 ändern, aber ich bin - wie oben beschrieben - sehr unsicher, ob die Incipits überhaupt korrekt sind, und es ist schwierig, das ganze zu beurteilen. 

2.200x habe ich Incipits mit G-2 und **,** [1x Komma] gefunden, was auch möglicherweise (aber nicht so stark wie ,, ) auf einen Bassschlüssel hindeuten könnte.
