### ISSUE TITLE
Fehler (?) beim Template-Wechsel

### ISSUE THREAD

**Issue by jenniferward** [rism-international/tasks#759]
Vor ca. zwei Wochen habe ich bei ein paar Titeln das Template geändert, damit die Drucke in den richtigen Templates sind. Hierbei ging es immer in Richtung Muskhandschrift --> Druck:
-Musikhandschrift, Haupteintrag Sammlung --> Musikdruck, Haupteintrag Sammlung
-Musikhandschrift, Individualeintrag --> Musikdruck, Teileintrag der Sammlung

Ich habe als Erstes den Haupteintrag geändert, dann die Individualeinträge. Der Haupteintrag Druck war ohne Probleme - Exemplareintrag automatisch ergänzt.
Erst jetzt sehe ich (durch den Muscat Health Report), dass sämtliche Teileinträge auch Exemplareinträge haben. Beim Template Musikdruck, Teileintrag der Sammlung sollen natürlich keine Exemplareinträgen erstellt werden. 

Beispiel: 
https://muscat.rism.info/admin/sources/1001017910 
Es handelt sich um 109 Titel. Siehe Anhang (copy und paste hat nicht funktioniert).

[Holdings_bei_Einzeleintraegen.docx](https://github.com/rism-international/tasks/files/4388569/Holdings_bei_Einzeleintraegen.docx)

**Comment by HirschSt** [comment]
Beim Wechsel des Templates von Handschrift zu Druck werden immer Holdings erstellt, fälschlicherweise auch bei Teileinträgen. Ich muss hier im Ablauf eine Ausnahme zufügen, um das zu umgehen. Die bisherigen Teileinträge mit Exemplareinträgen werden über ein Skript korrigiert.

**Comment by rism-international** [comment]
Im Opac werden die Fundorte anscheinend an die Teileinträge vererbt. In
Muscat sind sie nicht in den Teileinträgen. Ist das ein Fehler bei der BSB
oder geschieht das beim Datenexport?
Beispiel: 1001051109

Am Fr., 27. März 2020 um 09:07 Uhr schrieb Stephan Hirsch <
notifications@github.com>:

**Comment by jenniferward** [comment]
Ich kann die Frage nicht beanworten, aber diese Vererbung im OPAC ist einerseits sinnvoll, damit ein Nutzer, der nach ZimH 103/1 sucht, gleich den Fundort sieht, ohne extra klicken zu müssen. Wie bei den Handschriften: https://opac.rism.info/search?id=1001041377&View=rism

**Comment by jenniferward** [comment]
Hallo @HirschSt , oben hast du geschrieben: "Die bisherigen Teileinträge mit Exemplareinträgen werden über ein Skript korrigiert." Meinst du grundsätzlich alle, oder nur die 109, die in meiner Tabelle genannt sind? Ich habe inzwischen auch andere gefunden (aus dem CH-Import).

**Comment by HirschSt** [comment]
Alle

**Comment by jenniferward** [comment]
Einen Moment bitte, ich muss etwas mit CH klären.

**Comment by jenniferward** [comment]
Könntest du bitte CH-Titel von dem Skript ausschließen? Die CH-Titel, die überwiegend aus dem Import stammen, haben ihre eigenen Probleme, die in einem separaten Verfahren von den CH-Kollegen gelöst werden müssen.

**Comment by HirschSt** [comment]
CH wird ausgeschlossen; das Wartungsskript ist fertig, s. https://github.com/rism-international/muscat-maintenance/commit/b37797fcc07c1829b0929fd8a8d20e0c2efb213b
Fehlt noch die Ausnahme bei dem Templatewechsel direkt

**Comment by HirschSt** [comment]
Note für mich: https://github.com/rism-ch/muscat/blob/7d6d24826b964c6bfa9f8795c35c5ca06f1ac689/lib/template.rb#L30

**Comment by jenniferward** [comment]
Könntest du bitte das Wartungsskript noch einmal ausführen? Es gibt einige Hundert, die inzwischen durch den Templatewechsel erstellt wurden.  (Und wieder bitte CH ausschließen.)
Beispiel, Sammlung https://muscat.rism.info/admin/sources/350000042

**Comment by jenniferward** [comment]
Die CH-Ausnahme ist nicht mehr relevant; d.h., bitte alle betroffene Titel korrigieren.
