### ISSUE TITLE
Frankreich-Import: 300 $e?

### ISSUE THREAD

**Issue by jenniferward** [rism-international/tasks#760]
In den FR-Daten gibt es ein Feld 300 $e, das nicht in unseren MARC-Einstellungen vorkommt. Das Feld wird auch nicht in Muscat angezeigt, ist aber im XML vorhanden.
Inhaltlich eine Mischung aus 300 $a und 300 $c. Das Feld kommt 10x vor:
840012458	1 livret (14 p.)
840015517	1 partition des choeurs, pour un Domine salvum fac regem ([2] f., 31 x 23 cm)
840011214	114 parties
840016148	13 parties
840010693	21 parties instrumentales ; 30 x 23 cm
840016019	225 parties
840011953	5 parties (21 x 27 cm)
840010920	82 parties
840011086	82 parties ; 30,5 x 23,5 cm
840010718	livret ms. (16 f.) ; 23 x 18 cm

Wir werden diese Titel händisch korrigieren, aber eigentlich soll $e ganz aus den Daten gelöscht werden, oder?

**Comment by HirschSt** [comment]
Ja, ich lösche das Feld komplett aus den Daten

**Comment by HirschSt** [comment]
done with https://github.com/rism-international/muscat-maintenance/commit/8f15c6ddc81b4684f9ed492377395e240c28eef9
