### ISSUE TITLE
Personen: Bitte das Länderkürzel für Monaco ergänzen

### ISSUE THREAD

**Issue by alexandermarxen** [rism-international/tasks#761]
Bitte für die Personen das Länderkürzel für Monaco ergänzen XA-MC
Für mich: siehe: https://muscat.rism.info/admin/people/50041065

**Comment by HirschSt** [comment]
done with https://github.com/rism-ch/muscat/commit/dd14dfafa49b029c5f26e5e330313c8da600a219
