### ISSUE TITLE
D-Mbs: Digitalisat-Links zu Strauss und Pfitzner ergänzen

### ISSUE THREAD

**Issue by MFalletta** [rism-international/tasks#763]
Die BSB hat Links zu Digitalisaten von Strauss- und Pfitzner-Quellen zusammengestellt. Ich habe die Liste um die Felder 856 $z und 856 $x ergänzt.

[BSB_Pfitzner.xlsx](https://github.com/rism-international/tasks/files/4425641/BSB_Pfitzner.xlsx)
[BSB_Strauss-Richard.xlsx](https://github.com/rism-international/tasks/files/4425642/BSB_Strauss-Richard.xlsx)

**Comment by HirschSt** [comment]
done with https://github.com/rism-international/muscat-maintenance/commit/ecc593a70262b33392351f516df3100698af1c63
