### ISSUE TITLE
Frankreich-Import: | in 031$t löschen

### ISSUE THREAD

**Issue by jenniferward** [rism-international/tasks#768]
Das Pipe-Symbol | kommt manchmal im Feld 031$t vor. Da das Feld für Textincipits gedacht ist, kann das Zeichen grundsätzlich gelöscht werden in den Datensätzen, wo es vorkommt (in ca. 480 Datensätzen).

**Comment by HirschSt** [comment]
done with https://github.com/rism-international/muscat-maintenance/commit/f68f2c2c9050093c8e3a565c56404f5f613846ff
