### ISSUE TITLE
Frankreich-Import: Blank nach | in 245$a 

### ISSUE THREAD

**Issue by jenniferward** [rism-international/tasks#769]
Im Feld  245$a wird das Pipe-Symbol | in ca. 1.200 Datensätzen direkt gefolgt von einem Zeichen (a-z, A-Z, 0-9). 

Ich habe keine Beispiele gefunden, wo eine Hochstellung gemeint wäre (etwa in M|o oder M|m|e) . Es steht oft nach einem Artikel, aber nicht immer.

Beispiele:
840027166      Die \|Landlust
840028959     Effroi du pech[eur] \| au \| jugement dernier   \|psal. 67 \| Lalande
840011650      I \|nemici Generosi
840011651      I \|Nemici Generosi \| Opera in due Atti \| Del   Celebre Maestro Cimarosa
840015349     Cantique Spirituel \| Sur la naissance du   Sauveur. \| par Monsieur D'almayrac maitre \| de Musique de L'Eglise \|   Cathedrale de Rodez :\|1759

Ich schlage folgendes vor:
1) In 245$a, wo | nur 1x vorkommt: | löschen
2) In 245$a, wo | mehrmals vorkommt: Blank nach dem | einfügen

**Comment by Docudoctor** [comment]
Hallo Jennifer,
kannst Du bitte auch nach den Zeichen '| suchen?
Diese Kombi findet sich bei Titeln wie L'|Echange des roses.
In diesem Zusammenhang kann das Pipe herausgelöscht werden.

Danke,
Guido

**Comment by Docudoctor** [comment]
Hier noch ein hübsches Beispiel, wie Ausgangsdaten der BNF migriert wurden:
RISM ID 840010808, dipl. Titel bei der BNF: Eleuterio://Atto 2° // aria://Cherubini
Und bei uns (nicht korrigiert): Eleuterio:|Atto 2ʻ | aria:|Cherubini

**Comment by Docudoctor** [comment]
Noch ein Migrationsbeispiel:
Siehe RISM ID 840027287, dipl. Titel: Le | |Reveil-matin
Bei der BNF sieht das so aus: Le // Reveil-matin
Dies entspricht dem Original.

**Comment by Docudoctor** [comment]
Ein letztes Migrationsbeispiel, siehe RISM ID 840024057:
Der dipl. Titel sieht bei uns so aus: Les |Arts Florissans | Opera 
Bei der BNF aber so: Les Arts Florissans // Opera 
Im Digitalisat kann man das nachvollziehen.
Wie ist das Pipe vor Arts dazugekommen?

Schöne Grüße
Guido

**Comment by Docudoctor** [comment]
Das gilt auch beim dipl. Titel: L'|Olimpiade | Dramma per Musica | Original de Cafaro 
in der RISM ID 840010152.
Bei der BNF gibt es das Pipe zwischen L' und Olimpiade nicht.

**Comment by HirschSt** [comment]
> Wie ist das Pipe vor Arts dazugekommen?

Steht so in den gelieferten Daten, s.https://catalogue.bnf.fr/ark:/12148/cb396144734.intermarc

**Comment by Docudoctor** [comment]
> 
> 
> > Wie ist das Pipe vor Arts dazugekommen?
> 
> Steht so in den gelieferten Daten, s.https://catalogue.bnf.fr/ark:/12148/cb396144734.intermarc

Habe ich gerade gesehen. Zumindest in den Katalogeinträgen der BNF sieht das besser aus.

**Comment by jenniferward** [comment]
Hallo Guido,
danke für diese Überlegungen. Ich habe nach '| gesucht. Betroffen sind: 
Gl'|
Il'|
Nell'|
L'|

Die ersten drei Problemfälle habe ich händisch korrigiert, es waren nur 6 Titel. Ca. 175x gibt es dann L'| .

Ich schlage vor, dass bei **L'|** das | einfach verschwindet. @HirschSt  OK so?  

Ich glaube, wir müssen einfach damit leben, dass unsere 245 etwas von den der BNF abweichen.  L'| Echange (mit Blank) ist vielleicht unschön aber nicht unverständlich, während L' 
![image](https://user-images.githubusercontent.com/18663291/80200895-99c4a480-8623-11ea-8b8c-1f91f1a0359c.png)  ein technischer Fehler ist. 1.100 Titel mit den Originaldaten zu vergleichen scheint mir unpraktisch zu sein.

**Comment by HirschSt** [comment]
@jenniferward ist ok so
Bitte die Anweisungen für dieses Ticket nochmal präzise zusammenfassen, danke.

**Comment by jenniferward** [comment]
**Anweisungen:**
1) In 245$a, wo | nur 1x vorkommt: | löschen
2) In 245$a, wo | das 3. Zeichen in Zusammenhang mit **L'|**  ist : | löschen
3) In 245$a, wo | mehrmals vorkommt: Blank nach dem | einfügen

**Comment by KlausKeil** [comment]
zu 3. würde Blank vor und nach | einfügen, falls nicht vorhanden.

**Comment by HirschSt** [comment]
done with https://github.com/rism-international/muscat-maintenance/commit/32f0c805e636a03f9bbd379d94e622075f3140ad
