### ISSUE TITLE
Frankreich-Import: Falsche Werte in 240$k löschen

### ISSUE THREAD

**Issue by jenniferward** [rism-international/tasks#770]
Manchmal im Feld 240$k kommen Jahreszahlen vor, statt  Excerpts, Fragments oder Sketches.
Die Jahreszahlen sind in diesen Fällen nicht notwendig, weil die Angaben anderswo im Titel vorkommen.

In den folgenden Titeln:
https://docs.google.com/spreadsheets/d/1reoydFr4pdk4hx64FR0DlrYuUhDz79c5TO39rqshUuA/edit?usp=sharing
bitte die Angaben im Feld 240$k komplett löschen.

**Comment by HirschSt** [comment]
done with https://github.com/rism-international/muscat-maintenance/commits/master
