### ISSUE TITLE
Frankreich-Import: Falsche Werte in 240$k verschieben

### ISSUE THREAD

**Issue by jenniferward** [rism-international/tasks#771]
Im Feld 240$k kommen Jahreszahlen vor, die nicht anderswo im Titel auftauchen. Diese müssen wir beibehalten. 

Für folgende RISM-IDs bitte das Feld 240$k komplett nach 500 verschieben (d.h., 240$k ist dann anschließend leer) mit dem Vorsatz: 
Date:

Beispiel:
240$k 1619
500$a Date: 1619

https://docs.google.com/spreadsheets/d/16Az54OEuaOPGmyW19NL7CaU1BQiL_6CiBLcLdzep0uQ/edit?usp=sharing

**Comment by HirschSt** [comment]
In einigen Titeln der Liste wurde bereits $k manuell ergänzt bzw. korrigiert, d.h. hier die Werte zu verschieben wäre falsch, s. https://muscat.rism.info/admin/sources/840030322. Ich lasse das Skript daher nur bei solchen Titeln durchlaufen, die nicht bereits geändert wurden.

**Comment by jenniferward** [comment]
OK aber nur bei Titeln, wo $k noch nicht geändert wurde, oder? Ich habe schon Titel korrigiert aber $k gelassen, weil ich wusste, dass das Skript kommt.

**Comment by HirschSt** [comment]
Ja, aber andere Kollegen haben das Feld korrigiert. Der Abgleich mit der Versionshistorie ist sehr aufwendig, und die ursprüngliche Anforderung makulatur. Ich muss jetzt eine entsprechende Prüfung erstellen und vorschalten,  was zu Verzögerungen führt.

**Comment by MFalletta** [comment]
Es geht doch ausschließlich um Begriffe in $k, die aus Ziffern bestehen und verschoben werden sollen. Ist eine Prüfung überhaupt notwendig?

**Comment by HirschSt** [comment]
Ja, denn 1. stehen auch manchmal Text drin, der Datierungen beschreibt (nicht nur Zahlen), und 2. wurde manchmal $k richtig zu 'Excerpts' korrigiert. Ich mache die Prüfung jetzt in einfacher Form für diese Fälle.

**Comment by HirschSt** [comment]
done with https://github.com/rism-international/muscat-maintenance/commit/d952ed9a5268eab2eb4d7e510b079c28543ef855
