### ISSUE TITLE
Frankreich-Import: Übersetzungstabelle für die Tonarten in 240$r

### ISSUE THREAD

**Issue by jenniferward** [rism-international/tasks#772]
Viele Tonarten in 240$r entsprechen Muscat nicht. Siehe bitte diese Übersetzungstabelle:

https://docs.google.com/spreadsheets/d/18T5NYiGM_phj7WmuF3IeafuG-Cf7iMo00cjTM3mM4OQ/edit?usp=sharing

**Comment by jenniferward** [comment]
Siehe auch https://github.com/rism-ch/muscat/issues/890

**Comment by HirschSt** [comment]
done with https://github.com/rism-international/muscat-maintenance/commit/4c95ae2abbf96e6005bb3f2269af2d6c8dda44c1
