### ISSUE TITLE
Frankreich-Import: Übersetzungen für 300$a

### ISSUE THREAD

**Issue by jenniferward** [rism-international/tasks#773]
Im Feld 300$a sind viele Begriffe auf Französisch. Bitte in dieser Reihenfolge folgende Änderungen machen.
Es muss innerhalb des Feldes gesucht werden.

Begriff FR --> Änderin in
partition réduite → short score
partition en → score in
partitions → scores
partition → score
parties reliées → parts, bound
parties → parts
partie → part
Partie → part
et [ganzes Wort, am besten mit Blank vor und nach “et”] → and 
chacune → each
fasc. → fascicles
formats divers → Different sizes

**Comment by HirschSt** [comment]
done with https://github.com/rism-international/muscat-maintenance/commit/fe0249622f9b19b15a93d4661cbdee4a620f9f4e
