### ISSUE TITLE
Frankreich-Import: Übersetzungen für 300$c

### ISSUE THREAD

**Issue by jenniferward** [rism-international/tasks#774]
Im Feld 300$c, Format, sind viele Begriffe auf Französisch.
Bitte folgende Änderungen durchführen:

formats divers --> Different sizes
Formats multiples --> Multiple sizes
Formats différents --> Different sizes
et [ganzes Wort, am besten mit Blank vor und nach “et”] --> and

**Comment by HirschSt** [comment]
done with https://github.com/rism-international/muscat-maintenance/commit/e5db2023037c08960411af91f1a639fe2db8c6e4
