### ISSUE TITLE
Frankreich-Import: Übersetzungstabelle für 700$4 

### ISSUE THREAD

**Issue by jenniferward** [rism-international/tasks#777]
Einige Funktionen in  700$4 sind nicht in Muscat vorhanden und müssen geändert werden. Bitte folgende Übersetzungstabelle benutzen:

Import | Muscat
-- | --
adp  | arr
ann | oth
ant  | ccp
art  | ill
bnd  | oth
chr | oth
cnd | prf
cwt  | oth
dnc  | prf
dnr  | fmo
dto  | oth
ins  | oth
mus  | asn
nrt | oth
rcp | oth
sng  | prf

**Comment by HirschSt** [comment]
done with https://github.com/rism-international/muscat-maintenance/commit/28dda04e3aa610574db3651534ddfa15c20970cb
