### ISSUE TITLE
Frankreich-Import: bsl nach 710 verschieben

### ISSUE THREAD

**Issue by jenniferward** [rism-international/tasks#779]
bsl [Buchhändler] darf in Muscat nur bei den Institutionen vorkommen. 35x kommt bsl aber auch bei den Personen vor. Beispiel: 840017818.

Bitte die Namen mit bsl in 700 nach 710 verschieben.

**Comment by HirschSt** [comment]
done with https://github.com/rism-international/muscat-maintenance/commit/731ffae2c121ddbc3d8c9cdf95cbb921b4fa18e5
