### ISSUE TITLE
Frankreich-Import: Übersetzungstabelle für die Tonarten in 031$r

### ISSUE THREAD

**Issue by jenniferward** [rism-international/tasks#780]
Viele Tonarten in 031$r entsprechen Muscat nicht. Siehe bitte diese Übersetzungstabelle:

https://docs.google.com/spreadsheets/d/18fMHsmM5YdJtn8hEUw-B55q4l00xFkiebkhG0Q8bBZc/edit?usp=sharing

**Comment by HirschSt** [comment]
done with https://github.com/rism-international/muscat-maintenance/commit/24bd8f53601a4f8e525ca8848814fd5a4847bd19
