### ISSUE TITLE
Zeichenvorrat im Musikincipit

### ISSUE THREAD

**Issue by KlausKeil** [rism-international/tasks#781]
Töne:
CDEFGAB
Pause
-=
Oktavzeichen
',
Vorzeichen:
bxn
Rythmen:
1234567890. 
Taktstrich 
/:
Balkung / Sonderrhythmen
{}()+
Klammern nur paarweise 
Kleinstichnoten:
qgr
Akkorde
^
Besonderheiten: 
; nur in () 
Wechsel von Globalelementen
& gefolgt von Schlüsselangabe: G-[z], C-[z], F-[z], g-[z], G+[z], C+[z], F+[z]      z=1 bis 5
$ gefolgt von Tönen
@ gefolgt von Taktangaben wie c, c/, o, o/, 2/2, 3/2, 4/2, 3/4, 4/4, 6/4, 3/8, 6/8, 12/8

**Comment by jenniferward** [comment]
Die Musikincipits in 031$p weisen Fehler auf, die nicht durch den Zeichenvorrat entdeckt werden würden.

- Manchmal erscheinen die Vorzeichen im Feld Musikincipit. Beispiel:
https://muscat.rism.info/admin/sources/840012905 [schon korrigiert]
**bBEAD/**-16/4-8-"C/CD-r'B/rB"C-b'B/4Ag8E6AG/8AG



- Es gibt Incipits, wo ich vermute, dass etwas fehlt. zB. “29” oder “24” am Anfang [29-Takt Pause??] : 840024623, 840014878; “-13” am Anfang: 840028961


Auch mittendrin kommen Zahlen vor.
https://muscat.rism.info/admin/sources/840017000
: 8-/**32**/4-8-'G/''8D4D8G/xF4bE8D/gC'4B8A/6.B3C8D

**Comment by jenniferward** [comment]
Wird durch das Incipitprojekt erledigt.
