### ISSUE TITLE
Kommentare: Filterbox überdeckt Trefferliste

### ISSUE THREAD

**Issue by alexandermarxen** [rism-international/tasks#783]
Bei den Kommentaren überdeckt die Filterbox teilweise die Trefferliste. Dies ist nicht immer der Fall, möglicherweise nur, wenn das Feld "Inhalt" zu lang ist. Dadurch lassen sich die ersten Ergebnisse der Trefferliste nicht anzeigen.

![Comments_Muscat](https://user-images.githubusercontent.com/42838336/81786230-ae4bdc80-94ff-11ea-8dc9-465c6cc57b64.png)

**Comment by xhero** [comment]
This is a bug in Muscat, would you mind opening a ticket in the Muscat tracker?

**Comment by alexandermarxen** [comment]
Of course: https://github.com/rism-ch/muscat/issues/935
