### ISSUE TITLE
CS: 040 und 980 doppelt

### ISSUE THREAD

**Issue by MFalletta** [rism-international/tasks#785]
Daten sind ergänzt, aber doppelt und dreifach!
![CS 040 980 -2](https://user-images.githubusercontent.com/18736235/82226862-4fcf9580-9927-11ea-8ce8-fe2ffac542da.JPG)
![CS 040 980](https://user-images.githubusercontent.com/18736235/82226865-5100c280-9927-11ea-9dde-a2487f6c4364.JPG)

**Comment by HirschSt** [comment]
Sehr merkwürdig, im Testsystem wurde nur einfach ergänzt, kann also nicht am Wartungsskript liegen. Ich muss das nachprüfen.

**Comment by HirschSt** [comment]
done with https://github.com/rism-international/muscat-maintenance/commit/8f5321a04199c0a62407aec90c2072967eedf381
