### ISSUE TITLE
CS: 852 aus Teileinträgen der Drucke löschen

### ISSUE THREAD

**Issue by MFalletta** [rism-international/tasks#788]
Ich habe einen Ordner "Drucke Teileinträge Capp.Sist." mit allen Druck-Teileinträgen erstellt, aus denen 852 gelöscht werden soll, damit die Titel bearbeitet werden können.
https://muscat.rism.info/admin/folders/428

**Comment by HirschSt** [comment]
done with https://github.com/rism-international/muscat-maintenance/commit/190a4d526e770d73d50954fb8e4d6db4b53d5eb2
