### ISSUE TITLE
Personen: Länderkürzel für Guinea ergänzen

### ISSUE THREAD

**Issue by alexandermarxen** [rism-international/tasks#789]
Bitte bei den Personen das Länderkürzel für Guinea XC-GN ergänzen.

Für mich:
Siehe: https://muscat.rism.info/admin/people/30011895

**Comment by HirschSt** [comment]
done with https://github.com/rism-ch/muscat/commit/9f3165046bf9da60acdaa33bbfb2efa1a7db9844
