### ISSUE TITLE
Personen: Neuer Normdatenverweis

### ISSUE THREAD

**Issue by alexandermarxen** [rism-international/tasks#792]
Bitte in der Auswahlliste der Normdatenagenturen (024 $2) ORCID ergänzen.

ORCID bietet inzwischen persistente Identifier für über 8 Millionen Autoren an. Auch die DNB verwendet ORCID-Verweise in Feld 024: https://wiki.dnb.de/pages/viewpage.action?pageId=50759357&preview=%2F50759357%2F100664257%2F024.pdf

Um einen Link zu generieren, reicht die Adresse: https://orcid.org/
Die ID wird einfach angehängt.
Beispiel: https://orcid.org/0000-0003-3832-5399

**Comment by HirschSt** [comment]
done with https://github.com/rism-ch/muscat/commit/4b9041d196e6629b3805582b9556b03cc135c2e1

Den Link in Muscat muss durch eine spezielle Helper-Funktion generiert werden, die ich später noch einfügen kann
