### ISSUE TITLE
Personen - Feld 700$c (ICCU)

### ISSUE THREAD

**Issue by alexandermarxen** [rism-international/tasks#795]
Beim ICCU-Import wurde auch das Feld 700$c geliefert, das in Muscat nicht vorhanden ist. Da wir die Informationen aus diesem Feld im Feld 680 (Personen) übertragen haben, könnten sie aus den Quellen-Daten gelöscht werden.
Beispiel:
https://muscat.rism.info/admin/sources/850686187.xml

Gilt dies auch für die Körperschaften, also Feld 710$c, bzw. 852$x?

**Comment by HirschSt** [comment]
done with https://github.com/rism-international/muscat-maintenance/commit/b6c92a2e7a7855d1c1d5cd89b3d22d261efcded3

**Comment by jenniferward** [comment]
Nur zur Klarheit: wurde nur 700$c bearbeitet, oder auch 710$c, bzw. 852$x (siehe Frage von Alexander oben)?

**Comment by HirschSt** [comment]
Nur 700$c wurde auch zu den Personen transferiert, wenn ich das richtig verstanden habe. Die anderen Normdaten wurden nicht analog umgesetzt und benötigen daher dann eine andere Vorgehensweise.

**Comment by jenniferward** [comment]
Was brauchst du dann von uns?
