### ISSUE TITLE
D-F: Digitalisat-Links ergänzen

### ISSUE THREAD

**Issue by MFalletta** [rism-international/tasks#796]
Frau Kersting-Meuleman hat eine Liste mit ca. 950 Digitalisat-Links zusammengestellt.
Die Liste steht unter 
https://docs.google.com/spreadsheets/d/1dsJ0YU9-3Iz5iZljsV-MTQTsbomBzrYMvMfUt0MOYso/edit#gid=1164715803

Die Spalten A und B können ignoriert werden. 
Da aber früher einige Links bereits händisch ergänzt wurden, sollte überprüft werden, ob 856 leer bzw. noch nicht belegt ist (als Quellendigitalisat).

**Comment by MFalletta** [comment]
Da 856 $u mit "http" beginnen muss: bitte Vorsatz http://nbn-resolving.de/ ergänzen

**Comment by HirschSt** [comment]
Neue Tabelle erhalten (2020.09.29)

**Comment by HirschSt** [comment]
done with https://github.com/rism-international/muscat-maintenance/commit/2ba03ae57e6ccb2db252711f12be4a2312c1db22
