### ISSUE TITLE
787 als Verlinkungsfeld für in Beziehung stehende Quellen

### ISSUE THREAD

**Issue by MFalletta** [rism-international/tasks#799]
Dafür sind zwei Subfields notwendig.
$i Information zur Beziehung [Dropdown-Liste]
$w RISM ID [Autocomplete/verlinken]

Feldbezeichnungen:
Related RISM entry / Bezug zu RISM-Eintrag
Type of relationship / Art der Beziehung
RISM ID no. / RISM ID no.

Außerdem wird das Feld in den Block "References and notes" verschoben, zwischen 691 (Bibliopraphic reference) und 510 (RISM Series)

**Comment by MFalletta** [comment]
siehe auch #794

**Comment by jenniferward** [comment]
Es dauert wohl laenger, bis die Kollegen das Feld 787 aufraeumen.

**Comment by jenniferward** [comment]
Das Subfeld $w ist momentan belegt (manchmal falsch, manchmal mit anderen RISM-IDs).

**Comment by jenniferward** [comment]
Weiteres Subfeld:
$n: Bemerkung / Note

Validierung: Alle Subfelder müssen ausgefüllt werden.

Liste für Art der Beziehung:
- Parallelquelle/Konkordanzen
- Abschrift von einem Druck
- Veröffentlicht in einem Druck
- Weiteres Material
- Weitere Version
- Kontrafakta
- Choralbearbeitung

**Comment by MFalletta** [comment]
Feld und relator codes sind vorhanden
