### ISSUE TITLE
ICCU: Übersetzungstabelle Tonarten 240$r

### ISSUE THREAD

**Issue by jenniferward** [rism-international/tasks#800]
Für die unpublizierten Datensätzen aus dem ICCU-Import bitte folgende Übersetzungstabelle benutzen für das Feld 240$r (Tonarten):

Import ICCU | Muscat
-- | --
Ax | A\|x
Ab | A\|b
Bb | B\|b
cx | c\|x
Db | d\|b
Eb | E\|b
fx | f\|x
gx | g\|x
Gb | G\|b
1 | 1t
2 | 2t
3 | 3t
4 | 4t
5 | 5t
6 | 6t
7 | 7t
8 | 8t

**Comment by HirschSt** [comment]
done with https://github.com/rism-international/muscat-maintenance/commit/eb62109609ac51eaea627b0b50018cc44f22ba95
