### ISSUE TITLE
ICCU: Bitte leere 700$4 entfernen

### ISSUE THREAD

**Issue by jenniferward** [rism-international/tasks#801]
Bei den unveröffentlichten ICCU-Daten:
Im Feld 700$4 ist das Feld manchmal in Muscat "vorhanden"aber komplett leer. 
Leere $4 müssen entfernt werden. 
Beispiel: https://muscat.rism.info/admin/sources/850734277/edit

**Comment by HirschSt** [comment]
analog zu #813 würde ich sf $4oth ergänzen, statt die Felder zu entfernen

**Comment by HirschSt** [comment]
done with https://github.com/rism-international/muscat-maintenance/commit/c389ca718f3f1aac49c5a2859db08853d4d1a050
