### ISSUE TITLE
ICCU: 041$a abs löschen

### ISSUE THREAD

**Issue by jenniferward** [rism-international/tasks#802]
Bei den unveröffentlichten ICCU-Daten:
Wenn 041$a = abs , bitte abs löschen.

(siehe auch https://github.com/rism-international/iccu/issues/3 )

**Comment by HirschSt** [comment]
done with https://github.com/rism-international/muscat-maintenance/commit/41551e8c3273f29352ce49d5a23f4089c09f6842
