### ISSUE TITLE
ICCU: Übersetzungstabelle 700$4 Funktionen

### ISSUE THREAD

**Issue by jenniferward** [rism-international/tasks#803]
Für die unveröffentlichten ICCU-Daten, bitte folgende Funktionen in 700$4 ändern:

Import | Muscat
-- | --
adp | arr
hnr | dte
art | ill
ann
ant; aus; chr; cll; cnd; com; dnr; drt; dto; mte; pro; rcp; rev; spn | oth
sng | prf

**Comment by HirschSt** [comment]
done with https://github.com/rism-international/muscat-maintenance/commit/4603c3ebdbc6883c8e124add087de4e0a473e375
