### ISSUE TITLE
ICCU: Übersetzungstabelle Funktionen 710$4

### ISSUE THREAD

**Issue by jenniferward** [rism-international/tasks#804]
Bei den unveröffentlichten ICCU-Daten, bitte folgende Funktionen bei den Institutionen (710$4)  ändern:

Import ICCU | Muscat
-- | --
dnr | fmo
bnd; dto; egr; fnd; ill; ltg; spn; tyg; lyr | oth

**Comment by HirschSt** [comment]
done with https://github.com/rism-international/muscat-maintenance/commit/84b1744d9dd41569208194cdd2d67a55700f33ab
