### ISSUE TITLE
ICCU: 599$b "abbreviated"

### ISSUE THREAD

**Issue by jenniferward** [rism-international/tasks#805]
Bei den ICCU-Daten sehe ich in der MARC21-Datei in Feld 599$b abbreviated. Beispiel:
https://muscat.rism.info/admin/sources/850685527.xml

Meine Fragen: Gehört das nicht im Feld 980$b (wird ja nicht im Bearbeitungsmodus angezeigt), und soll das nicht "brief' heißen?

**Comment by HirschSt** [comment]
Auch dieses Feld wird autogeneriert, s. https://github.com/rism-ch/muscat/blob/7ee6d2e30f4973101483734311af536ba30c91b4/lib/marc_source.rb#L503; die Bezeichnungen stammen aus https://github.com/rism-ch/muscat/blob/8dcefb67ee434f8f52a5762641f97ee8803eefd8/app/models/source.rb#L105
