### ISSUE TITLE
ICCU: DE-633 in 040$a

### ISSUE THREAD

**Issue by jenniferward** [rism-international/tasks#806]
Laut MARC-Einstellungen ist 040$a [unspecified]. In den ICCU-Daten ist das Feld manchmal (ca. 150x in meinen Daten) mit "DE-633' belegt. Ich wollte nachfragen, ob das so bleiben kann oder ob es besser gelöscht werden soll.

**Comment by HirschSt** [comment]
Auch dieses Feld wird autogeneriert, s. https://github.com/rism-ch/muscat/blob/8dcefb67ee434f8f52a5762641f97ee8803eefd8/lib/marc_source.rb#L434. Das Feld sollte eigentlich immer belegt sein, in dem Code scheint ein Fehler zu stecken (das Feld wird nicht belegt, wenn 040 bereits vorhanden ist). Muß ich noch prüfen.

**Comment by HirschSt** [comment]
fixing missing 040$a s. https://github.com/rism-ch/muscat/commit/9ea0fc361f4a47d8bdf20368075f1ae6a084e20a
