### ISSUE TITLE
ICCU: 040$b Katalogisierungssprache

### ISSUE THREAD

**Issue by jenniferward** [rism-international/tasks#807]
In meinen Daten aus dem ICCU-Import ist 040$b 43x doppelt vorhanden. In 44 Titeln fehlt das $b komplett. 
Es soll doch überall 1x vorhanden und "ita" sein, oder?

**Comment by MFalletta** [comment]
1x reicht!

Einen ähnlichen Fall hatten wir bei Cappella Sistina, siehe #785

**Comment by HirschSt** [comment]
done with https://github.com/rism-international/muscat-maintenance/commit/b140160cfc35a267e274f30f1c85d6e27175f215
