### ISSUE TITLE
ICCU: 240$n löschen

### ISSUE THREAD

**Issue by jenniferward** [rism-international/tasks#808]
Bei den ICCU-Daten kommt das Feld 240$n vor, was nicht in Muscat vorhanden ist. Die Angaben wiederholen die Angaben in 690 oder 383. 240$n kann von daher aus den Daten gelöscht werden, oder?

**Comment by HirschSt** [comment]
Ja, das subfield kann gelöscht werden.
Kannst Du mir bitte einen Beispieltitel nennen? Bei meiner Suche nach 240$n bekomme ich kein Ergebnis.

**Comment by HirschSt** [comment]
Ich musste zunächst etwas recherchieren: Die Angaben in 240$n werden automatisch generiert und stehen so nicht in den Daten, das WV wird als Teil des Einordungstitels im OPAC (und auch sonstwo benötigt), s. https://github.com/rism-ch/muscat/blob/8dcefb67ee434f8f52a5762641f97ee8803eefd8/lib/marc_source.rb#L464
