### ISSUE TITLE
ICCU: 245$a manchmal doppelt vorhanden

### ISSUE THREAD

**Issue by jenniferward** [rism-international/tasks#809]
In den ICCU-Daten kommt das Subfeld $a in 245 manchmal mehrmals vor. Beispiel:
https://muscat.rism.info/admin/sources/850809033
Können die $a in einem Feld kombiniert werden, oder nach 246$a verschoben werden?

**Comment by HirschSt** [comment]
werden jetzt in einem sf kombiniert, s. https://github.com/rism-international/muscat-maintenance/commit/29b997d6fea9fba18f1ebe928589b360ca08ebf0
