### ISSUE TITLE
ICCU: Blank nach und vor | in 245$a

### ISSUE THREAD

**Issue by jenniferward** [rism-international/tasks#810]
Wie beim FR-Import (#769) kommt es manchmal in Feld 245$a vor, dass | nicht klar durch ein Blank getrennt ist.

Ich habe nicht den Eindruck, dass z.B. M.|o benutzt wird wie bei uns. (Findet jemand Gegenbeispiele?)
Beispiele:
850657528 Litania della B.V.M.|del M.tro|Oreste Gardini
850669469 Cantata|del|Maestro Nicola de Giosa|Eseguito
850689371 P. Emmanuele da Catelvecchio|o.f.m.|Ninna Nonna a|Gesu' Bambino

Es wäre besser, ein Blank vor und nach dem | hinzuzufügen, wenn es fehlt.

**Comment by alexandermarxen** [comment]
Bei den ICCU-Titeln muss man natürlich etwas vorsichtig sein, da sie von Bibliothek zu Bibliothek sehr unterschiedlich sind, aber ich glaube auch nicht, dass das Pipe-Symbol für Hochstellungen benutzt wurde. In sehr vielen Titeln sind die Blanks auch vorhanden.
https://muscat.rism.info/admin/sources/850757776
In diesem Fall ist wahrscheinlich das o in "libro 2.o" hochgestellt. Ich vermute, dass Hochstellungen grundsätzlich nicht markiert wurden.

**Comment by KlausKeil** [comment]
Definitiv kommt | nicht für Hochstellung vor. Es kommt aber vor zur Abtrennung von Artikel und Substantiv. Ich finde jetzt aber kein Beispiel.

**Comment by HirschSt** [comment]
done with https://github.com/rism-international/muscat-maintenance/commit/e3388b7ac7702d8b70627228c602d6a4be1fe4bc
