### ISSUE TITLE
ICCU: 594$a löschen?

### ISSUE THREAD

**Issue by jenniferward** [rism-international/tasks#811]
Bei den unveröffentlichten ICCU-Daten:
Das Feld 594$a ist in den Daten vorhanden, wobei $a nicht in Muscat ist. 
Die Daten in $a scheinen die Daten in 594$b und 594$c zu duplizieren. Soll 594$a in den Daten bleiben?

Beispiele
850696456
=594  \\$bvl$c3
=594  \\$bvla$c1
=594  \\$bvlc$c1
=594  \\$avl (3), vla, vlc

850811070
=594  \\$bCoro T$c2
=594  \\$bCoro B$c1
=594  \\$bvl$c2
=594  \\$bvla$c1
=594  \\$bvlc$c1
=594  \\$bvlne$c1
=594  \\$bob$c2
=594  \\$bfag$c1
=594  \\$bcor$c2
=594  \\$aCoro T (2), Coro B, vl (2), vla, vlc, vlne, ob (2), fag, cor (2)

**Comment by HirschSt** [comment]
Auch hier handelt es sich um ein autogeneriertes Feld, s. https://github.com/rism-ch/muscat/blob/8dcefb67ee434f8f52a5762641f97ee8803eefd8/lib/marc_source.rb#L449
