### ISSUE TITLE
ICCU select 128$b and 128$c as list with RISM-ID

### ISSUE THREAD

**Issue by HirschSt** [rism-international/tasks#812]

**Comment by jenniferward** [comment]
Manchmal (?) auch vielleicht 928 $b und $c? Siehe z.B. Unimarc-Datei zu http://id.sbn.it/bid/LO11691789

**Comment by HirschSt** [comment]
done with 128, see https://raw.githubusercontent.com/rism-international/import/master/data/ICCU/input/128.csv

**Comment by jenniferward** [comment]
@HirschSt Sind die Besetzungen auch im Feld 928 $b und $c zu finden? Mein Beispiel http://id.sbn.it/bid/LO11691789 befindet sich nicht in der Liste.
