### ISSUE TITLE
ICCU: 700 ohne $4

### ISSUE THREAD

**Issue by jenniferward** [rism-international/tasks#813]
Bei den unveröffentlichten ICCU-Daten:
Einige Personen in 700 haben kein $4. Diese sollen oth bekommen.

In meinem Teilbestand geht es um ca. 130 Titel. Möglicherweise sind andere Titel (aus dem anderen Teil) auch betroffen.

**Comment by HirschSt** [comment]
Inwieweit korreliert das mit #801 ?

**Comment by jenniferward** [comment]
Hoffentlich gar nicht. Die betroffenen Titel aus #801 haben - so weit ich es gesehen habe - immer 1x belegtes $4 und 1x "Unbelegt":
![image](https://user-images.githubusercontent.com/18663291/90617853-7d222d00-e20f-11ea-834c-a66cbacb5326.png)


Vielleicht hat jemand Gegenbeispiele gefunden?

Das heißt, solche Titel (#801) würden nicht durch dieses Verfahren auftauchen.

Soll  sicherheitshalber #801 zunächst ausgeführt werden, dann anschließend #813?

**Comment by HirschSt** [comment]
Beide issues werden mit einem Skript eingefangen: wenn kein $4 oder nur ein leeres $4, wird mir $4oth ergänzt. Wenn weitere $4, die leer sind, existieren, werden diese gelöscht

done with https://github.com/rism-international/muscat-maintenance/commit/c389ca718f3f1aac49c5a2859db08853d4d1a050
