### ISSUE TITLE
Sistina: 730 löschen

### ISSUE THREAD

**Issue by jenniferward** [rism-international/tasks#817]
Bei diesem Ordner: https://muscat.rism.info/admin/folders/429
soll das Feld 730 komplett gelöscht werden.

**Comment by Docudoctor** [comment]
Okay. Wurde alles geprüft?
Guido


Am Do., 9. Juli 2020 um 19:21 Uhr schrieb Jennifer Ward <
notifications@github.com>:

**Comment by HirschSt** [comment]
done with https://github.com/rism-international/muscat-maintenance/commit/eff9fcdcfa2aa7d5ff36be925c55a29fa801b9a9
