### ISSUE TITLE
Sistina: Neue Schlagworte

### ISSUE THREAD

**Issue by jenniferward** [rism-international/tasks#818]
Diese Tabelle enthält neue Schlagworte (650$a). Sie sollen die bereits vorhandenen komplett ersetzen.

https://docs.google.com/spreadsheets/d/1MPojShTi5fVnVJdrxbzm0ZlnMLIGWu21wcU9HvlRPMU/edit#gid=490535250

(X, Cappella Sistina, 2020 06 03 Daten, Titel mit 730)

Dabei ist zu beachten, dass 650 manchmal mehrfach belegt ist und mit ; getrennt.

**Comment by Docudoctor** [comment]
Gut.
Guido

Am Do., 9. Juli 2020 um 19:26 Uhr schrieb Jennifer Ward <
notifications@github.com>:

**Comment by HirschSt** [comment]
done with https://github.com/rism-international/muscat-maintenance/commit/692fec4af0c6091b7c1dddacce344c8ad6fcfec5
