### ISSUE TITLE
856 $x mit Linktyp=Quellendigitalisat auszeichnen

### ISSUE THREAD

**Issue by jenniferward** [rism-international/tasks#819]
Siehe #497
Einige Digitalisate wurden nicht berücksichtigt - rund 10.000.

Beispiele:

https://muscat.rism.info/admin/sources/993103784  [digitized version]

https://muscat.rism.info/admin/sources/990059797 [digitized version]

Im Prinzip die Titel, wo folgendes irgendwo in 856$z vorkommt:

- digitized
- Digitized
- digital
- Digital
- Digitisation
- Manuscriptorium

("Manuscriptorium" ist neu.)

Ich vermute, dass sowohl Exemplare als auch Handschriften betroffen sind.

**Comment by HirschSt** [comment]
see #951

**Comment by jenniferward** [comment]
Duplicate of #951
