### ISSUE TITLE
Change Pipe character in references to broken bar '¦'

### ISSUE THREAD

**Issue by HirschSt** [rism-international/tasks#826]
- [x] 510$a (no items)
- [x] 510$c
- [x] 500$a
- [x] 245$a (no items after some additional checks)

eg. 1542¦5

**Comment by jenniferward** [comment]
Unsere Kollegen waren zum Teil sehr fleißig und haben das | Symbol mehrfach innerhalb der Nummer verwendet, z.B.
1609|0|1    https://muscat.rism.info/admin/sources/1001035844
1591|0|8  https://muscat.rism.info/admin/sources/1001035853
1554|1|0  https://muscat.rism.info/admin/sources/190013139

Auch mit Minuszeichen, Komma und Schrägstrich kommt vor.
