### ISSUE TITLE
ICCU: Einfügen von 128c in 500 

### ISSUE THREAD

**Issue by HirschSt** [rism-international/tasks#828]
s. auch #812

**Comment by jenniferward** [comment]
Bitte unbedingt diese Tabelle benutzen!
Das Feld 128$c ist leider nicht ganz sauber. Angaben zum Besetzungshinweis sind in sowohl 128$b als auch 128$c zu finden. Beispiele: 

850779884 | IT\ICCU\MSM\0257763 | 1str,orchar | cb-solo,vl1,vl2,vla,vlc,b
850779885 | IT\ICCU\MSM\0257764 | 2str,orch | cb-solo,vl-solo,ott,fl,ob1,ob2,cl1,cl2,fag1,fag2,cor1,cor2,cor3,cor4,tr1,tr2,trb1,trb2,trb3,bombne,vl1,vl2,vla,vlc,cb,timp
850772399 | IT\ICCU\MSM\0169847 | S,vl1,vl2,fl,cl1,cl2,cor1,cor2,tr1,tr2,fag,trb,b | 1V,orch |  
850772585 | IT\ICCU\MSM\0170307 | >V,vl1,vl2,vla,cl1,cl2,fag1,fag2,cor1,cor2,vlc,cb | >V,orch |  

Ich habe die Tabelle komplett überarbeitet und die Angaben sind nun im richtigen Feld: 128$b entspricht unserem 240$m und die Angaben sind jetzt RISM-konform; 128$c ist als zusätzliche Bemerkung (500$a) einzufügen.

Außerdem habe ich Zeichen wie > oder $ oder % gelöscht und ein Blank zwischen den Instrumenten eingefügt.

- Bitte 240$m komplett überschreiben, auch wenn eine Angabe schon vorhanden ist. Dabei ist zu beachten, dass mehrere Besetzungsangaben durch ; getrennt sind und für mehrere $m bestimmt sind.
- Bitte 500$a dann einfügen.

[128_bearbeitet.xlsx](https://github.com/rism-international/tasks/files/5035190/128_bearbeitet.xlsx)

**Comment by HirschSt** [comment]
done with https://github.com/rism-international/muscat-maintenance/commit/2766b7f5066dba9b22da2a9526befedb7c1a08f7
