### ISSUE TITLE
ICCU: Einzeleinträge ohne 593

### ISSUE THREAD

**Issue by jenniferward** [rism-international/tasks#833]
In den ICCU-Daten (in meinem Teilbestand) gibt es 55.000 Titel ohne Materialbeschreibung. Ich vermute, es handelt sich um Einzeleinträge. 
Beispiele:
https://muscat.rism.info/admin/sources/850812693
https://muscat.rism.info/admin/sources/850812213
 
Falls der Collectioneintrag eine Angabe zum Quellentyp hat, kann diese Angabe auch in die Einzeleinträge kommen?

**Comment by jenniferward** [comment]
Als zweiter Schritt sollen die angehängten Titel 593$a = Manuscript copy bekommen, falls das Feld nicht anderweitig belegt ist. 
[ohne_593.xlsx](https://github.com/rism-international/tasks/files/5034989/ohne_593.xlsx)

**Comment by HirschSt** [comment]
done with https://github.com/rism-international/muscat-maintenance/commit/af32e502db4fdb39bb7a9a70cf3bfb05e95c6033

**Comment by jenniferward** [comment]
Hallo Stephan, siehe bitte meine Tabelle oben "Als zweiter Schritt sollen die angehängten Titel 593$a = Manuscript copy bekommen, falls das Feld nicht anderweitig belegt ist."
Die Tabelle wurde nicht (komplett??) übernommen. 
Beispiele: 850603483 und 850779394
593 soll mit Manuscript copy belegt werden. Diese Angabe muss noch nachmigriert werden.
