### ISSUE TITLE
ICCU: Instrumente aus 928$b und 928$c 

### ISSUE THREAD

**Issue by jenniferward** [rism-international/tasks#835]
Siehe #812, dort handelt es sich um 24.000 Titel (aus 217.000), was mir ein bisschen wenig vorkommt.  
In 928$b und 928$c befinden sich auch Instrumentenangaben.
Beispiel: http://id.sbn.it/bid/LO11691789 
928 $ats# $b3str$cvl,vla,vlc$zIT\ICCU\CMP\0335036

Könnest du bitte eine Liste erstellen mit RISM-ID, 928$b und 928$c?

**Comment by HirschSt** [comment]
Liste steht unter https://raw.githubusercontent.com/rism-international/import/master/data/ICCU/input/928.csv

**Comment by jenniferward** [comment]
Danke, übernehme ich, analog zu #812 und #828
