### ISSUE TITLE
ICCU: zusätzliche Bemerkungen einfügen (500)

### ISSUE THREAD

**Issue by jenniferward** [rism-international/tasks#836]
In dieser Tabelle habe ich eine Spalte mit zusätzlichen Bemerkungen (aus verschiedenen Feldern), die das Feld 500$a ergänzen sollen. Nicht überspielen - einfach einfügen bitte. 

Einige Bemerkungen sind durch ; getrennt und sind als mehrere Bemerkungen zu betrachten.

[500_zusaetzlicheBemerkung.xlsx](https://github.com/rism-international/tasks/files/5034863/500_zusaetzlicheBemerkung.xlsx)

**Comment by HirschSt** [comment]
done with https://github.com/rism-international/muscat-maintenance/commit/643c59d5682e24fcc5ba91cd5ce58543221ae9c6
