### ISSUE TITLE
240$k und 240$o ersetzen

### ISSUE THREAD

**Issue by jenniferward** [rism-international/tasks#840]
Wie in der Sitzung besprochen:
Ich habe das Feld 240$k überarbeitet und nach Excerpts - Sketches - Fragments kontrolliert. Die richtigen Angaben sind in der Tabelle. Dabei ist manchmal auch das Feld $o zu ergänzen bzw. ersetzen. Bitte die angegebenen Felder komplett ersetzen.

[240k_bearbeitet.xlsx](https://github.com/rism-international/tasks/files/5104022/240k_bearbeitet.xlsx)

**Comment by HirschSt** [comment]
done with https://github.com/rism-international/muscat-maintenance/commit/05786459ab7135b976584e07c81609a1be146a70
