### ISSUE TITLE
Neue Exemplare GB-Lbl

### ISSUE THREAD

**Issue by jenniferward** [rism-international/tasks#841]
Ich habe eine Tabelle mit ca. 1.100 neuen Exemplaren aus GB-Lbl bekommen.

[wird überarbeitet]

**Comment by jenniferward** [comment]
Wie ist der Stand? Die Kollegen in GB-Lbl haben nachgefragt, wann die Exemplare im OPAC erscheinen werden.

**Comment by jenniferward** [comment]
Hallo Stephan, sorry, dass ich nachhake: hast du eine Vorstellung, wann die Exemplare importiert werden können? Was kann ich der Bibliothek sagen?

**Comment by HirschSt** [comment]
Wurde auf der ZR-Sitzung am 21.3.2022 erneut thematisiert

**Comment by jenniferward** [comment]
Entschuldigung, das habe ich verschwitzt. Da es insgesamt drei verschiedene Facetten des Projekts gibt (wie am 07.03. erklärt), erstelle ich insgesamt 3 Tickets.

Hier die Tabelle für die neuen Exemplare (561 an der Zahl). Bitte immer ein neues Exemplar erstellen mit:

- 852$a
- 852$c
- 500$a (manchmal mehrfach vorhanden)
- 856$u
- 856$x
- 856$z

Zur Info: Manchmal sind mehrere Exemplare nachgewiesen (mit derselben Nummer im Feld 001). Jedes Exemplar hat eine eigene Zeile.
[01-neue-exemplare.xlsx](https://github.com/rism-international/tasks/files/8324983/01-neue-exemplare.xlsx)

**Comment by HirschSt** [comment]
done with https://github.com/rism-international/muscat-maintenance/commit/98501e102187d48a76243f7c8041bb1f4ff4a094, @jenniferward bitte prüfen und Rückmeldung geben

**Comment by jenniferward** [comment]
Vielen Dank! 
Ich habe die Angaben in der Tabelle mit einigen Titeln auf beta verglichen. Alle Angaben waren vorhanden.

Grünes Licht von mir.
