### ISSUE TITLE
ICCU: Taktart falsch geschrieben (Teil 2)

### ISSUE THREAD

**Issue by jenniferward** [rism-international/tasks#847]
(Vortsetzung von #608 )

Taktart ist manchmal falsch geschrieben: 

850786580: c\ statt c/

**Comment by jenniferward** [comment]
Martina: Brauchen wir "sm" in den Daten (ohne Metrum??) https://muscat.rism.info/admin/sources/850669143

**Comment by MFalletta** [comment]
"sm" (sine metrum) macht keinen Sinn, zu mal in dem genannten Beispiel Taktstriche eingetragen wurden

"sm" kann gelöscht werden

**Comment by jenniferward** [comment]
Bei den ICCU-Daten, im Feld 031 $o, bitte:
c\ in c/ ändern
sm löschen

**Comment by jenniferward** [comment]
Ich glaube, das wird durch das Incipitprojekt erledigt.
