### ISSUE TITLE
Körperschaften, MARC-Feld 110 $g, Rechte der Katalogisierer 

### ISSUE THREAD

**Issue by Docudoctor** [rism-international/tasks#849]
Bitte die Rechte der Katalogisierer am MARC-Feld Sigel (110 $g) in der Datei Körperschaften zurücknehmen, sowohl im Erstellen-Modus, als auch im Bearbeiten-Modus.  
Alle Editoren sollen ihre Rechte an diesem Feld behalten. Nur Editoren sollen die Möglichkeit haben, neue Sigel zu erstellen, oder gegebenenfalls zu korrigieren. 
Gruß,
Guido

**Comment by HirschSt** [comment]
AFAIK gibt es bisher in Muscat in Marc21-Objekten noch keine Möglichkeit, Rechte auf Feldebene zu beschränken, ich lasse mich aber gerne eines besseren belehren. 
Grundsätzlich aber wäre das schon machbar, wäre ein neues Feature für Muscat 7

**Comment by BaMikusi** [comment]
Wenn die Sache etwas komplizierter ist, bin ich mir nicht sicher, ob das eine Priorität sein soll. Katalogisierer können ja vieles falsch machen, was wir auch durch genauere Guidelines zu vorbeugen hoffen, anstatt Ihre Rechte ganz ausführlich zu manipulieren. Wenn es auch andere Felder gibt, mit denen wir ähnlich vorgehen möchten, wäre die Ausarbeitung dieser Option natürlich schon wirtschaftlicher (wobei ich als Laie annehme, dass die Vorgehensweise für verschieden Felder grundsätzlich ähnlich sein könnte).

**Comment by Docudoctor** [comment]
Stimmt genau. Stephan klärt noch ab, ob es doch möglich ist, Rechte auf Feldebene zu beschränken. Falls nicht, freut sich die RISM IT vielleicht über eine harte Nuss zum Knacken. ;-)

**Comment by HirschSt** [comment]
@Docudoctor Nicht unbedingt!

**Comment by jenniferward** [comment]
Vielleicht relevant? Die Katalogisierer können das Feld "Besitzer des Eintrags" (Aktion für Eintrag) nicht ändern, auch das Feld RISM Dokumentnummer (001) (Administration) ist beim Erstellen ausgegraut und beim Editieren nicht editierbar. Andere Felder, die man nicht bearbeiten kann, hängen mit den Normdaten zusammen (in Quellen), z.B. Geburts- und Todesdaten (100$d) und "Bibliothek" (852$e).

**Comment by jenniferward** [comment]
Siehe auch https://github.com/rism-ch/muscat/issues/989

**Comment by HirschSt** [comment]
@jenniferward leider nein, denn 1. sind die genannten Administrationsfelder keine Marc-Felder, und 2. 100$d etc. sind Verlinkungsfelder, die automatisch bei der Verknüpfung ausgefüllt werden

**Comment by HirschSt** [comment]
Wir können das wieder aufnehmen, wenn grundsätzlich der deutliche Wunsch besteht, die Editiermöglichkeit verschiedener Marc-Felder über die Rechteverwaltung zu steuern.
