### ISSUE TITLE
Digitalisate aus B-Br für 856

### ISSUE THREAD

**Issue by jenniferward** [rism-international/tasks#870]
Ich habe eine Tabelle von Links aus B-Br, die importiert werden sollen (856). Siehe Tabelle.

[Vieuxtemps_KBRdigitizedsources_bearbeitet.xlsx](https://github.com/rism-international/tasks/files/5298765/Vieuxtemps_KBRdigitizedsources_bearbeitet.xlsx)

**Comment by HirschSt** [comment]
done with https://github.com/rism-international/muscat-maintenance/commit/edeadf6bf8165a06907e1ae05f9bb523c8914908

Zur Info: In der Tabelle werden die Links sowohl bei dem Sammeleintrag als auch nochmal zusätzlich in den Einzeleinträgen eingetragen, s. 700011099. Das ist vielleicht nicht optimal.

**Comment by jenniferward** [comment]
Ja, das weiß ich. Wir haben nichts in den Richtlinien, das dafür oder dagegen spräche. Sollen wir das vielleicht am Montag diskutieren?

**Comment by BaMikusi** [comment]
Meinetwegen sehr gerne.
