### ISSUE TITLE
Sigeldatenbank: Suche nach Städtenamen mit 2+ Wörtern

### ISSUE THREAD

**Issue by jenniferward** [rism-international/tasks#885]
Ein Bug
Städtenamen, die aus mehr als 1 Wort bestehen, werden nicht gefunden: Die Datenbank tut nichts.
Feld City
Beispiele: Tel Aviv, Bad Homburg vor der Höhe, Studley Royal

**Comment by jenniferward** [comment]
Auch im Feld Country: South Africa

**Comment by HirschSt** [comment]
Gut gesehen! Ich prüfe das.

**Comment by HirschSt** [comment]
fixed with https://github.com/rism-international/sigla-catalog/commit/a0738a7a2ee8541fa5219adcdbf2495b9179943e
