### ISSUE TITLE
Sigeldatenbank: Country undefined

### ISSUE THREAD

**Issue by jenniferward** [rism-international/tasks#886]
Bei einigen Sigeln habe ich zufällig "Country: undefined" gefunden:
E-CCRc
E-LCm
BOL-SUbn

![image](https://user-images.githubusercontent.com/18663291/95442465-b481a000-095b-11eb-9ec5-3381e693d4b1.png)

**Comment by HirschSt** [comment]
Danke, ja. Wahrscheinlich ist bei diesen Sigeln das Land 043 falsch belegt, so auch im Beispieltitel, s. https://muscat.rism.info/admin/institutions/30079641/edit

**Comment by HirschSt** [comment]
Das müsste in den Daten bereingt werden

**Comment by HirschSt** [comment]
done with https://github.com/rism-international/sigla-catalog/commit/d9e7df4917d6d197f1808e41b80dfef49fc1d46c
