### ISSUE TITLE
Sigeldatenbank: Sigel in Klammern

### ISSUE THREAD

**Issue by jenniferward** [rism-international/tasks#887]
Ich frage mich, ob die Sigel in Klammern gesetzt werden müssen? Schließlich stehen die Sigel im Mittelpunkt.

![image](https://user-images.githubusercontent.com/18663291/95445949-f280c300-095f-11eb-892f-8324e50c1656.png)

**Comment by HirschSt** [comment]
In der alten Sigeldatenbank war es genauso, aber ich habe das jetzt geändert, done with https://github.com/rism-international/sigla-catalog/commit/337524d1fe54b178df9114463d04a1ac79e12351
