### ISSUE TITLE
Sigeldatenbank: Sonderzeichen ignorieren

### ISSUE THREAD

**Issue by jenniferward** [rism-international/tasks#888]
Können Sonderzeichen ignoriert werden, wie in der aktuellen Datenbank?
Beispiele:
Düsseldorf
Liège
universitatsbibliothek

**Comment by HirschSt** [comment]
Das Verhalten entspricht dem von Muscat, aber ich kann prüfen, inwiefern das geändert werden kann

**Comment by HirschSt** [comment]
soll über rism-online umgesetzt werden.
