### ISSUE TITLE
Sigeldatenbank: Library siglum (klein geschrieben)

### ISSUE THREAD

**Issue by jenniferward** [rism-international/tasks#889]
Nur eine Kleinigkeit, und nur wenn die Änderung einfach ist: In der Indexsuche, kann "Library Siglum" als "Library siglum" (also mit kleinem "s") geschrieben werden?

![image](https://user-images.githubusercontent.com/18663291/95449219-bdc33a80-0964-11eb-985e-b1dd09260940.png)

**Comment by HirschSt** [comment]
Ja, ist geändert, s. https://github.com/rism-international/sigla-catalog/commit/919d573b5dc5c9f2976ba175f460b5ecf5b9a78a
