### ISSUE TITLE
Check helptext of sigla catalog

### ISSUE THREAD

**Issue by HirschSt** [rism-international/tasks#890]

**Comment by BaMikusi** [comment]
Wenn es hier um den Text geht, der über das Suchfeld steht, wäre es hier gut zu beschreiben
(1) was das gelbe Sternchen bei den Ergebnissen bedeutet, und
(2) dass man Länder (so weit ich sehe) nur auf Englisch oder Deutsch eintragen kann (nicht aber auf der jeweiligen Muttersprache oder Französisch)

**Comment by jenniferward** [comment]
Ja, (1) muss noch übertragen werden, was gemeint ist, steht hier http://www.rism.info/de/rism-bibliothekssigel.html . Die Formatierung machen wir in den nächsten Wochen, glaube ich. 

Bei (2): Bisher (http://www.rism.info/en/sigla/help.html) hieß es, Englisch soll im Feld Country eingegeben werden. Vielleicht kann Stephan überprüfen, ob das noch stimmt. Ich finde z.B. 1.715 Sigel für "Germany" aber 1.713 für "Deutschland".

**Comment by HirschSt** [comment]
@BaMikusi zu (2): es werden alle Begriffe berücksichtigt, die in Muscat eingetragen sind, z.B. s. https://github.com/rism-ch/muscat/blob/4b150a68f9380d3472ca75da7931ff8180f12a07/config/editor_profiles/default/configurations/InstitutionLabels.yml#L1068 (pl wurde noch nicht berücksichtigt, da erst später hinzugefügt). Hier fehlen noch viele Übersetzungen, nur die deutschen hatte ich nachgetragen.

**Comment by BaMikusi** [comment]
Obige Liste finde ich etwas verwirrend insofern, dass für viele Länder das Feld "label: de:" die Englische Fassung wiederholt: z.B. South Africa, Russian Federation, Slovakia, Latvia usw. Es gibt auch kuriose Mischformen wie Slovenien (das wäre m.E. nur auf Schwedisch richtig). Längerfristig wäre hier vielleicht eine drop-down Liste die beste Lösung -- dann könnte der Nutzer nur solche Schreibweisen eintragen, die in der Datenbank tatsächlich vorhanden sind.

**Comment by jenniferward** [comment]
Einfachheitshalber schreibe ich dann im Hilfetext, dass man die Ländernamen in EN oder DE eingeben kann. 

Die Ländernamen werden nur nach und nach von unseren Übersetzern ergänzt.

**Comment by HirschSt** [comment]
Die Liste sollte in jedem Fall überarbeitet werden. Gut wäre hierfür, externe Datenquellen wir wikidata (z.B. https://www.wikidata.org/wiki/Q889) zu nutzen. Es gibt für Rails auch mindestens eine eigene Bibliothek dazu, s. https://github.com/hexorx/countries
Ich glaube deswegen nicht, dass man hier in jedem Fall Übersetzer bemühen muss.
Ein Autocomplete anzubieten wäre gut, aber hierfür müsste in Muscat noch einiges angepasst werden (u.a. die Rechteverwaltung). 
Für diese Anforderungen sollten eigene Issues erstellt werden.

**Comment by HirschSt** [comment]
https://github.com/rism-international/tasks/issues/891

**Comment by BaMikusi** [comment]
Ob händisch oder automatisiert, die Liste sollte korrigiert werden, und wenn die Namen schon in Ordnung sind, wäre es eine schöne Geste, die Suche für alle Muscat-Sprachen anzubieten.

Auch fällt es mir ein, dass man auf der Startseite des OPACs sofort (als eine Art Werbung) sehen kann, wie viele Quellen usw. da recherchierbar sind. Wäre es zu kompliziert, so etwas auch für diese Sigelsuche zu entwickeln? Ich glaube, dass die meisten Nutzer keine Ahnung über die Menge der schon vorhandenen Sigel haben, und der Umfang des RISM-Projekts könnte auf diese Weise auch sehr gut veranschaulicht werden.

**Comment by HirschSt** [comment]
Sollte möglich sein, es sind aktuell 8.407

**Comment by xhero** [comment]
Just chiming in to say, the list in InstitutionLabels.yml is an internal component of Muscat and used for the interface translations, cleaning it up is part of te global translation project we discussed yesterday.

**Comment by HirschSt** [comment]
@xhero 100% correct, thanks for this reminder

**Comment by jenniferward** [comment]
@HirschSt Könntest du uns bitte deine Änderungswünsche am Hilfetext bis spätestens Mitte nächster Woche mitteilen?

**Comment by jenniferward** [comment]
@HirschSt Ich möchte im Januar eine News über die Sigelsuche schreiben, doch zwei Punkte sind für mich (und vermutlich für die Nutzer) noch unklar:

https://rism.info/community/sigla/help.html

1) Im EN steht (bath.corporateName) (rism.librarySiglum) (rism.place) (rism.libraryCountry) aber nicht im DE. Sind diese Begriffe notwendig? Und falls ja, wie sind sie für die Nutzer oder die Suche relevant?

2) Kombinierte Suche: Ich verstehe nicht, warum "USA" funktioniert aber nicht "US" (die eigentliche Abkürzung bei uns). Gibt es andere abweichende Abkürzungen oder ist das die Ausnahme?

**Comment by HirschSt** [comment]
1. die Begriffe sind notwendig, weil Sie die Index-Felder bezeichnen
2. die Länderabkürzungen werden anhand der country-codes in Muscat gebildet, s. https://github.com/rism-ch/muscat/blob/91f3677d1ca37ce1ec5b1bfbce4732ada2d3b89c/config/locales/marc_records/de.yml#L213; hier steht "USA", aber nicht US

**Comment by jenniferward** [comment]
1. Das mag aus technischer sicht notwendig sein, aber aus Nutzersicht verstehe ich das wirklich nicht.  Der Nutzer liest:
The fields Name, Library siglum, City, and Country can be selected and searched in the drop-down menu. Please note the following:
Name: The official name or alternative names of the institution in the local language **(bath.corporateName)**
usw.
Wie soll er **(bath.corporateName)** verstehen? Ich würde das gerne löschen - oder kannst du mir bitte sagen, wie diese Begriffe für die Nutzer relevant sind?

2. Wie können wir das für die Nutzer auf verständlicher Weise formulieren?
RISM-Sigel: US
Länderbezeichnung im Sigeleintrag: Country: USA
Muscat: usa
Suche: country=USA

Aber:

RISM-Sigel: RUS
Länderbezeichnung im Sigeleintrag: Country: Russia
Muscat: russian_federation
Suche: country=Russia funktioniert nicht, aber country=Russian Federation schon.

Wie erklären wir das dem Nutzer? Ich würde gerne den Hinweis auf den Suchparameter **country=** löschen, sonst führt das nur zu Frust.

**Comment by HirschSt** [comment]
1. wenn man kombiniert suchen möchte, muss man den richtigen Index auswählen - das geht vielleicht auch noch eleganter, aber nicht in kurzer Zeit
2. in der Suche nach Ländern werden nur Begriffe gesucht, die in Muscat stehen. Ich nehme an, "Russia" steht nicht in den Übersetzungen, vielleicht irre ich mich aber

**Comment by HirschSt** [comment]
Russia* funktioniert

**Comment by jenniferward** [comment]
2. Ich passe das für die Nutzer an, aber das ist doch sehr umständlich, vor allem falls neue Ländernamen kommen. Wie sie im Sigeleintrag angezeigt werden, soll doch suchbar sein, ohne Umwege.

**Comment by HirschSt** [comment]
wird über rism-online umgesetzt
