### ISSUE TITLE
Sigeldatenbank: Ergänze Button mit Funktion Clear search / Zurücksetzen

### ISSUE THREAD

**Issue by Docudoctor** [rism-international/tasks#892]
Danke. Guido

**Comment by HirschSt** [comment]
![image](https://user-images.githubusercontent.com/6461776/98908356-94944d80-24c0-11eb-8632-34507b8f2a4a.png)

**Comment by HirschSt** [comment]
done with https://github.com/rism-international/sigla-catalog/commit/81a1ee9748a4870f8d80cda1605bd030983f2ef3
