### ISSUE TITLE
Datenauszug Feld Ländercode (043), Datei Körperschaften

### ISSUE THREAD

**Issue by Docudoctor** [rism-international/tasks#893]
Zur Verbesserung der Ausgangsdaten für die Publikation der RISM-Sigel in der Sigeldatenbank benötige ich einen vollständigen Auszug der Belegung im Feld Ländercode (043) der Körperschaftendatei.

Danke,
Guido

**Comment by HirschSt** [comment]
list at https://raw.githubusercontent.com/rism-international/muscat-maintenance/master/report/2020-11-02_countries.csv

done with https://github.com/rism-international/muscat-maintenance/commits/master
