### ISSUE TITLE
Personendatenbank

### ISSUE THREAD

**Issue by alexandermarxen** [rism-international/tasks#898]
Analog zum "Online-Verzeichnis der RISM-Bibliothekssigel" sollten wir auch eine Personen-Datenbank anbieten.
Ideen für eine Umsetzung:

Suche
Einfache Suche / Erweiterte Suche (analog zur Suchmaske in Muscat)
Suche nach:
- Name (inkl. Namensvarianten)
- Lebensdaten
- Geschlecht
- Beruf/Funktion
- Nationalität
- Ort (vielleicht mit Indikatoren Geburtsort etc.)
- Orden

Trefferliste (sortierbar)
Darstellung analog zu Muscat, aber ohne Status und Besitzer (ID?; vielleicht interessant zum Sortieren nach neu angelegten Personen)
Vielleicht auch Suchfilter, z.B. zur Eingrenzung der Lebensdaten.

Anzeige
Analog zu Muscat, ohne das Feld 667
Zusätzlich: Verlinkung zum OPAC

Grundsatzfrage:
Sollen  Personen, die noch auf "unpublished" stehen, trotzdem veröffentlicht werden?
Zur Zeit wäre es kein so großes Problem; direkt nach Daten-Importen wären aber mitunter sehr viele Dubletten vorhanden!

**Comment by alexandermarxen** [comment]
Die Personendatenbank gehört im Prinzip ja schon zum Angebot von rism.online. Die Frage wäre, ob wir analog zur Sigelsuche, dennoch ein solches Angebot auf unserer Webseite veröffentlichen wollen. Das hätte zumindest den Vorteil, dass die Normdaten stärker als ein Angebot der Zentralredaktion wahrgenommen werden.

**Comment by BaMikusi** [comment]
Das ist ein größeres Thema, das wir am besten in der nächsten Redaktionssitzung besprechen sollten.

**Comment by HirschSt** [comment]
Da es offensichtlich nicht möglich ist, hier einfach eine Entscheidung zu fällen, ohne X und Y um gnädige Erlaubnis zu bitten, fällt das Projekt flach - was schade ist, weil der eigentlich Dumme die quelleninteressierte Öffentlichkeit ist. Es ist nicht das erste Mal, dass der Entscheidungsspielraum der ZR so geschmälert wird. Meinen Ärger darüber habe ich hoffentlich klar genug zum Ausdruck gebracht.
