### ISSUE TITLE
Sigeldatenbank: Publikation der Sigeleinträge wie unten beschrieben

### ISSUE THREAD

**Issue by Docudoctor** [rism-international/tasks#899]
Display der Sigeleinträge in der Sigeldatenbank

Folgende MARC-Felder aus den Körperschaftseinträgen sollen in dieser Reihenfolge mit folgenden Feldbezeichnungen publiziert werden analog zu den Anforderungen an die BSB zum RISM OPAC:

- [x] 1) RISM-Sigel: (110 $g)
- [x] 2) Land: (043)
- [x] 3) Ort: (110 $c)
- [x] 4) Körperschaft: (110 $a)
- [x] 5) Andere Körperschaftsnamen: (410)
- [x] 6) Typ der Körperschaft: (368 $a)
- [x] 7) Heute in: (580 $0 und $x) [​als Link​]
- [x] 8) Adresse: (371 $a, e, b, c, d, m, u, z)
- [x] 9) Geodaten: (034 $f [Breitengrad], $d [Längengrad]) [Google maps (eingebunden)]
- [x] 10) Literatur [​als Link​]: (670 $0, a, b)
- [x] 11) Geschichte der Körperschaft: (678 $a)
- [x] 12) Anmerkungen: (680 $a)
- [x] 13) Externer Link: (856 $u, z)
- [x] 14) In Beziehung stehende Körperschaft [​als Link​]: (710 $0, a)
- [x] 15) Person [​als Link​] und ihre Funktion: (700 $0, a, d, e, t, 4, 5)
- [x] 16) Normdatenverweise [​als Link​]: (024 $a und 024 $2)

Besten Dank.
Guido

**Comment by Docudoctor** [comment]
Ist dringend!!

**Comment by HirschSt** [comment]
Wird nur in der neuen Sigelsuche umgesetzt. Was von diesen Feldern wie umgesetzt werden kann, muss ich zuerst noch prüfen.

**Comment by HirschSt** [comment]
done with https://github.com/rism-international/sigla-catalog/commit/cd19418f1501fcda84b139632f14da789840b487
