### ISSUE TITLE
Datei Körperschaften. Feld Länder-Code (043): Ergänze fehlende Länder 

### ISSUE THREAD

**Issue by Docudoctor** [rism-international/tasks#905]
Bitte ergänze folgende Länder:
1) Andorra (ISO-Code 3166-1: XA-AD)
2) Indonesia (ISO-Code 3166-1: XB-ID) 
3) Northern Ireland (ISO-Code 3166-2: XA-GB-NIR) 
4) Monaco (ISO-Code 3166-1: XA-MC)
5) Philippines (ISO-Code 3166-1: XB-PH)
6) Saudi Arabia (ISO-Code 3166-1: XB-SA)
7) Hong Kong (ISO-Code 3166-1: XB-HK)
8) Taiwan (ISO-Code 3166-2: XB-TW) 
9) Papua New Guinea (ISO-Code 3166-1: XE-PG)

Danke,
Guido

**Comment by HirschSt** [comment]
will be checked by AH
