### ISSUE TITLE
Ergänze unvollständige Ländercodes (043) in Körperschaftseinträgen

### ISSUE THREAD

**Issue by Docudoctor** [rism-international/tasks#906]
Siehe die geteilte Google-Tabelle. 
Gruß, Guido

**Comment by HirschSt** [comment]
Unvollständiger Ländercode | Korrigiere in:
-- | --
AD | XA-AD
AT | XA-AT
BE | XA-BE
CZ | XA-CZ
DE | XA-DE
ES | XA-ES
F | XA-FR
FR | XA-FR
GB | XA-GB
HK | XB-HK
ID | XB-ID
IRLN | XA-GB-NIR
IT | XA-IT
MC | XA-MC
PH | XB-PH
PL | XA-PL
PT | XA-PT
RC | XB-TW
SA | XB-SA
US | XD-US

**Comment by HirschSt** [comment]
done with https://github.com/rism-international/muscat-maintenance/commit/4736058c100f4c1809b08f100eb3386ee1a64823
