### ISSUE TITLE
Sigelkatalog: Mouseover-Text

### ISSUE THREAD

**Issue by jenniferward** [rism-international/tasks#915]
Könntest du bitte den Mouseover-Text im Sigelkatalog am aktuellen Namen des Katalogs anpassen?
![image](https://user-images.githubusercontent.com/18663291/102480911-3b8c7c00-4061-11eb-9b96-16b1e0cacd9a.png)

See sources in RISM Catalog of Musical Sources

**Comment by jenniferward** [comment]
Auch hier:
![image](https://user-images.githubusercontent.com/18663291/102482031-e487a680-4062-11eb-80da-5104211e832f.png)

This institution has sources in the RISM Catalog of Musical Sources

**Comment by HirschSt** [comment]
soll über rism-online umgesetzt werden
