### ISSUE TITLE
Sigel-OPAC, neue Webseite, Trennen mehrerer URL

### ISSUE THREAD

**Issue by Docudoctor** [rism-international/tasks#916]
Hallo Stephan,
siehe PL-WRu.
Hier sind zwei URL angegeben, die im neuen Sigel-OPAC nicht getrennt verarbeitet werden. Das führt nach dem Anklicken zu keinem Ergebnis.
Gruß,
Guido

**Comment by HirschSt** [comment]
soll über rism-online umgesetzt werden
