### ISSUE TITLE
Sigel-OPAC, neue Webseite, Statusänderung in Muscat

### ISSUE THREAD

**Issue by Docudoctor** [rism-international/tasks#917]
Hallo Stephan,
wird der Status eines Sigeleintrags in Muscat auf "Unpublished" gesetzt, bleibt der Eintrag im Sigel-OPAC weiterhin such-und sichtbar. 
Dieses bitte ändern. 
Danke,
Guido

**Comment by BaMikusi** [comment]
Ich nehme an, das wird sich erst nach dem nächsten Update der Datenbank auf der Webseite ändern, oder? Dann aber wahrscheinlich ohne weitere Eingreifen.

**Comment by DadimoPflege** [comment]
Bitte ein Beispiel nennen, danke!

**Comment by Docudoctor** [comment]
Beispiel D-Mlbk

**Comment by HirschSt** [comment]
soll über rism-online umgesetzt werden
