### ISSUE TITLE
Sigel-OPAC, neue Webseite, Normdatenverweise ohne Verlinkung

### ISSUE THREAD

**Issue by Docudoctor** [rism-international/tasks#919]
Hallo Stephan,
bitte verlinke alle Normdatenverweise.

Schönen Dank.
Guido

NB: Soweit ich es bisher gesehen habe, funktioniert die Verlinkung im Augenblick nur zur DNB.

**Comment by jenniferward** [comment]
Beispiel in #930 :-)

**Comment by HirschSt** [comment]
soll über rism-online umgesetzt werden
