### ISSUE TITLE
Sigel-OPAC, neue Webseite, Feld Parallele Namensformen (510) wird nicht publiziert

### ISSUE THREAD

**Issue by Docudoctor** [rism-international/tasks#920]
Hallo Stephan,
bitte publiziere das Feld Parallele Namensformen (510). 
Setze es in den Sigeleinträgen eine Zeile direkt über den Einträgen des Feldes Andere Namensformen (410).

Danke,
Guido

**Comment by HirschSt** [comment]
soll über rism-online umgesetzt werden
