### ISSUE TITLE
Sigel-OPAC, neue Webseite, Verlinkung zwischen Einträgen innerhalb des Sigel-OPACs 

### ISSUE THREAD

**Issue by Docudoctor** [rism-international/tasks#922]
Hallo Stephan,
siehe das Beispiel D-DO im Sigel-OPAC.
Zeile "Now in:" Die Verlinkung nach D-KA führt leider zum RISM OPAC der BSB. 
Bitte richte Verlinkungen innerhalb des Sigel-OPACs zwischen den Einträgen ein.
Das gilt für die MARC-Felder Heute in (580) und für In Beziehung stehende Körperschaft (710). 

Danke,
Guido

**Comment by HirschSt** [comment]
soll über rism-online umgesetzt werden
