### ISSUE TITLE
Sigel-OPAC, neue Webseite, Ländersuche verbessern

### ISSUE THREAD

**Issue by Docudoctor** [rism-international/tasks#924]
Hallo Stephan,
zur Verbesserung der Ländersuche im Sigel-OPAC bitte folgende Ländernamen in den Ausgangsdaten von Muscat ändern (in der englischen, deutschen, französischen und italienischen Version; MARC-Feld Ländercode 043):

Russian Federation in Russia
Russische Föderation in Russland
Fédération russe in Russie
Federazione Russa in Russia

Holy See in Vatican City State
Heilige Stuhl in Vatikan
Saint-Siège in Vatican
Santa Sede in Vaticano

Die Ländernamen "Ägypten", "Österreich", "Tschechische Republik", "Vereinigtes Königreich", "États-Unis d'Amérique" führen bei der Suche leider zu keinem befriedigenden Ergebnis. 

Schönen Dank.
Guido

**Comment by jenniferward** [comment]
Nur "Vatican City" auf EN, bitte.

**Comment by HirschSt** [comment]
soll über rism-online umgesetzt werden
