### ISSUE TITLE
Sigel-OPAC, neue Webseite, Stichwortsuche verbessern

### ISSUE THREAD

**Issue by Docudoctor** [rism-international/tasks#925]
Hallo Stephan,
in die Stichwortsuche bitte noch die Einträge in den MARC-Feldern Andere Namensformen (410) und Parallele Namensformen (510) integrieren sowie die Einträge aus Geschichte der Körperschaft (678).

Danke,
Guido

**Comment by HirschSt** [comment]
soll über rism-online umgesetzt werden
