### ISSUE TITLE
Sigel-OPAC, neue Webseite, Boolescher Operator NOT funktioniert nicht

### ISSUE THREAD

**Issue by Docudoctor** [rism-international/tasks#927]
Hallo Stephan,
beim Booleschen Operator NOT bleibt die Suche "kalt". 
Es funktionieren AND sowie OR. 
Bitte in die Suche integrieren.
Beispiel: "Biblioteca NOT Archivio" in Namenssuche oder Stichwortsuche

Danke,
Guido

**Comment by HirschSt** [comment]
soll über rism-online umgesetzt werden
