### ISSUE TITLE
Sigelsuche: Normdaten verlinken

### ISSUE THREAD

**Issue by jenniferward** [rism-international/tasks#930]
Beispiel: D-DO
Ich sehe: Authority Reference: ISIL: DE-50; VIAF: 168671893; DNB: 4623149-3 ; DNB: 4623151-1 ; DNB: 5050100-8 

ISIL und VIAF werden nicht verlinkt, die drei DNB-Nummern verlinken nach http://d-nb.info/gnd/ . 

@ Guido : Sollen nicht alle Normdaten verlinkt werden?

**Comment by jenniferward** [comment]
Entschuldigung, doppelt!

**Comment by Docudoctor** [comment]
Soweit man aufsetzen kann. ISIL macht keinen Sinn. Aber VIAF und andere Datenbanken mit IDs.

**Comment by Docudoctor** [comment]
Jupp. :)
