### ISSUE TITLE
Sigel OPAC, neue Webseite, publiziere MARC-Feld 110 $b

### ISSUE THREAD

**Issue by Docudoctor** [rism-international/tasks#931]
Lieber Stephan,
publiziere das Feld 110 $b "Subordinate unit". 
Platziere es zwischen 110 $a, $c und 110 $g in einer eigenen Zeile im grau unterlegten Streifen, in schwarz, nicht fett.
Beachte, das Feld 110 $b ist verdoppelbar. 
Bsp.: I-Fammf

Besten Dank
Guido

**Comment by HirschSt** [comment]
soll über rism-online umgesetzt werden
