### ISSUE TITLE
Sigel-OPAC, Suche mit Leerzeichen

### ISSUE THREAD

**Issue by jenniferward** [rism-international/tasks#935]
Wäre es möglich, dass die Suche auch Leerzeichen am Ende einer Suchanfrage ignoriert? Manchmal kopiert man den Institutionsnamen aus dem Internet und ein Leerzeichen wird mit kopiert - dann findet die Suche nichts.
Beispiel: "Universitätsbibliothek Johann" (ohne Anführungszeichen) findet 3 Treffer
"Universitätsbibliothek Johann " (ohne Anführungszeichen, mit Leerzeichen nach dem letzten Wort) findet nichts.

**Comment by HirschSt** [comment]
soll über rism-online umgesetzt werden
