### ISSUE TITLE
Digitalisate US-Su ergänzen

### ISSUE THREAD

**Issue by jenniferward** [rism-international/tasks#938]
Anbei eine Liste mit Digitalisaten zum Eränzen bei US-Su. Es handelt sich um Drucke. Der Exemplareintrag ist schon in Muscat. Es müssen lediglich 856 $u, $x und $z ergänzt werden.

[US_Su_Import.xlsx](https://github.com/rism-international/tasks/files/6559817/US_Su_Import.xlsx)

**Comment by HirschSt** [comment]
done with https://github.com/rism-international/muscat-maintenance/commit/c6cf06bddf7a816bab8900efaba7c49cca26b790
