### ISSUE TITLE
Templatewechsel bitte (Collections mit Incipits)

### ISSUE THREAD

**Issue by jenniferward** [rism-international/tasks#940]
In der Tabelle gibt es 176 RISM-IDs, die aus Collections mit 031 bestehen (ohne Einzeleinträge). Ich glaube, die Titel können ohne Datenverlust in Handschriften (MSR) konvertiert werden. Das geht bestimmt schneller mit einem Skript, ist das machbar?
[COL-MSR_mit_031.xlsx](https://github.com/rism-international/tasks/files/6771569/COL-MSR_mit_031.xlsx)

**Comment by HirschSt** [comment]
Das kann gemacht werden, bei den Titeln muss allerdings dann nachträglich noch der Komponist ergänzt werden. Bitte auf beta anhand https://github.com/rism-international/muscat-maintenance/blob/master/log/20230612_coll_incipit.log kurzfristig prüfen.

**Comment by jenniferward** [comment]
Stichprobenartig sieht das richtig aus. Ich ergänze die Komponistennamen nachdem der Skript gelaufen ist. Wann wird das ungefähr sein?

**Comment by HirschSt** [comment]
Das ist jetzt durchgelaufen
