### ISSUE TITLE
ausgeschiedene "Besitzer" - Kommentare

### ISSUE THREAD

**Issue by MFalletta** [rism-international/tasks#945]
Bitte Kommentare an diese Personen an jemand anderen weiterleiten oder Kommentarfunktion abstellen ???

Miquela Döppenschmidt
Nina Eichholz
Angelo Fusacchia
Andrea Ickstadt
Björn Kessler
Daniel Kneer
Charlotte Köhler
Chantal Köppl
Carmen Rosenthal
Ulrike Schädel
Jasmin Seib
Johanna Thöne
Vivian Tompkins
Daniela Wissemann

**Comment by Docudoctor** [comment]
Katarína Pečenkárová
Adriana Grešová
Andrej Šuba

**Comment by Docudoctor** [comment]
Jakub Strużyński
Tomasz Jeż

**Comment by Docudoctor** [comment]
Jędrzej Mróz
Aleksandra Wróblewska

**Comment by HirschSt** [comment]
Die Nutzer sind jetzt auf inaktiv gesetzt, Kommentare werden an muscat-comments@rism.info weitergeleitet.
