### ISSUE TITLE
Sigel-OPAC: Autocomplete

### ISSUE THREAD

**Issue by jenniferward** [rism-international/tasks#946]
Im Sigelkatalog sollen die Groß- und Kleinschreibung bis auf die Sigel nicht berücksichtigt werden.
Beispiel: las palmas findet nichts
Las Palmas findet 9 Treffer.

@ Guido ok?

**Comment by Docudoctor** [comment]
Las Palmas funktioniert bei mir klein und groß geschrieben. 
Sigeleingabe nach Norm, ja. 
Generell wäre mir eine Autocompletefunktion sehr lieb.

**Comment by jenniferward** [comment]
Ach, heute funktioniert es. Komisch. 
Ich formuliere das Ticket um.

**Comment by HirschSt** [comment]
soll über rism-online umgesetzt werden
