### ISSUE TITLE
Digitalisate aus US-Wc: Tabelle

### ISSUE THREAD

**Issue by jenniferward** [rism-international/tasks#948]
Anbei eine Tabelle mit ca. 1.400 Links zu Digitalisaten aus US-Wc für das Import in Muscat. Es handelt sich um Handschriften, die bisher keine Digitalisate hatten.

[US-Wc_Digitalisate.xlsx](https://github.com/rism-international/tasks/files/7538987/US-Wc_Digitalisate.xlsx)

**Comment by HirschSt** [comment]
done with https://github.com/rism-international/muscat-maintenance/commit/ea1d0767c648ce4ecbf96350cd033bc88dab282f
