### ISSUE TITLE
PiKaDo-Import: abgehackte 245

### ISSUE THREAD

**Issue by jenniferward** [rism-international/tasks#950]
Guido und ich bitten darum, uns PiKaDo-Dateien mit Titeln zur Verfügung zu stellen, bei denen das 245 möglicherweise bei der Migration abgehackt wurde. 
Wir beginnen mit einem relativ großen Kreis von 3.784 Titeln.
Die Titelnummern befinden sich in der Textdatei.

Hinweis: Möglicherweise müssen die Titelnummern etwas angepasst werden: z.B. ich habe `102012` aber die Titelnummern in https://github.com/rism-international/tasks/issues/949 weisen führende Nullen auf: `000000102012`. Ich hoffe, das ist nicht problematisch.

[abgehackte245.txt](https://github.com/rism-international/tasks/files/8152167/abgehackte245.txt)

**Comment by HirschSt** [comment]
Führende Nullen sind nicht problematisch, das Archiv mit den Titelnummern ist beigefügt.
[pikado.zip](https://github.com/rism-international/tasks/files/8161424/pikado.zip)

**Comment by BaMikusi** [comment]
Vielen Dank für die schnelle Erledigung.

**Comment by HirschSt** [comment]
War nicht so schwer, aber trotzdem danke!

Am Di., 1. März 2022 um 14:11 Uhr schrieb BaMikusi ***@***.***

**Comment by HirschSt** [comment]
Etwas code für spätere Fälle:

```ruby
require 'pry'

nx = File.readlines('no.txt').map {|e| e.to_i }

res = {}
id = nil

File.foreach("tit.ascii").each do | line |
  if line.start_with?("000")
    puts line
    tmp_id = line[3..-1].to_i
    if nx.include?(tmp_id)
      id = tmp_id
      res[id] = []
    else
      if res[id]
        File.write("./#{id}.txt", res[id].join)
      end
      res = {}
      id = nil
    end
  end
  if id
    res[id] << line
  else
    next
  end
end
```
