### ISSUE TITLE
Renew 856$x digitized version linktypes

### ISSUE THREAD

**Issue by HirschSt** [rism-international/tasks#951]
Since there are some confusing with "[digitized version]", we need a new restart of cleaning up these value according the rule for **sources and holdings** in 856$z

- digitized
- Digitized
- digital
- Digital
- Digitisation
- Manuscriptorium

so -> 856$z ~= /Regexp.union(list)/i -> 856$x"Digitized"

**Comment by xhero** [comment]
`Digitized` is the value we are using

**Comment by HirschSt** [comment]
Please doublecheck https://raw.githubusercontent.com/rism-international/muscat-maintenance/master/log/20220302-repair-856.log (from https://github.com/rism-international/muscat-maintenance/commit/d4a720e1d2d3165d60b3c1aa928bc9214a6b5aee)

**Comment by jenniferward** [comment]
Eigentlich meinten wir, nur leere $x sollen ergänzt werden, siehe https://github.com/rism-international/tasks/issues/497

> !! Wichtig: Voraussetzung: Link type 856 $x muss leer sein; vorhandenen Linktyp bitte nicht überschreiben!!

Der Skript hat auch u.a. "Bach Digital" gefunden und geändert von `Other` in `Digitized` - das ist falsch!

(Wobei ich einige Fehlerchen unsererseits gefunden habe, also insofern war das hilfreich, danke)

**Comment by HirschSt** [comment]
Danke, das hatte ich mir ebenfalls gedacht. Ich ändere das Skript so, dass nur leere 856$x ergänzt werden, und stelle eine neue Protokolldatei ein - das ist kein Problem.

**Comment by HirschSt** [comment]
New version without changing existing $x nodes see https://raw.githubusercontent.com/rism-international/muscat-maintenance/master/log/20220302-repair-856.log (from https://github.com/rism-international/muscat-maintenance/commit/121728f952e743f88d9d7d2a67b763635f164c27)

**Comment by jenniferward** [comment]
Vielen Dank, das sieht gut aus. 
Es wäre gut, wenn jemand ein frisches Auge drauf werfen könnte.

**Comment by MFalletta** [comment]
Sieht gut aus!
