### ISSUE TITLE
Musikdrucke in Rostock D-ROu

### ISSUE THREAD

**Issue by DadimoPflege** [rism-international/tasks#952]
Liste der im RISM-OPAC verzeichneten Drucke aus ihrem Bestand, der abzulesen ist, für welche Bestände noch keine Digitalisate vorliegen (auch nicht von Exemplaren anderer Bibliotheken) ​und welche Musikdrucke in Rostock D-ROu ggf. unikal überliefert sind. Ziel ist, auf dieser Grundlage dann Priorisierungen von Digitalisierungsvorhaben vorzunehmen.

**Comment by HirschSt** [comment]
done with https://github.com/rism-international/muscat-maintenance/commits/master

report at https://github.com/rism-international/muscat-maintenance/blob/master/report/2022-04-18_rostock.csv, raw at https://raw.githubusercontent.com/rism-international/muscat-maintenance/master/report/2022-04-18_rostock.csv
