### ISSUE TITLE
Check OENB Import file

### ISSUE THREAD

**Issue by HirschSt** [rism-international/tasks#953]
TODOs
- [ ] 001 id: entpricht nicht der Muscat-Spezifikation -> wird in Muscat ids konvertiert
- [ ] 001 id: teilweise mehrfach vorhanden; Dubletten?
- [ ] 099 soll als Template in den Leader überführt werden 
- [x] 970 (wurde gelöscht)
- [x] wf_owner leer, wer soll eingetragen werden? Traunsteiner mit alias-rism.info Adresse

**Comment by jenniferward** [comment]
970 kann für diese Phase ignoriert werden!

**Comment by HirschSt** [comment]
Wenn ich das Feld einspiele, wird es nicht ignoriert... also muss es aus der Datei raus

**Comment by jenniferward** [comment]
Danke für die Ruckmeldung. Kannst du das Feld löschen, oder soll ich das machen?

**Comment by jenniferward** [comment]
Sicherheitshalber schicke ich dir eine Datei ohne 970, Mail kommt in Kürze.

**Comment by HirschSt** [comment]
Danke! Es gibt einige neue Anforderungen, die sich ergeben haben, s. o. unter den TODOs

**Comment by BaMikusi** [comment]
Die Kollegin, die unsere Verständnisfragen aus Wien beantwortet habe, ist die stellvertretende Leiterin der ÖNB-Musiksammlung, die offenbar auch für die Katalogisierung verantwortlich ist. M.E. sollten wir also als Besitzerin am besten sie nennen: Christa Traunsteiner

**Comment by HirschSt** [comment]
Danke. Hier bräuchte ich nur noch die Mail-Adresse von Frau Traunsteiner, um sie als Muscat-Nutzerin anzulegen. Am besten an mich per Mail (nicht über Github).

**Comment by MFalletta** [comment]
Für den Import können die RISM IDs ab 600100001 genutzt werden.

**Comment by HirschSt** [comment]
In der Import-Datei sind einige IDs mehrfach vergeben (s. 990052322310603338 insgesamt 3x). In der ursprünglichen OAI-Datei war die ID nur einmal vorhanden. @jenniferward bitte nachprüfen, ob es sich um Dubletten handelt

**Comment by HirschSt** [comment]
Hier die Liste mit ID + Anzahl der Dubletten: 
[doubl.csv](https://github.com/rism-international/tasks/files/8520498/doubl.csv)
