### ISSUE TITLE
GB-Lbl: Exemplarinfos ergänzen

### ISSUE THREAD

**Issue by jenniferward** [rism-international/tasks#954]
(Siehe auch #841) 

In dieser Tabelle handelt es sich um 191 Exemplare aus GB-Lbl, die schon nachgewiesen sind. Die BL hat aber zusätzliche Infos geliefert, die wir ergänzen sollen. 

- 001: RISM-ID. Der Skript muss den Exemplareintrag finden, wo 852$a = GB-Lbl
- 852$c: Bitte komplett überschreiben. 
- Sonstige Felder neu ergänzen, auch wenn z.B. ein 856 oder 500 schon vorhanden ist. (Nicht überschreiben.)

[02-vorhandene-exemplare.xlsx](https://github.com/rism-international/tasks/files/8324986/02-vorhandene-exemplare.xlsx)

**Comment by HirschSt** [comment]
Ist jetzt auf beta umgesetzt, z.B. https://beta.rism.info/admin/sources/990059038#holding_232747 (prüfbar bis 14.4.2022)
Bitte Rückmeldung geben, ob das so übernommen werden kann

**Comment by jenniferward** [comment]
Leider konnte ich nichts bis zu dem Zeitpunkt prüfen, weil ich abwesend war. Können die Daten bitte wieder eingespielt werden?

**Comment by HirschSt** [comment]
Kein Problem, ich habe die Daten erneut eingespielt, prüfbar bis 1.5.2022

**Comment by jenniferward** [comment]
Vielen Dank!
Die Angaben aus 856$u,	856$x und 856$z sind nicht mitgekommen, z.B. https://beta.rism.info/admin/sources/990059038#holding_232747 

001 | 852$c | 500$a | 500$a | 856$u | 856$x | 856$z
-- | -- | -- | -- | -- | -- | --
00000990059038 | A.277.(7.) | Copy at A.277.(7.). Imperfect: canto part book only. | Title information: Corona, il secondo libro delle canzoni alla   Napolitana à tre voci. In Vinegia: Appresso Girolamo Scotto, MDLXXI [1571]. | http://explore.bl.uk/BLVU1:LSCOP-ALL:BLL01004650112 | Other | Description in British Library catalogue


Ein Link zum Digitalisat war zwar schon vorhanden, aber hier gehört einen zusätzlichen Link zum Katalogisat. Ich habe bei der Prüfung keine Links zu Katalogeinträgen gesehen. Können diese nachgetragen werden?

**Comment by HirschSt** [comment]
Kein Problem, ich habe es nochmal durchlaufen lassen, bitte erneut prüfen

**Comment by jenniferward** [comment]
Danke! Alle Angaben sind nun da.
