### ISSUE TITLE
GB-Lbl: Publikationsjahr

### ISSUE THREAD

**Issue by jenniferward** [rism-international/tasks#955]
(Siehe auch #841) 

In dieser Tabelle handelt es sich um Publikationsjahre im Feld 260$c (auf bibliographischer Ebene), die wir anhand von Daten aus GB-Lbl ergänzen können. Summe: 496 Zeilen
Dabei soll das Feld 260$c ergänzt werden mit einem Hinweis im Feld 500$a: `Year of publication from British Library catalogue.`
Wir bleiben auf bibliographischer Ebene.

Voraussetzung: Das Feld 260$c soll leer sein. Falls nicht, bitte Bescheid geben.

[03-Publikationsjahr.xlsx](https://github.com/rism-international/tasks/files/8324992/03-Publikationsjahr.xlsx)

**Comment by HirschSt** [comment]
In zwei Titeln ist 260$c nicht leer: 990014805 und 990025825 (hier gibt es kein Exemplar aus GB-Lbl). @jenniferward bitte prüfen

**Comment by jenniferward** [comment]
Vielen Dank für die Mitteilung. In den zwei genannten Titeln handelt es sich um Änderungen, die erst vor kuzem erfolgten. In beiden Fällen stimmen die Angaben mit denen aus GB-Lbl überein. Von daher kann man die Titel einfach überspringen. Ist das möglich?

(Das Exemplar zu 990025825  kommt mit #841.)

**Comment by HirschSt** [comment]
done with https://github.com/rism-international/muscat-maintenance/commits/master

Ja, die beiden Titel können übergangen werden. Ich muss die Daten allerdings erneut einspielen, ab Montag bitte prüfen und Rückmeldung geben.

**Comment by HirschSt** [comment]
Bitte prüfen unter beta, z.B. https://beta.rism.info/admin/sources/00000990063509

**Comment by jenniferward** [comment]
Oh hoppla, eine Sache ist mir erst jetzt aufgefallen: ich hätte Angaben wie `[approximately 1729]` und `[between 1702 and 1710?]`  in `[ca. 1729]` bzw. `[1702-1710?]` ändern sollen. Kann man das noch korrigieren?  Falls ja, hänge ich eine korrigierte Tabelle an (990014805 und 990025825 habe ich gelöscht aus der Tabelle):

[03-Publikationsjahr-a.xlsx](https://github.com/rism-international/tasks/files/8565084/03-Publikationsjahr-a.xlsx)

**Comment by HirschSt** [comment]
Ja, die Angaben können noch korrigiert werden

**Comment by HirschSt** [comment]
Ist jetzt auf beta eingespielt, bitte prüfen

**Comment by jenniferward** [comment]
Das sieht stichprobenartig in Ordnung aus.
