### ISSUE TITLE
US-Wc: Digitalisate

### ISSUE THREAD

**Issue by jenniferward** [rism-international/tasks#958]
Bitte diese Tabelle mit Links zu Digitalisaten und Signaturen ergänzen. Es handelt sich um Drucke aus US-Wc.
Eine Signatur ist manchmal in Muscat schon vorhanden aber am Besten die Angaben komplett überschreiben.

Importiert werden:
- 856$u	
- 856$x	
- 856$z	
- 852$c
[US-Wc-Digitalisate-2022-04.xlsx](https://github.com/rism-international/tasks/files/8565216/US-Wc-Digitalisate-2022-04.xlsx)

**Comment by HirschSt** [comment]
Ist umgesetzt (https://github.com/rism-international/muscat-maintenance/commit/310b154d9ab60a9e5497ae35c7b92f947d265bde)

Bitte auf beta prüfen, s. https://raw.githubusercontent.com/rism-international/muscat-maintenance/master/log/2022-05-01_wc.log, danke

**Comment by jenniferward** [comment]
Ich habe stichprobenartig geprüft und alles sieht korrekt aus.
