### ISSUE TITLE
Muscat, Normdaten, Register Titel / Textincipit: Einträge ohne Verknüpfung zu Quellen

### ISSUE THREAD

**Issue by Docudoctor** [rism-international/tasks#963]
Lieber Stephan,
bitte Einträge ohne Verknüpfung zu Quellen aus dem Register Titel / Textincipit für einen weiteren Check durch mich extrahieren. 
Einträge ohne Verknüpfung werden im Register ohne Type aufgeführt.
Das betrifft mehr als 16.500 Einträge.

Besten Dank,
Guido

**Comment by HirschSt** [comment]
Tabelle jetzt verfügbar unter https://raw.githubusercontent.com/rism-international/muscat-maintenance/master/report/2022-08-08_title.csv
