### ISSUE TITLE
Maintenance to change 593$a and add 593$b in sources and holdings

### ISSUE THREAD

**Issue by HirschSt** [rism-international/tasks#967]
see https://github.com/rism-digital/muscat/issues/1248

**Comment by HirschSt** [comment]
done with https://github.com/rism-international/muscat-maintenance/commit/e55dc067dbe2e68d96a338d3673bbaf96b6d860f

Please doublecheck the (huge) log-file listing all the changes at https://github.com/rism-international/muscat-maintenance/blob/master/log/2022-05-12_add_593b_source.bz2.tar

**Comment by BaMikusi** [comment]
I have looked at the log file, but it's somewhat beyond human capacity to double-check such stuff -- perhaps it should be meaningful to wait until Andrew gets a dump for testing in RISM Online? That would likely say more than what my eyes can catch here.

**Comment by HirschSt** [comment]
If its too difficult for you then you can check it also directly in muscat-test
