### ISSUE TITLE
ÖNB: 040$b ergänzen

### ISSUE THREAD

**Issue by jenniferward** [rism-international/tasks#976]
Die Titel in diesem Ordner:
https://muscat.rism.info/admin/folders/909
bitte mit `040  ##$bger` ergänzen.
Katalogisierungssprache: Deutsch

**Comment by HirschSt** [comment]
Sehe ich das richtig, dass das einfach alle importierten Titel von A-Wn (owner: Traunsteiner) sind?

**Comment by jenniferward** [comment]
Ja, das stimmt auch!

**Comment by HirschSt** [comment]
Was ist mit 040$a?
```xml
<marc:datafield tag="040" ind1=" " ind2=" ">
   <marc:subfield code="a">DE-633</marc:subfield>
</marc:datafield>

```

**Comment by jenniferward** [comment]
$a soll beibehalten werden. Bitte $b ergänzen.

**Comment by HirschSt** [comment]
040$a befindet sich nicht in den Daten, sondern wird dynamisch beim Export generiert, s. https://github.com/rism-digital/muscat/blob/2bc8109706a2c8eecfaec5bc872980eae5877232/lib/marc_source.rb#L456

Katalogisierungsquelle bei den importierten Daten wäre aber doch eher A-Wn, also "040$aAT-OeNB".
Ich würde entsprechend vorschlagen, bei den Titeln aus A-Wn die Angabe explizit einzutragen

**Comment by jenniferward** [comment]
Das wäre mir neu, haben wir das bisher immer so gemacht mit 040$a bei den importierten Daten? 
Mexico: https://muscat.rism.info/admin/sources/120003043.xml
ICCU:  https://muscat.rism.info/admin/sources/850817621.xml
BnF: https://muscat.rism.info/admin/sources/840015878.xml

In den MEX-Daten stand: 
=040  \\$aMusicat
Das hatte ich gelöscht...aber das kann ich gerne beim nächsten Import berücksichtigen.
