### ISSUE TITLE
A-Wn bereits in Muscat: Links ergänzen

### ISSUE THREAD

**Issue by jenniferward** [rism-international/tasks#977]
422 Titel aus dem ÖNB-Import waren bereits in Muscat vorhanden. Von diesen ÖNB-Titeln habe ich die Links genommen (Links zu Digitalisaten, Links zu Karteikarten) und zusätzlich Links zum jeweiligen Katalogisat erstellt. Bitte diese Links ergänzen.

[06-only-856s.zip](https://github.com/rism-international/tasks/files/9902810/06-only-856s.zip)

**Comment by HirschSt** [comment]
done with https://github.com/rism-international/muscat-maintenance/commit/c3953862f1bae326fe41e62b5745d7f18f13bb82

**Comment by jenniferward** [comment]
Soll ich das gegenchecken? Ist alles auf beta?

**Comment by HirschSt** [comment]
Nein, im Moment spiele ich testweise alle aktuellen Abläufe neu ein. Ab morgen kann dann auf beta geprüft werden.

**Comment by jenniferward** [comment]
Ich habe die Titel stichprobenartig geprüft und sie sehen in Ordnung aus.
