### ISSUE TITLE
ICCU: 852 $c Signaturen vererben

### ISSUE THREAD

**Issue by MFalletta** [rism-international/tasks#982]
852 $c: Signaturen aus dem Sammlungseintrag bitte in die Teileinträge vererben, 
Bsp.
Sammlung: I-MOe Mus.F.99 https://muscat.rism.info/admin/sources/850609014 
Teileintrag: I-MOe [no indication] https://muscat.rism.info/admin/sources/850765851 

Betroffen davon sind verschiedene Bibliothekssigel, daher mögliche Auswahlkriterien:
Besitzer: Massimo Gentili-Tedeschi 
852 $c in übergeordnetem Sammlungseintrag ungleich [no indication]
852 $c in untergeordnetem Teileintrag gleich [no indication]

**Comment by HirschSt** [comment]
Ist auf beta umgesetzt, z.B. https://beta.rism.info/admin/sources/850765851

Bitte anhand der Datei https://github.com/rism-international/muscat-maintenance/blob/master/log/20230220-iccu_inherit_shelfmark.log prüfen. 

done with https://github.com/rism-international/muscat-maintenance/commit/8915baa49138c4d88db0dabb5e7646d5ae8fc91d

**Comment by MFalletta** [comment]
Sieht gut aus, danke!
