### ISSUE TITLE
ICCU: Nicht vererbte Komponistennamen in handschriftlichen Collections

### ISSUE THREAD

**Issue by Docudoctor** [rism-international/tasks#993]
Bitte in den ICCU-Daten nach Collection-Haupteinträgen mit Komponist im Marc-Feld 100 suchen, deren Teileinträge im Feld 100 nur "Anonymus" aufweisen. In den Originaldaten wurden bei einer Anzahl von Collections die Komponisten nicht in den Teileinträgen vererbt. 

Die Resultate bitte in einer Tabelle mit folgenden Spalten darstellen:
Spalte 1: RISM ID
Spalte 2: Templatetyp 
Spalte 3: MARC-Feld 100
Spalte 4: RISM-Sigel
Spalte 5: Signatur

**Comment by HirschSt** [comment]
Tabelle ist unter https://github.com/rism-international/muscat-maintenance/blob/master/report/20230608-ICCU_check_composer.csv verfügbar
