### ISSUE TITLE
Create IIIf-table for D-Dl

### ISSUE THREAD

**Issue by HirschSt** [rism-international/tasks#994]
next step in the IIIf saga

**Comment by jenniferward** [comment]
Mir ist etwas aufgefallen, der vielleicht mit diesem Ticket zu tun hat. 856$x `Digitized` bzw. `IIIF manifest (digitized source)` bezieht sich nur auf die Quelle, die im Katalogisat beschrieben wird. Manchmal verlinkt die Bibliothek aber auch auf andere relevante Digitalisate, z.B. Stempel oder Libretti. Diese sind aber nicht `Digitized`  bzw. `IIIF manifest (digitized source)`  sondern `Other` bzw. `IIIF manifest (other)` .

In diesem Titel
https://muscat.rism.info/admin/sources/270001873#holding_51046066 
heißt es im $z `[digitized version] Digitalisat des Librettos` und von daher ist `IIIF manifest (other)` richtig.  Durch ein Skript wurde fälschlicherweise `IIIF manifest (digitized source)` vergeben (siehe Änderungsgeschichte) .

Gab es eine Liste von der Bibliothek? Man muss im $z prüfen oder mit der Bibliothek klären, ob die Muscat-Quelle beschrieben wird oder eine andere Resourse.

**Comment by HirschSt** [comment]
Das Problem ist, dass nur die Links zu den IIIF-Manifesten generiert wurden. Was sich dahinter jeweils verbirgt, weiß i. d. R. noch nicht mal die Bibliothek. Eine Liste, was Digitalisate von Quellen sind und was ev. andere Digitalisate, gab es leider nicht.

**Comment by jenniferward** [comment]
Woher stammten die Angaben in 856$z?
