### ISSUE TITLE
Missing 710$a in BSB export

### ISSUE THREAD

**Issue by HirschSt** [rism-international/tasks#995]
Kann es sein, dass 710$a fehlt? Oder zumindest, wenn $4fmo bei den Drucken im Haupteintrag (nicht Exemplar) ist?
=710  2\$a$cOlten$030000283$4fmo
Der Text aus $a (der Name) fehlt? Im OPAC wird der Name nicht angezeigt:
https://opac.rism.info/search?id=407002407&View=rism
RISM Online kann den Namen finden und anzeigen:
https://rism.online/sources/407002407
Muscat: https://muscat.rism.info/admin/sources/407002407
RISM Online[RISM Online](https://rism.online/sources/407002407)
RISM Online
RISM Online provides access to millions of musical records from a global collection of music libraries, archives, and cultural centres.

Möglicherweise ist eine Rails-Migration nicht gelaufen. Ich mache heute mal einen Probeexport und schaue, ob das Problem weiterhin auftritt.

**Comment by HirschSt** [comment]
Im Test werden nach der DB-Migration die Felder wieder exportiert. Es wäre noch zu klären, ob wir die BSB bitten sollen, eine korrigierte Nachlieferung einzuspielen, oder ob es genügt, den Fehler mit der nächsten Lieferung zu beheben.

**Comment by BaMikusi** [comment]
Bitte die Kollegen in München (insbesondere Herrn Lutz) benachrichtigen und das Problem kurz erklären -- am besten sollte die BSB entscheiden, ob sie nun eine neue Einspielung der Daten unternehmen wollen.

**Comment by HirschSt** [comment]
Es wurde vereinbart, die nächste Datenlieferung abzuwarten
