### ISSUE TITLE
593$a in CMP anpassen

### ISSUE THREAD

**Issue by jenniferward** [rism-international/tasks#996]
Im Templatetyp CMP soll 593$a `Composite` lauten. Bitte bisherige $a entsprechend ändern. Das kommt ca. 770x vor (manchmal mehrmals).
Beispiele: https://muscat.rism.info/admin/sources/1001155036/edit
`Print`

https://muscat.rism.info/admin/sources/1001182000/edit
`Print`
`Manuscript copy`

**Comment by HirschSt** [comment]
Bitte auf beta anhand von https://github.com/rism-international/muscat-maintenance/blob/master/log/20230614_change_593a.log kurzfristig prüfen

**Comment by jenniferward** [comment]
Ich habe mit ein paar Hundert mehr gerechnet. Hat der Skript auch die Titel gefunden, wo z.B. `Other` in 593$a steht? 
https://beta.rism.info/admin/sources/400101958
https://beta.rism.info/admin/sources/1001056388 
https://beta.rism.info/admin/sources/469517500 `Manuscript copy`
https://beta.rism.info/admin/sources/1001248582 --> dort nichts in 593$a


Es gibt manchmal mehrere Materialgruppen und 593$a kommt in diesen Fällen mehrmals vor:
https://beta.rism.info/admin/sources/1001182000
https://beta.rism.info/admin/sources/1001184806
https://beta.rism.info/admin/sources/1001185214

Auch in den anderen Gruppen muss 593$a geändert werden.

**Comment by HirschSt** [comment]
Danke, völlig richtig:  ich hatte aus irgendwelchen Gründen nur nach "Prints" gesucht. Das ist jetzt korrigiert, bitte erneut auf beta prüfen, s. https://github.com/rism-international/muscat-maintenance/blob/master/log/20230614_change_593a.log

**Comment by jenniferward** [comment]
Danke, sieht gut aus!
